In [2]:
import pandas as pd
import random
import numpy as np

In [2]:
mzc = pd.read_csv('C:/Users/Trine/Desktop/my_data/data_sorting.csv')
mzc = mzc.fillna(5)
storeId = mzc.loc[:, 'store_id']
mask = storeId.duplicated()
storeId_dealed = storeId[~mask]
len(storeId_dealed)
mzc = pd.DataFrame(mzc, dtype = int)
mzc.head()

,store_id,shot_state,action_id,mzc_sku,mzc_flag,yp_sku,yp_flag,hs_sku,hs_flag,nyn_sku,nyn_flag,atm_sku,atm_flag,msj_sku,msj_flag,fh_sku,fh_flag
0,71701,0,1416487,99,1,25,0,154,1,12,5,4,5,84,1,0,5
1,71701,5,1743906,97,1,23,5,151,1,12,5,6,5,85,1,0,5
2,71701,5,2495574,90,0,7,5,102,0,21,0,7,5,60,0,0,5
3,71701,5,2545031,88,5,6,5,95,5,19,5,9,0,58,5,0,5
4,71701,5,4263724,87,5,8,5,90,5,19,5,0,5,57,5,0,5

In [51]:
brand = ['mzc', 'yp', 'hs', 'nyn', 'atm', 'msj', 'fh']
out_data = pd.DataFrame(columns= brand)

try:
    for i in storeId_dealed:
        store = mzc.loc[storeId == i, :]
        out = pd.DataFrame()
        for j in brand:
            flag = str(j) + '_flag'
            sku = str(j) + '_sku'
            mean = np.mean((store.loc[:, sku]))
            to_one=store.loc[:, sku]/mean
            out[j]=to_one
        out_data = pd.concat([out_data,out]) 
             
except AttributeError:
     print('错误')
#out_data.reset_index(inplace = True)
#out_data.drop('store_id', axis=1, inplace = True)

0    1.073753
1    1.052061
2    0.976139
3    0.954447
4    0.943601
Name: mzc_sku, dtype: float64
0    1.811594
1    1.666667
2    0.507246
3    0.434783
4    0.579710
Name: yp_sku, dtype: float64
0    1.300676
1    1.275338
2    0.861486
3    0.802365
4    0.760135
Name: hs_sku, dtype: float64
0    0.722892
1    0.722892
2    1.265060
3    1.144578
4    1.144578
Name: nyn_sku, dtype: float64
0    0.769231
1    1.153846
2    1.346154
3    1.730769
4    0.000000
Name: atm_sku, dtype: float64
0    1.220930
1    1.235465
2    0.872093
3    0.843023
4    0.828488
Name: msj_sku, dtype: float64
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: fh_sku, dtype: float64
5     0.897770
6     0.884758
7     1.118959
8     1.001859
9     1.001859
10    1.092937
11    1.001859
Name: mzc_sku, dtype: float64
5     1.117647
6     1.000000
7     1.019608
8     0.960784
9     1.000000
10    0.823529
11    1.078431
Name: yp_sku, dtype: float64
5     0.897436
6     0.830128
7     0.852564
8     1.144231
9     1.189103
10    1.009615
11    1.076923
Name: hs_sku, dtype: float64
5     1.2
6     1.0
7     0.9
8     0.9
9     1.0
10    1.1
11    0.9
Name: nyn_sku, dtype: float64
5     1.040541
6     0.662162
7     0.945946
8     0.945946
9     1.324324
10    0.945946
11    1.135135
Name: atm_sku, dtype: float64
5     0.937322
6     0.897436
7     1.017094
8     0.997151
9     1.056980
10    0.957265
11    1.136752
Name: msj_sku, dtype: float64
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
Name: fh_sku, dtype: float64
12    1.154745
13    0.991241
14    0.960584
15    1.032117
16    0.950365
17    1.001460
18    0.909489
Name: mzc_sku, dtype: float64
12    1.442897
13    1.696379
14    0.000000
15    1.306407
16    1.208914
17    1.345404
18    0.000000
Name: yp_sku, dtype: float64
12    1.267135
13    1.254833
14    1.230228
15    1.119508
16    1.021090
17    1.070299
18    0.036907
Name: hs_sku, dtype: float64
12    0.494949
13    0.636364
14    1.131313
15    1.202020
16    1.202020
17    1.060606
18    1.272727
Name: nyn_sku, dtype: float64
12    0.411765
13    0.391176
14    1.420588
15    1.255882
16    1.194118
17    1.276471
18    1.050000
Name: atm_sku, dtype: float64
12    0.000000
13    0.000000
14    1.395189
15    1.419244
16    1.298969
17    1.395189
18    1.491409
Name: msj_sku, dtype: float64
12    0.000000
13    0.000000
14    1.391813
15    1.187135
16    1.473684
17    1.473684
18    1.473684
Name: fh_sku, dtype: float64
19    1.197368
20    1.105263
21    1.031579
22    0.902632
23    0.921053
24    0.921053
25    0.921053
Name: mzc_sku, dtype: float64
19    1.045840
20    1.057725
21    1.687606
22    0.808149
23    0.808149
24    0.796265
25    0.796265
Name: yp_sku, dtype: float64
19    1.064384
20    1.160274
21    1.006849
22    0.930137
23    0.968493
24    0.939726
25    0.930137
Name: hs_sku, dtype: float64
19    0.816667
20    1.516667
21    1.575000
22    0.816667
23    0.700000
24    0.816667
25    0.758333
Name: nyn_sku, dtype: float64
19    0.943005
20    1.051813
21    1.051813
22    1.015544
23    0.906736
24    1.015544
25    1.015544
Name: atm_sku, dtype: float64
19    1.312500
20    1.361111
21    1.458333
22    0.704861
23    0.729167
24    0.704861
25    0.729167
Name: msj_sku, dtype: float64
19    1.101852
20    1.101852
21    1.058642
22    0.885802
23    0.950617
24    0.950617
25    0.950617
Name: fh_sku, dtype: float64
26    1.088553
27    0.755940
28    1.920086
29    0.907127
30    0.952484
31    0.226782
32    1.149028
Name: mzc_sku, dtype: float64
26    0.948387
27    1.038710
28    1.016129
29    0.564516
30    0.970968
31    1.422581
32    1.038710
Name: yp_sku, dtype: float64
26    1.378238
27    1.233161
28    1.015544
29    0.834197
30    0.870466
31    0.797927
32    0.870466
Name: hs_sku, dtype: float64
26   NaN
27   NaN
28   NaN
29   NaN
30   NaN
31   NaN
32   NaN
Name: nyn_sku, dtype: float64
26   NaN
27   NaN
28   NaN
29   NaN
30   NaN
31   NaN
32   NaN
Name: atm_sku, dtype: float64
26    7.0
27    0.0
28    0.0
29    0.0
30    0.0
31    0.0
32    0.0
Name: msj_sku, dtype: float64
26    0.000000
27    0.000000
28    0.000000
29    3.818182
30    1.113636
31    1.431818
32    0.636364
Name: fh_sku, dtype: float64
33    1.309353
34    0.839329
35    1.107914
36    0.990408
37    0.705036
38    1.242206
39    0.805755
Name: mzc_sku, dtype: float64
33    0.825328
34    0.855895
35    1.039301
36    0.855895
37    0.703057
38    1.131004
39    1.589520
Name: yp_sku, dtype: float64
33    0.883838
34    0.954545
35    1.095960
36    0.795455
37    0.848485
38    0.777778
39    1.643939
Name: hs_sku, dtype: float64
33    0.933333
34    0.933333
35    0.000000
36    0.233333
37    1.166667
38    1.633333
39    2.100000
Name: nyn_sku, dtype: float64
33    0.863014
34    0.767123
35    0.000000
36    1.150685
37    1.438356
38    1.342466
39    1.438356
Name: atm_sku, dtype: float64
33   NaN
34   NaN
35   NaN
36   NaN
37   NaN
38   NaN
39   NaN
Name: msj_sku, dtype: float64
33   NaN
34   NaN
35   NaN
36   NaN
37   NaN
38   NaN
39   NaN
Name: fh_sku, dtype: float64
40    0.690265
41    0.530973
42    1.778761
Name: mzc_sku, dtype: float64
40    3.0
41    0.0
42    0.0
Name: yp_sku, dtype: float64
40    0.176471
41    2.823529
42    0.000000
Name: hs_sku, dtype: float64
40    3.0
41    0.0
42    0.0
Name: nyn_sku, dtype: float64
40   NaN
41   NaN
42   NaN
Name: atm_sku, dtype: float64
40    0.0
41    3.0
42    0.0
Name: msj_sku, dtype: float64
40    1.5
41    1.5
42    0.0
Name: fh_sku, dtype: float64
43    1.151316
44    1.019737
45    1.151316
46    0.789474
47    0.888158
Name: mzc_sku, dtype: float64
43    1.328125
44    0.703125
45    0.937500
46    1.484375
47    0.546875
Name: yp_sku, dtype: float64
43    1.180556
44    1.250000
45    1.111111
46    1.111111
47    0.347222
Name: hs_sku, dtype: float64
43    1.333333
44    1.000000
45    1.333333
46    0.000000
47    1.333333
Name: nyn_sku, dtype: float64
43    0.952381
44    0.952381
45    0.952381
46    0.952381
47    1.190476
Name: atm_sku, dtype: float64
43    1.448598
44    0.560748
45    0.373832
46    1.728972
47    0.887850
Name: msj_sku, dtype: float64
43    5.0
44    0.0
45    0.0
46    0.0
47    0.0
Name: fh_sku, dtype: float64
48    0.713403
49    0.964175
50    1.119827
51    1.076590
52    0.981470
53    1.054972
54    1.089561
Name: mzc_sku, dtype: float64
48    0.921424
49    0.850907
50    1.034251
51    0.841504
52    1.109469
53    1.109469
54    1.132975
Name: yp_sku, dtype: float64
48    0.879646
49    0.854867
50    1.061357
51    1.077876
52    0.987021
53    1.082006
54    1.057227
Name: hs_sku, dtype: float64
48    0.467742
49    1.096774
50    1.080645
51    1.096774
52    1.064516
53    1.096774
54    1.096774
Name: nyn_sku, dtype: float64
48    0.735324
49    0.980433
50    1.002060
51    1.016478
52    1.038105
53    1.124614
54    1.102987
Name: atm_sku, dtype: float64
48    1.001052
49    1.001052
50    1.001052
51    0.986330
52    1.001052
53    1.008412
54    1.001052
Name: msj_sku, dtype: float64
48   NaN
49   NaN
50   NaN
51   NaN
52   NaN
53   NaN
54   NaN
Name: fh_sku, dtype: float64
55    0.973684
56    0.973684
57    0.921053
58    1.000000
59    1.131579
Name: mzc_sku, dtype: float64
55    0.989848
56    1.675127
57    0.862944
58    0.685279
59    0.786802
Name: yp_sku, dtype: float64
55    0.833333
56    0.746528
57    1.145833
58    1.423611
59    0.850694
Name: hs_sku, dtype: float64
55    1.8
56    1.2
57    2.0
58    0.0
59    0.0
Name: nyn_sku, dtype: float64
55    2.317073
56    1.463415
57    0.975610
58    0.000000
59    0.243902
Name: atm_sku, dtype: float64
55    1.286550
56    0.891813
57    0.906433
58    0.964912
59    0.950292
Name: msj_sku, dtype: float64
55    0.0
56    0.0
57    0.0
58    5.0
59    0.0
Name: fh_sku, dtype: float64
60    0.805888
61    0.805888
62    0.938362
63    1.037718
64    0.739650
65    0.673413
66    1.070837
67    1.468261
68    0.816927
69    1.611776
70    1.004600
71    1.026679
Name: mzc_sku, dtype: float64
60    1.490196
61    0.915033
62    1.385621
63    1.450980
64    1.150327
65    1.019608
66    0.810458
67    0.954248
68    0.745098
69    0.888889
70    0.549020
71    0.640523
Name: yp_sku, dtype: float64
60    1.159664
61    1.008403
62    1.149580
63    1.109244
64    0.847059
65    0.988235
66    1.078992
67    0.998319
68    0.957983
69    1.139496
70    0.695798
71    0.867227
Name: hs_sku, dtype: float64
60    1.677419
61    2.580645
62    1.290323
63    2.258065
64    1.290323
65    1.354839
66    1.548387
67    0.000000
68    0.000000
69    0.000000
70    0.000000
71    0.000000
Name: nyn_sku, dtype: float64
60    2.133333
61    1.066667
62    2.933333
63    1.600000
64    1.600000
65    0.800000
66    1.600000
67    0.000000
68    0.000000
69    0.266667
70    0.000000
71    0.000000
Name: atm_sku, dtype: float64
60    0.401163
61    0.680233
62    0.732558
63    0.802326
64    1.046512
65    0.837209
66    0.837209
67    1.534884
68    1.447674
69    2.145349
70    0.436047
71    1.098837
Name: msj_sku, dtype: float64
60     0.0
61     0.0
62     0.0
63     0.0
64     0.0
65     0.0
66     0.0
67     0.0
68     0.0
69     0.0
70     0.0
71    12.0
Name: fh_sku, dtype: float64
72    0.828947
73    1.171053
74    1.138158
75    0.934211
76    1.447368
77    0.480263
Name: mzc_sku, dtype: float64
72    0.36
73    0.00
74    4.56
75    1.08
76    0.00
77    0.00
Name: yp_sku, dtype: float64
72    1.147826
73    1.069565
74    2.191304
75    1.565217
76    0.026087
77    0.000000
Name: hs_sku, dtype: float64
72   NaN
73   NaN
74   NaN
75   NaN
76   NaN
77   NaN
Name: nyn_sku, dtype: float64
72   NaN
73   NaN
74   NaN
75   NaN
76   NaN
77   NaN
Name: atm_sku, dtype: float64
72    1.860465
73    0.186047
74    1.534884
75    1.488372
76    0.000000
77    0.930233
Name: msj_sku, dtype: float64
72   NaN
73   NaN
74   NaN
75   NaN
76   NaN
77   NaN
Name: fh_sku, dtype: float64
78    0.973054
79    2.005988
80    1.152695
81    0.568862
82    0.299401
Name: mzc_sku, dtype: float64
78    2.927928
79    0.225225
80    1.666667
81    0.180180
82    0.000000
Name: yp_sku, dtype: float64
78    1.915423
79    1.343284
80    1.243781
81    0.261194
82    0.236318
Name: hs_sku, dtype: float64
78    1.315789
79    0.921053
80    1.184211
81    1.184211
82    0.394737
Name: nyn_sku, dtype: float64
78    0.789474
79    1.052632
80    1.447368
81    1.052632
82    0.657895
Name: atm_sku, dtype: float64
78    0.803109
79    1.398964
80    1.450777
81    0.751295
82    0.595855
Name: msj_sku, dtype: float64
78   NaN
79   NaN
80   NaN
81   NaN
82   NaN
Name: fh_sku, dtype: float64
83    1.002604
84    0.937500
85    0.963542
86    1.171875
87    0.924479
Name: mzc_sku, dtype: float64
83    0.987654
84    1.028807
85    0.987654
86    0.802469
87    1.193416
Name: yp_sku, dtype: float64
83    0.972763
84    0.885214
85    0.953307
86    0.943580
87    1.245136
Name: hs_sku, dtype: float64
83    0.963855
84    0.722892
85    1.144578
86    0.722892
87    1.445783
Name: nyn_sku, dtype: float64
83    1.028037
84    0.747664
85    0.981308
86    0.747664
87    1.495327
Name: atm_sku, dtype: float64
83    0.662461
84    1.151420
85    1.340694
86    0.552050
87    1.293375
Name: msj_sku, dtype: float64
83   NaN
84   NaN
85   NaN
86   NaN
87   NaN
Name: fh_sku, dtype: float64
88    1.746835
89    1.206751
90    0.886076
91    0.708861
92    0.725738
93    0.725738
Name: mzc_sku, dtype: float64
88    0.000000
89    1.386555
90    1.487395
91    1.058824
92    1.033613
93    1.033613
Name: yp_sku, dtype: float64
88    1.632094
89    1.050881
90    1.003914
91    0.792564
92    0.804305
93    0.716243
Name: hs_sku, dtype: float64
88    0.00000
89    1.12500
90    1.31250
91    1.40625
92    1.03125
93    1.12500
Name: nyn_sku, dtype: float64
88    0.000000
89    1.714286
90    1.178571
91    0.750000
92    0.642857
93    1.714286
Name: atm_sku, dtype: float64
88    0.000000
89    1.162304
90    1.256545
91    1.256545
92    1.162304
93    1.162304
Name: msj_sku, dtype: float64
88   NaN
89   NaN
90   NaN
91   NaN
92   NaN
93   NaN
Name: fh_sku, dtype: float64
94    1.089109
95    0.910891
Name: mzc_sku, dtype: float64
94    0.190476
95    1.809524
Name: yp_sku, dtype: float64
94    0.946565
95    1.053435
Name: hs_sku, dtype: float64
94    0.0
95    2.0
Name: nyn_sku, dtype: float64
94    0.0
95    2.0
Name: atm_sku, dtype: float64
94    0.512397
95    1.487603
Name: msj_sku, dtype: float64
94    1.0
95    1.0
Name: fh_sku, dtype: float64
96     0.931238
97     0.966601
98     1.013752
99     1.025540
100    1.037328
101    1.025540
Name: mzc_sku, dtype: float64
96     2.170213
97     1.659574
98     1.659574
99     0.255319
100    0.255319
101    0.000000
Name: yp_sku, dtype: float64
96     0.886364
97     1.456612
98     0.904959
99     0.917355
100    0.923554
101    0.911157
Name: hs_sku, dtype: float64
96     1.914894
97     1.276596
98     1.021277
99     0.510638
100    0.638298
101    0.638298
Name: nyn_sku, dtype: float64
96     2.400000
97     1.733333
98     1.066667
99     0.266667
100    0.266667
101    0.266667
Name: atm_sku, dtype: float64
96     0.195918
97     0.808163
98     1.028571
99     1.273469
100    1.346939
101    1.346939
Name: msj_sku, dtype: float64
96     0.0
97     6.0
98     0.0
99     0.0
100    0.0
101    0.0
Name: fh_sku, dtype: float64
102    1.031847
103    0.993631
104    0.735669
105    0.984076
106    1.041401
107    1.012739
108    1.022293
109    1.194268
110    0.984076
Name: mzc_sku, dtype: float64
102    1.034934
103    0.969432
104    0.825328
105    0.903930
106    1.100437
107    1.034934
108    1.034934
109    1.021834
110    1.074236
Name: yp_sku, dtype: float64
102    0.873355
103    1.021382
104    0.947368
105    1.125000
106    1.080592
107    0.917763
108    1.021382
109    0.932566
110    1.080592
Name: hs_sku, dtype: float64
102    1.090909
103    1.090909
104    1.090909
105    1.090909
106    1.090909
107    1.000000
108    1.090909
109    0.727273
110    0.727273
Name: nyn_sku, dtype: float64
102    1.022727
103    0.818182
104    1.022727
105    1.125000
106    1.022727
107    1.227273
108    1.125000
109    0.409091
110    1.227273
Name: atm_sku, dtype: float64
102    1.021008
103    0.964286
104    0.983193
105    1.021008
106    1.002101
107    0.945378
108    1.096639
109    0.983193
110    0.983193
Name: msj_sku, dtype: float64
102    0.0
103    9.0
104    0.0
105    0.0
106    0.0
107    0.0
108    0.0
109    0.0
110    0.0
Name: fh_sku, dtype: float64
111    1.035422
112    0.991826
113    1.013624
114    0.959128
Name: mzc_sku, dtype: float64
111    1.137056
112    0.893401
113    0.954315
114    1.015228
Name: yp_sku, dtype: float64
111    1.082969
112    1.030568
113    0.960699
114    0.925764
Name: hs_sku, dtype: float64
111    0.965517
112    0.896552
113    1.034483
114    1.103448
Name: nyn_sku, dtype: float64
111    0.800000
112    0.533333
113    1.333333
114    1.333333
Name: atm_sku, dtype: float64
111    0.653595
112    0.862745
113    1.228758
114    1.254902
Name: msj_sku, dtype: float64
111   NaN
112   NaN
113   NaN
114   NaN
Name: fh_sku, dtype: float64
115    0.952174
116    0.952174
117    0.965217
118    0.821739
119    0.873913
120    1.200000
121    0.952174
122    1.082609
123    1.200000
Name: mzc_sku, dtype: float64
115    1.044993
116    1.031930
117    0.979681
118    0.940493
119    0.966618
120    1.123367
121    1.031930
122    0.888244
123    0.992743
Name: yp_sku, dtype: float64
115    1.018248
116    1.051095
117    1.067518
118    0.903285
119    0.919708
120    1.083942
121    1.067518
122    0.936131
123    0.952555
Name: hs_sku, dtype: float64
115    0.000000
116    0.000000
117    1.862069
118    0.000000
119    1.551724
120    1.551724
121    0.000000
122    1.862069
123    2.172414
Name: nyn_sku, dtype: float64
115    0.000000
116    0.000000
117    1.830508
118    0.000000
119    2.135593
120    2.135593
121    0.000000
122    1.525424
123    1.372881
Name: atm_sku, dtype: float64
115    0.933014
116    0.990431
117    0.990431
118    1.004785
119    1.004785
120    1.019139
121    0.990431
122    1.033493
123    1.033493
Name: msj_sku, dtype: float64
115    0.0
116    0.0
117    9.0
118    0.0
119    0.0
120    0.0
121    0.0
122    0.0
123    0.0
Name: fh_sku, dtype: float64
124    1.136176
125    0.953232
126    0.943604
127    0.962861
128    0.991747
129    0.962861
130    1.049519
Name: mzc_sku, dtype: float64
124    1.039936
125    0.961661
126    0.961661
127    0.939297
128    1.039936
129    0.995208
130    1.062300
Name: yp_sku, dtype: float64
124    1.068273
125    0.941767
126    0.899598
127    0.997992
128    1.096386
129    0.955823
130    1.040161
Name: hs_sku, dtype: float64
124    1.302326
125    0.976744
126    0.976744
127    0.976744
128    0.976744
129    0.895349
130    0.895349
Name: nyn_sku, dtype: float64
124    1.166667
125    1.020833
126    0.875000
127    0.875000
128    0.875000
129    1.020833
130    1.166667
Name: atm_sku, dtype: float64
124    1.038929
125    1.004866
126    0.970803
127    1.004866
128    1.021898
129    1.038929
130    0.919708
Name: msj_sku, dtype: float64
124   NaN
125   NaN
126   NaN
127   NaN
128   NaN
129   NaN
130   NaN
Name: fh_sku, dtype: float64
131    0.978723
132    0.957447
133    0.957447
134    0.957447
135    1.095745
136    1.010638
137    1.042553
Name: mzc_sku, dtype: float64
131    1.045333
132    0.970667
133    0.840000
134    1.045333
135    1.064000
136    0.970667
137    1.064000
Name: yp_sku, dtype: float64
131    0.875
132    1.125
133    0.925
134    0.925
135    1.150
136    0.900
137    1.100
Name: hs_sku, dtype: float64
131    0.865979
132    0.865979
133    0.865979
134    0.793814
135    1.298969
136    1.154639
137    1.154639
Name: nyn_sku, dtype: float64
131    1.333333
132    1.333333
133    1.333333
134    1.000000
135    0.666667
136    0.444444
137    0.888889
Name: atm_sku, dtype: float64
131    1.029925
132    1.082294
133    0.977556
134    0.977556
135    1.064838
136    1.029925
137    0.837905
Name: msj_sku, dtype: float64
131   NaN
132   NaN
133   NaN
134   NaN
135   NaN
136   NaN
137   NaN
Name: fh_sku, dtype: float64
138    0.986150
139    0.997230
140    0.975069
141    1.041551
Name: mzc_sku, dtype: float64
138    0.743590
139    1.102564
140    1.025641
141    1.128205
Name: yp_sku, dtype: float64
138    1.089109
139    1.188119
140    0.910891
141    0.811881
Name: hs_sku, dtype: float64
138    1.041096
139    1.205479
140    1.041096
141    0.712329
Name: nyn_sku, dtype: float64
138    0.946237
139    0.946237
140    0.946237
141    1.161290
Name: atm_sku, dtype: float64
138    1.100671
139    0.778523
140    1.181208
141    0.939597
Name: msj_sku, dtype: float64
138   NaN
139   NaN
140   NaN
141   NaN
Name: fh_sku, dtype: float64
142    1.024390
143    0.811530
144    1.064302
145    1.130820
146    0.984479
147    0.984479
Name: mzc_sku, dtype: float64
142    1.027624
143    0.983425
144    1.005525
145    1.016575
146    0.928177
147    1.038674
Name: yp_sku, dtype: float64
142    1.048276
143    0.855172
144    1.048276
145    1.075862
146    0.965517
147    1.006897
Name: hs_sku, dtype: float64
142    0.0000
143    0.0000
144    2.8125
145    1.1250
146    0.0000
147    2.0625
Name: nyn_sku, dtype: float64
142    0.000000
143    0.000000
144    1.935484
145    2.129032
146    0.000000
147    1.935484
Name: atm_sku, dtype: float64
142    1.142857
143    0.836735
144    1.142857
145    1.102041
146    0.938776
147    0.836735
Name: msj_sku, dtype: float64
142   NaN
143   NaN
144   NaN
145   NaN
146   NaN
147   NaN
Name: fh_sku, dtype: float64
148    0.928803
149    0.928803
150    0.883495
151    0.996764
152    1.177994
153    1.064725
154    1.019417

Name: mzc_sku, dtype: float64
148    1.056818
149    0.988636
150    0.909091
151    1.056818
152    1.068182
153    0.943182
154    0.977273
Name: yp_sku, dtype: float64
148    1.009009
149    1.059459
150    1.059459
151    1.046847
152    1.046847
153    0.756757
154    1.021622
Name: hs_sku, dtype: float64
148    0.768293
149    1.024390
150    1.024390
151    1.109756
152    1.024390
153    1.024390
154    1.024390
Name: nyn_sku, dtype: float64
148    1.066667
149    0.800000
150    1.066667
151    0.866667
152    1.200000
153    1.200000
154    0.800000
Name: atm_sku, dtype: float64
148    0.959762
149    0.928465
150    0.970194
151    1.043219
152    1.053651
153    1.011923
154    1.032787
Name: msj_sku, dtype: float64
148    0.0
149    0.0
150    0.0
151    0.0
152    0.0
153    7.0
154    0.0
Name: fh_sku, dtype: float64
155    0.869976
156    1.068558
157    1.021277
158    1.011820
159    0.964539
160    0.983452
161    1.030733
162    1.049645
Name: mzc_sku, dtype: float64
155    0.881119
156    0.909091
157    0.979021
158    1.020979
159    1.034965
160    1.104895
161    1.048951
162    1.020979
Name: yp_sku, dtype: float64
155    1.068592
156    1.020457
157    0.962696
158    1.010830
159    1.001203
160    1.058965
161    0.962696
162    0.914561
Name: hs_sku, dtype: float64
155    0.000000
156    1.493333
157    0.000000
158    1.493333
159    1.280000
160    1.280000
161    1.173333
162    1.280000
Name: nyn_sku, dtype: float64
155    0.000000
156    1.126761
157    0.000000
158    1.239437
159    1.690141
160    1.352113
161    1.352113
162    1.239437
Name: atm_sku, dtype: float64
155    0.928760
156    1.139842
157    1.055409
158    1.182058
159    0.907652
160    0.886544
161    0.970976
162    0.928760
Name: msj_sku, dtype: float64
155   NaN
156   NaN
157   NaN
158   NaN
159   NaN
160   NaN
161   NaN
162   NaN
Name: fh_sku, dtype: float64
163    1.457082
164    0.946352
165    0.736052
166    0.796137
167    0.901288
168    1.171674
169    0.991416
Name: mzc_sku, dtype: float64
163    0.651515
164    0.833333
165    1.045455
166    1.060606
167    1.196970
168    1.121212
169    1.090909
Name: yp_sku, dtype: float64
163    1.040948
164    1.025862
165    0.633621
166    0.859914
167    1.282328
168    1.040948
169    1.116379
Name: hs_sku, dtype: float64
163    0.591549
164    1.183099
165    1.281690
166    1.577465
167    0.887324
168    0.591549
169    0.887324
Name: nyn_sku, dtype: float64
163    0.658824
164    1.070588
165    0.905882
166    0.658824
167    1.482353
168    0.905882
169    1.317647
Name: atm_sku, dtype: float64
163    0.684444
164    1.306667
165    1.088889
166    1.368889
167    1.026667
168    0.777778
169    0.746667
Name: msj_sku, dtype: float64
163    7.0
164    0.0
165    0.0
166    0.0
167    0.0
168    0.0
169    0.0
Name: fh_sku, dtype: float64
170    1.125000
171    1.000000
172    0.972222
173    0.944444
174    0.958333
Name: mzc_sku, dtype: float64
170    0.375427
171    0.998294
172    1.211604
173    1.228669
174    1.186007
Name: yp_sku, dtype: float64
170    0.742297
171    1.036415
172    0.980392
173    1.106443
174    1.134454
Name: hs_sku, dtype: float64
170    0.756303
171    1.134454
172    0.840336
173    1.008403
174    1.260504
Name: nyn_sku, dtype: float64
170    0.876068
171    0.982906
172    1.217949
173    1.025641
174    0.897436
Name: atm_sku, dtype: float64
170    0.930556
171    1.111111
172    0.819444
173    1.000000
174    1.138889
Name: msj_sku, dtype: float64
170    0.000000
171    1.106115
172    1.276978
173    1.366906
174    1.250000
Name: fh_sku, dtype: float64
175    1.085714
176    1.057143
177    0.971429
178    0.971429
179    0.952381
180    0.961905
Name: mzc_sku, dtype: float64
175    1.168831
176    1.285714
177    0.909091
178    0.922078
179    0.831169
180    0.883117
Name: yp_sku, dtype: float64
175    1.183612
176    1.183612
177    0.928680
178    0.919575
179    0.901366
180    0.883156
Name: hs_sku, dtype: float64
175    0.914286
176    0.971429
177    1.028571
178    1.028571
179    1.028571
180    1.028571
Name: nyn_sku, dtype: float64
175    0.702128
176    0.702128
177    1.228723
178    1.196809
179    1.132979
180    1.037234
Name: atm_sku, dtype: float64
175    0.346570
176    0.801444
177    1.104693
178    1.277978
179    1.212996
180    1.256318
Name: msj_sku, dtype: float64
175    0.000000
176    0.000000
177    1.292308
178    1.476923
179    1.523077
180    1.707692
Name: fh_sku, dtype: float64
181    1.046358
182    1.072848
183    1.086093
184    0.993377
185    0.913907
186    0.887417
Name: mzc_sku, dtype: float64
181    1.192771
182    0.957831
183    1.048193
184    0.939759
185    0.957831
186    0.903614
Name: yp_sku, dtype: float64
181    0.960526
182    0.815789
183    0.750000
184    1.302632
185    1.171053
186    1.000000
Name: hs_sku, dtype: float64
181    1.183099
182    1.098592
183    1.352113
184    0.591549
185    0.845070
186    0.929577
Name: nyn_sku, dtype: float64
181    0.682464
182    0.767773
183    0.767773
184    1.279621
185    1.222749
186    1.279621
Name: atm_sku, dtype: float64
181    0.888889
182    0.987654
183    0.814815
184    0.987654
185    1.259259
186    1.061728
Name: msj_sku, dtype: float64
181    0.000000
182    0.000000
183    0.000000
184    1.571429
185    2.142857
186    2.285714
Name: fh_sku, dtype: float64
187    1.010267
188    1.084189
189    1.084189
190    0.948665
191    0.948665
192    0.924025
Name: mzc_sku, dtype: float64
187    1.192661
188    1.100917
189    0.972477
190    1.266055
191    0.403670
192    1.064220
Name: yp_sku, dtype: float64
187    1.077165
188    1.048819
189    1.058268
190    0.963780
191    0.992126
192    0.859843
Name: hs_sku, dtype: float64
187    0.409091
188    1.159091
189    0.954545
190    1.227273
191    1.090909
192    1.159091
Name: nyn_sku, dtype: float64
187    0.658537
188    0.914634
189    0.512195
190    1.646341
191    0.841463
192    1.426829
Name: atm_sku, dtype: float64
187    0.975
188    0.975
189    0.650
190    1.125
191    1.225
192    1.050
Name: msj_sku, dtype: float64
187    0.000000
188    0.000000
189    0.000000
190    2.153846
191    1.846154
192    2.000000
Name: fh_sku, dtype: float64
193    1.110390
194    1.022727
195    1.022727
196    0.983766
197    0.974026
198    0.886364
Name: mzc_sku, dtype: float64
193    1.237895
194    1.010526
195    1.149474
196    1.023158
197    0.960000
198    0.618947
Name: yp_sku, dtype: float64
193    1.139717
194    1.139717
195    1.271586
196    0.979592
197    1.017268
198    0.452119
Name: hs_sku, dtype: float64
193    1.034483
194    0.620690
195    0.620690
196    1.241379
197    1.241379
198    1.241379
Name: nyn_sku, dtype: float64
193    0.585799
194    0.639053
195    0.674556
196    1.349112
197    1.366864
198    1.384615
Name: atm_sku, dtype: float64
193    1.289902
194    0.879479
195    0.938111
196    0.899023
197    1.035831
198    0.957655
Name: msj_sku, dtype: float64
193    0.000000
194    0.000000
195    0.092308
196    0.000000
197    2.953846
198    2.953846
Name: fh_sku, dtype: float64
199    1.140575
200    1.130990
201    0.958466
202    0.958466
203    0.881789
204    0.929712
Name: mzc_sku, dtype: float64
199    1.041667
200    1.083333
201    0.972222
202    0.986111
203    0.972222
204    0.944444
Name: yp_sku, dtype: float64
199    0.832579
200    1.176471
201    1.058824
202    0.995475
203    0.959276
204    0.977376
Name: hs_sku, dtype: float64
199    0.84
200    1.08
201    1.02
202    1.02
203    1.02
204    1.02
Name: nyn_sku, dtype: float64
199    0.356757
200    0.681081
201    1.216216
202    1.329730
203    1.167568
204    1.248649
Name: atm_sku, dtype: float64
199    0.717791
200    0.938650
201    1.085890
202    1.049080
203    1.122699
204    1.085890
Name: msj_sku, dtype: float64
199    3.6
200    1.2
201    0.0
202    1.2
203    0.0
204    0.0
Name: fh_sku, dtype: float64
205    1.109718
206    1.081505
207    0.949843
208    0.996865
209    0.921630
210    0.940439
Name: mzc_sku, dtype: float64
205    1.129707
206    1.368201
207    0.941423
208    0.903766
209    0.790795
210    0.866109
Name: yp_sku, dtype: float64
205    1.084906
206    1.160377
207    1.000000
208    0.943396
209    0.905660
210    0.905660
Name: hs_sku, dtype: float64
205    0.500000
206    0.571429
207    1.214286
208    1.142857
209    1.285714
210    1.285714
Name: nyn_sku, dtype: float64
205    0.460064
206    0.785942
207    1.035144
208    1.418530
209    1.054313
210    1.246006
Name: atm_sku, dtype: float64
205    0.797203
206    0.671329
207    1.216783
208    0.986014
209    1.258741
210    1.069930
Name: msj_sku, dtype: float64
205    0.0
206    0.0
207    6.0
208    0.0
209    0.0
210    0.0
Name: fh_sku, dtype: float64
211    1.005917
212    1.035503
213    1.124260
214    0.946746
215    0.887574
Name: mzc_sku, dtype: float64
211    1.013514
212    1.064189
213    1.047297
214    0.945946
215    0.929054
Name: yp_sku, dtype: float64
211    0.769231
212    0.856643
213    1.346154
214    1.118881
215    0.909091
Name: hs_sku, dtype: float64
211    1.0
212    1.0
213    1.0
214    1.0
215    1.0
Name: nyn_sku, dtype: float64
211    1.000000
212    1.000000
213    1.055556
214    0.888889
215    1.055556
Name: atm_sku, dtype: float64
211    0.625000
212    0.937500
213    1.210938
214    1.210938
215    1.015625
Name: msj_sku, dtype: float64
211    0.0
212    0.0
213    0.0
214    2.5
215    2.5
Name: fh_sku, dtype: float64
216    1.085414
217    1.067017
218    1.177398
219    0.929041
220    0.910644
221    0.929041
222    0.901445
Name: mzc_sku, dtype: float64
216    1.389513
217    1.337079
218    1.179775
219    0.917603
220    0.734082
221    0.760300
222    0.681648
Name: yp_sku, dtype: float64
216    0.856051
217    1.194904
218    1.257325
219    0.971975
220    0.864968
221    0.980892
222    0.873885
Name: hs_sku, dtype: float64
216    0.752688
217    1.204301
218    0.000000
219    1.279570
220    1.053763
221    1.354839
222    1.354839
Name: nyn_sku, dtype: float64
216    0.589109
217    0.658416
218    0.710396
219    1.264851
220    1.247525
221    1.282178
222    1.247525
Name: atm_sku, dtype: float64
216    0.655518
217    0.772575
218    1.006689
219    1.123746
220    1.123746
221    1.170569
222    1.147157
Name: msj_sku, dtype: float64
216    0.0
217    0.0
218    0.0
219    7.0
220    0.0
221    0.0
222    0.0
Name: fh_sku, dtype: float64
223    1.121622
224    0.702703
225    1.202703
226    0.945946
227    1.027027
228    1.013514
229    0.986486
Name: mzc_sku, dtype: float64
223    1.143902
224    0.870732
225    1.041463
226    1.024390
227    1.024390
228    1.007317
229    0.887805
Name: yp_sku, dtype: float64
223    0.905751
224    0.916933
225    0.995208
226    0.950479
227    1.151757
228    1.118211
229    0.961661
Name: hs_sku, dtype: float64
223    0.840000
224    0.840000
225    0.840000
226    1.400000
227    1.026667
228    1.120000
229    0.933333
Name: nyn_sku, dtype: float64
223    0.825095
224    0.851711
225    0.718631
226    1.117871
227    1.197719
228    1.117871
229    1.171103
Name: atm_sku, dtype: float64
223    0.794953
224    0.772871
225    0.905363
226    1.037855
227    1.236593
228    1.126183
229    1.126183
Name: msj_sku, dtype: float64
223    0.000000
224    0.000000
225    0.000000
226    1.659794
227    1.226804
228    1.804124
229    2.309278
Name: fh_sku, dtype: float64
230    1.045872
231    1.073394
232    0.963303
233    0.963303
234    1.018349
235    0.935780
Name: mzc_sku, dtype: float64
230    1.089286
231    1.089286
232    0.964286
233    0.982143
234    0.910714
235    0.964286
Name: yp_sku, dtype: float64
230    1.009560
231    0.848948
232    1.089866
233    0.963671
234    1.101338
235    0.986616
Name: hs_sku, dtype: float64
230    1.038462
231    1.038462
232    0.923077
233    1.038462
234    0.923077
235    1.038462
Name: nyn_sku, dtype: float64
230    0.517241
231    0.586207
232    1.241379
233    1.172414
234    1.206897
235    1.275862
Name: atm_sku, dtype: float64
230    0.746888
231    0.796680
232    1.219917
233    1.170124
234    1.045643
235    1.020747
Name: msj_sku, dtype: float64
230   NaN
231   NaN
232   NaN
233   NaN
234   NaN
235   NaN
Name: fh_sku, dtype: float64
236    0.958631
237    1.004280
238    1.015692
239    1.095578
240    0.947218
241    0.935806
242    1.038516
243    1.004280
Name: mzc_sku, dtype: float64
236    0.867257
237    0.929204
238    0.929204
239    1.345133
240    0.938053
241    1.008850
242    0.982301
243    1.000000
Name: yp_sku, dtype: float64
236    0.944099
237    0.968944
238    0.968944
239    1.378882
240    0.981366
241    0.906832
242    0.944099
243    0.906832
Name: hs_sku, dtype: float64
236    0.800000
237    0.829630
238    0.829630
239    1.096296
240    0.888889
241    1.244444
242    1.125926
243    1.185185
Name: nyn_sku, dtype: float64
236    0.708861
237    0.708861
238    0.708861
239    0.911392
240    0.759494
241    1.518987
242    1.265823
243    1.417722
Name: atm_sku, dtype: float64
236    1.035813
237    0.947658
238    0.947658
239    1.388430
240    0.881543
241    0.903581
242    0.903581
243    0.991736
Name: msj_sku, dtype: float64
236    0.690096
237    0.690096
238    0.971246
239    1.303514
240    1.099042
241    1.099042
242    1.099042
243    1.047923
Name: fh_sku, dtype: float64
244    0.966543
245    0.762082
246    1.198885
247    1.031599
248    1.040892
Name: mzc_sku, dtype: float64
244    0.909091
245    1.191223
246    1.128527
247    0.877743
248    0.893417
Name: yp_sku, dtype: float64
244    0.986111
245    1.000000
246    1.208333
247    0.902778
248    0.902778
Name: hs_sku, dtype: float64
244    1.00
245    0.95
246    1.10
247    1.00
248    0.95
Name: nyn_sku, dtype: float64
244    1.019108
245    1.019108
246    0.955414
247    0.987261
248    1.019108
Name: atm_sku, dtype: float64
244    0.966667
245    1.066667
246    1.033333
247    0.900000
248    1.033333
Name: msj_sku, dtype: float64
244    0.881226
245    0.919540
246    1.321839
247    0.842912
248    1.034483
Name: fh_sku, dtype: float64
249    1.027119
250    1.057627
251    1.088136
252    0.986441
253    0.823729
254    1.016949
Name: mzc_sku, dtype: float64
249    0.932432
250    1.023649
251    1.023649
252    1.023649
253    0.972973
254    1.023649
Name: yp_sku, dtype: float64
249    0.889734
250    0.912548
251    1.517110
252    0.798479
253    0.946768
254    0.935361
Name: hs_sku, dtype: float64
249    1.112903
250    1.016129
251    1.838710
252    1.016129
253    0.580645
254    0.435484
Name: nyn_sku, dtype: float64
249    0.786408
250    0.815534
251    1.310680
252    0.873786
253    1.077670
254    1.135922
Name: atm_sku, dtype: float64
249    0.707224
250    0.935361
251    1.711027
252    0.798479
253    0.889734
254    0.958175
Name: msj_sku, dtype: float64
249    0.000
250    1.125
251    1.225
252    1.000
253    1.350
254    1.300
Name: fh_sku, dtype: float64
255    0.043478
256    1.956522
Name: mzc_sku, dtype: float64
255    2.0
256    0.0
Name: yp_sku, dtype: float64
255    0.916667
256    1.083333
Name: hs_sku, dtype: float64
255    2.0
256    0.0
Name: nyn_sku, dtype: float64
255    2.0
256    0.0
Name: atm_sku, dtype: float64
255    2.0
256    0.0
Name: msj_sku, dtype: float64
255    1.928571
256    0.071429
Name: fh_sku, dtype: float64
257    1.0
Name: mzc_sku, dtype: float64
257   NaN
Name: yp_sku, dtype: float64
257    1.0
Name: hs_sku, dtype: float64
257    1.0
Name: nyn_sku, dtype: float64
257    1.0
Name: atm_sku, dtype: float64
257    1.0
Name: msj_sku, dtype: float64
257    1.0
Name: fh_sku, dtype: float64
258    1.126531
259    1.151020
260    1.089796
261    1.114286
262    1.114286
263    0.795918
264    0.673469
265    1.187755
266    1.114286
267    0.942857
268    0.857143
269    0.832653
Name: mzc_sku, dtype: float64
258    0.933775
259    1.112583
260    1.013245
261    1.251656
262    1.092715
263    1.013245
264    1.052980
265    0.993377
266    0.953642
267    0.814570
268    0.794702
269    0.973510
Name: yp_sku, dtype: float64
258    0.858369
259    0.841202
260    0.841202
261    1.064378
262    0.892704
263    0.892704
264    0.824034
265    1.047210
266    0.909871
267    1.253219
268    1.304721
269    1.270386
Name: hs_sku, dtype: float64
258    1.100917
259    1.100917
260    1.431193
261    1.431193
262    1.321101
263    1.321101
264    1.321101
265    1.100917
266    1.211009
267    0.220183
268    0.220183
269    0.220183
Name: nyn_sku, dtype: float64
258    1.236364
259    1.272727
260    1.345455
261    1.381818
262    1.309091
263    1.236364
264    1.200000
265    1.236364
266    1.309091
267    0.181818
268    0.145455
269    0.145455
Name: atm_sku, dtype: float64
258    1.099796
259    1.148676
260    1.050916
261    1.197556
262    0.953157
263    1.295316
264    1.221996
265    1.270876
266    1.148676
267    1.344196
268    0.146640
269    0.122200
Name: msj_sku, dtype: float64
258    12.0
259     0.0
260     0.0
261     0.0
262     0.0
263     0.0
264     0.0
265     0.0
266     0.0
267     0.0
268     0.0
269     0.0
Name: fh_sku, dtype: float64
270    0.959938
271    0.959938
272    0.841294
273    1.035439
274    1.046225
275    1.035439
276    1.121726
Name: mzc_sku, dtype: float64
270    0.785714
271    0.714286
272    0.619048
273    1.261905
274    1.285714
275    1.047619
276    1.285714
Name: yp_sku, dtype: float64
270    1.070064
271    0.951168
272    1.129512
273    1.070064
274    0.906582
275    0.951168
276    0.921444
Name: hs_sku, dtype: float64
270    1.263889
271    0.777778
272    0.972222
273    0.972222
274    0.875000
275    0.875000
276    1.263889
Name: nyn_sku, dtype: float64
270    1.086207
271    0.844828
272    0.482759
273    1.267241
274    1.267241
275    1.146552
276    0.905172
Name: atm_sku, dtype: float64
270    0.909091
271    0.909091
272    0.772727
273    0.909091
274    1.181818
275    1.090909
276    1.227273
Name: msj_sku, dtype: float64
270   NaN
271   NaN
272   NaN
273   NaN
274   NaN
275   NaN
276   NaN
Name: fh_sku, dtype: float64
277    1.037791
278    1.017442
279    0.997093
280    1.017442
281    0.976744
282    0.956395
283    0.997093
Name: mzc_sku, dtype: float64
277    1.004484
278    0.957399
279    0.988789
280    0.988789
281    1.035874
282    1.020179
283    1.004484
Name: yp_sku, dtype: float64
277    0.000000
278    0.000000
279    1.434251
280    1.455657
281    1.391437
282    1.391437
283    1.327217
Name: hs_sku, dtype: float64
277    0.972222
278    0.972222
279    0.972222
280    1.020833
281    1.020833
282    1.020833
283    1.020833
Name: nyn_sku, dtype: float64
277    0.648876
278    0.707865
279    0.865169
280    1.317416
281    1.317416
282    1.081461
283    1.061798
Name: atm_sku, dtype: float64
277    0.979644
278    1.033079
279    0.961832
280    1.033079
281    1.015267
282    0.944020
283    1.033079
Name: msj_sku, dtype: float64
277    0.000000
278    0.000000
279    1.379808
280    1.413462
281    1.447115
282    1.362981
283    1.396635

Name: fh_sku, dtype: float64
284    0.973607
285    0.926686
286    1.020528
287    1.079179
Name: mzc_sku, dtype: float64
284    1.005848
285    1.029240
286    0.982456
287    0.982456
Name: yp_sku, dtype: float64
284    0.967742
285    1.032258
286    1.010753
287    0.989247
Name: hs_sku, dtype: float64
284    0.946237
285    1.032258
286    1.161290
287    0.860215
Name: nyn_sku, dtype: float64
284    0.827586
285    1.034483
286    0.758621
287    1.379310
Name: atm_sku, dtype: float64
284    1.021898
285    0.992701
286    1.167883
287    0.817518
Name: msj_sku, dtype: float64
284   NaN
285   NaN
286   NaN
287   NaN
Name: fh_sku, dtype: float64
288    0.971193
289    1.119342
290    0.930041
291    1.144033
292    1.127572
293    1.111111
294    0.880658
295    0.716049
Name: mzc_sku, dtype: float64
288    1.057728
289    0.968343
290    1.325885
291    1.206704
292    1.355680
293    1.236499
294    0.685289
295    0.163873
Name: yp_sku, dtype: float64
288    1.030812
289    1.075630
290    0.784314
291    1.210084
292    0.817927
293    1.098039
294    1.030812
295    0.952381
Name: hs_sku, dtype: float64
288    0.930233
289    0.930233
290    1.054264
291    0.496124
292    1.178295
293    1.178295
294    1.116279
295    1.116279
Name: nyn_sku, dtype: float64
288    0.970297
289    0.752475
290    1.069307
291    1.188119
292    1.188119
293    0.930693
294    1.108911
295    0.792079
Name: atm_sku, dtype: float64
288    0.731183
289    1.118280
290    0.989247
291    1.032258
292    1.204301
293    1.419355
294    0.580645
295    0.924731
Name: msj_sku, dtype: float64
288   NaN
289   NaN
290   NaN
291   NaN
292   NaN
293   NaN
294   NaN
295   NaN
Name: fh_sku, dtype: float64
296    0.987342
297    1.139241
298    0.740506
299    1.044304
300    1.158228
301    0.930380
Name: mzc_sku, dtype: float64
296   NaN
297   NaN
298   NaN
299   NaN
300   NaN
301   NaN
Name: yp_sku, dtype: float64
296    0.000000
297    1.714286
298    0.857143
299    3.428571
300    0.000000
301    0.000000
Name: hs_sku, dtype: float64
296   NaN
297   NaN
298   NaN
299   NaN
300   NaN
301   NaN
Name: nyn_sku, dtype: float64
296    0.0
297    0.0
298    6.0
299    0.0
300    0.0
301    0.0
Name: atm_sku, dtype: float64
296   NaN
297   NaN
298   NaN
299   NaN
300   NaN
301   NaN
Name: msj_sku, dtype: float64
296   NaN
297   NaN
298   NaN
299   NaN
300   NaN
301   NaN
Name: fh_sku, dtype: float64
302    0.880952
303    0.642857
304    0.880952
305    0.952381
306    1.642857
Name: mzc_sku, dtype: float64
302   NaN
303   NaN
304   NaN
305   NaN
306   NaN
Name: yp_sku, dtype: float64
302   NaN
303   NaN
304   NaN
305   NaN
306   NaN
Name: hs_sku, dtype: float64
302   NaN
303   NaN
304   NaN
305   NaN
306   NaN
Name: nyn_sku, dtype: float64
302   NaN
303   NaN
304   NaN
305   NaN
306   NaN
Name: atm_sku, dtype: float64
302   NaN
303   NaN
304   NaN
305   NaN
306   NaN
Name: msj_sku, dtype: float64
302   NaN
303   NaN
304   NaN
305   NaN
306   NaN
Name: fh_sku, dtype: float64
307    1.104369
308    0.764563
309    0.883495
310    0.713592
311    1.376214
312    1.189320
313    0.968447
Name: mzc_sku, dtype: float64
307    0.0
308    0.0
309    0.0
310    0.0
311    7.0
312    0.0
313    0.0
Name: yp_sku, dtype: float64
307    0.0
308    0.0
309    0.0
310    7.0
311    0.0
312    0.0
313    0.0
Name: hs_sku, dtype: float64
307   NaN
308   NaN
309   NaN
310   NaN
311   NaN
312   NaN
313   NaN
Name: nyn_sku, dtype: float64
307   NaN
308   NaN
309   NaN
310   NaN
311   NaN
312   NaN
313   NaN
Name: atm_sku, dtype: float64
307   NaN
308   NaN
309   NaN
310   NaN
311   NaN
312   NaN
313   NaN
Name: msj_sku, dtype: float64
307   NaN
308   NaN
309   NaN
310   NaN
311   NaN
312   NaN
313   NaN
Name: fh_sku, dtype: float64
314    1.0
Name: mzc_sku, dtype: float64
314   NaN
Name: yp_sku, dtype: float64
314   NaN
Name: hs_sku, dtype: float64
314   NaN
Name: nyn_sku, dtype: float64
314   NaN
Name: atm_sku, dtype: float64
314   NaN
Name: msj_sku, dtype: float64
314   NaN
Name: fh_sku, dtype: float64
315    1.020747
316    0.672199
317    0.995851
318    1.120332
319    1.095436
320    1.095436
Name: mzc_sku, dtype: float64
315    0.0
316    0.0
317    0.0
318    0.0
319    0.0
320    6.0
Name: yp_sku, dtype: float64
315    0.827586
316    0.000000
317    0.827586
318    0.827586
319    1.034483
320    2.482759
Name: hs_sku, dtype: float64
315   NaN
316   NaN
317   NaN
318   NaN
319   NaN
320   NaN
Name: nyn_sku, dtype: float64
315   NaN
316   NaN
317   NaN
318   NaN
319   NaN
320   NaN
Name: atm_sku, dtype: float64
315    0.0
316    6.0
317    0.0
318    0.0
319    0.0
320    0.0
Name: msj_sku, dtype: float64
315    0.0
316    6.0
317    0.0
318    0.0
319    0.0
320    0.0
Name: fh_sku, dtype: float64
321    0.896806
322    1.007371
323    1.130221
324    0.958231
325    1.007371
Name: mzc_sku, dtype: float64
321    0.277778
322    0.277778
323    1.944444
324    2.500000
325    0.000000
Name: yp_sku, dtype: float64
321    0.0
322    5.0
323    0.0
324    0.0
325    0.0
Name: hs_sku, dtype: float64
321   NaN
322   NaN
323   NaN
324   NaN
325   NaN
Name: nyn_sku, dtype: float64
321   NaN
322   NaN
323   NaN
324   NaN
325   NaN
Name: atm_sku, dtype: float64
321   NaN
322   NaN
323   NaN
324   NaN
325   NaN
Name: msj_sku, dtype: float64
321    0.0
322    0.0
323    0.0
324    5.0
325    0.0
Name: fh_sku, dtype: float64
326    1.122995
327    0.561497
328    1.203209
329    1.096257
330    1.016043
Name: mzc_sku, dtype: float64
326    0.142857
327    0.142857
328    0.000000
329    4.714286
330    0.000000
Name: yp_sku, dtype: float64
326    0.940594
327    1.485149
328    1.039604
329    0.891089
330    0.643564
Name: hs_sku, dtype: float64
326    0.0
327    0.0
328    5.0
329    0.0
330    0.0
Name: nyn_sku, dtype: float64
326    0.0
327    2.5
328    2.5
329    0.0
330    0.0
Name: atm_sku, dtype: float64
326    0.000000
327    0.000000
328    0.238095
329    4.761905
330    0.000000
Name: msj_sku, dtype: float64
326   NaN
327   NaN
328   NaN
329   NaN
330   NaN
Name: fh_sku, dtype: float64
331    1.169492
332    1.203390
333    1.220339
334    0.711864
335    0.694915
Name: mzc_sku, dtype: float64
331    0.0
332    0.0
333    0.0
334    5.0
335    0.0
Name: yp_sku, dtype: float64
331   NaN
332   NaN
333   NaN
334   NaN
335   NaN
Name: hs_sku, dtype: float64
331   NaN
332   NaN
333   NaN
334   NaN
335   NaN
Name: nyn_sku, dtype: float64
331   NaN
332   NaN
333   NaN
334   NaN
335   NaN
Name: atm_sku, dtype: float64
331    0.0
332    0.0
333    5.0
334    0.0
335    0.0
Name: msj_sku, dtype: float64
331   NaN
332   NaN
333   NaN
334   NaN
335   NaN
Name: fh_sku, dtype: float64
336    1.0
Name: mzc_sku, dtype: float64
336   NaN
Name: yp_sku, dtype: float64
336   NaN
Name: hs_sku, dtype: float64
336   NaN
Name: nyn_sku, dtype: float64
336   NaN
Name: atm_sku, dtype: float64
336   NaN
Name: msj_sku, dtype: float64
336   NaN
Name: fh_sku, dtype: float64
337    0.845103
338    0.845103
339    0.861048
340    0.892938
341    1.307517
342    1.100228
343    1.148064
Name: mzc_sku, dtype: float64
337   NaN
338   NaN
339   NaN
340   NaN
341   NaN
342   NaN
343   NaN
Name: yp_sku, dtype: float64
337    1.521739
338    3.043478
339    1.826087
340    0.608696
341    0.000000
342    0.000000
343    0.000000
Name: hs_sku, dtype: float64
337   NaN
338   NaN
339   NaN
340   NaN
341   NaN
342   NaN
343   NaN
Name: nyn_sku, dtype: float64
337   NaN
338   NaN
339   NaN
340   NaN
341   NaN
342   NaN
343   NaN
Name: atm_sku, dtype: float64
337   NaN
338   NaN
339   NaN
340   NaN
341   NaN
342   NaN
343   NaN
Name: msj_sku, dtype: float64
337   NaN
338   NaN
339   NaN
340   NaN
341   NaN
342   NaN
343   NaN
Name: fh_sku, dtype: float64
344    1.297297
345    0.729730
346    0.972973
Name: mzc_sku, dtype: float64
344   NaN
345   NaN
346   NaN
Name: yp_sku, dtype: float64
344   NaN
345   NaN
346   NaN
Name: hs_sku, dtype: float64
344   NaN
345   NaN
346   NaN
Name: nyn_sku, dtype: float64
344   NaN
345   NaN
346   NaN
Name: atm_sku, dtype: float64
344   NaN
345   NaN
346   NaN
Name: msj_sku, dtype: float64
344   NaN
345   NaN
346   NaN
Name: fh_sku, dtype: float64
347    0.896341
348    0.939024
349    1.052846
350    0.995935
351    0.867886
352    1.109756
353    1.138211
Name: mzc_sku, dtype: float64
347   NaN
348   NaN
349   NaN
350   NaN
351   NaN
352   NaN
353   NaN
Name: yp_sku, dtype: float64
347   NaN
348   NaN
349   NaN
350   NaN
351   NaN
352   NaN
353   NaN
Name: hs_sku, dtype: float64
347   NaN
348   NaN
349   NaN
350   NaN
351   NaN
352   NaN
353   NaN
Name: nyn_sku, dtype: float64
347   NaN
348   NaN
349   NaN
350   NaN
351   NaN
352   NaN
353   NaN
Name: atm_sku, dtype: float64
347   NaN
348   NaN
349   NaN
350   NaN
351   NaN
352   NaN
353   NaN
Name: msj_sku, dtype: float64
347   NaN
348   NaN
349   NaN
350   NaN
351   NaN
352   NaN
353   NaN
Name: fh_sku, dtype: float64
354    0.634058
355    1.413043
356    0.778986
357    1.485507
358    0.688406
Name: mzc_sku, dtype: float64
354   NaN
355   NaN
356   NaN
357   NaN
358   NaN
Name: yp_sku, dtype: float64
354   NaN
355   NaN
356   NaN
357   NaN
358   NaN
Name: hs_sku, dtype: float64
354   NaN
355   NaN
356   NaN
357   NaN
358   NaN
Name: nyn_sku, dtype: float64
354   NaN
355   NaN
356   NaN
357   NaN
358   NaN
Name: atm_sku, dtype: float64
354    2.857143
355    0.000000
356    0.000000
357    0.357143
358    1.785714
Name: msj_sku, dtype: float64
354   NaN
355   NaN
356   NaN
357   NaN
358   NaN
Name: fh_sku, dtype: float64
359    0.917476
360    1.036408
361    0.968447
362    1.019417
363    1.053398
364    1.070388
365    0.934466
Name: mzc_sku, dtype: float64
359    0.075269
360    0.827957
361    0.075269
362    3.537634
363    1.129032
364    0.752688
365    0.602151
Name: yp_sku, dtype: float64
359    2.434783
360    1.826087
361    0.152174
362    0.913043
363    1.065217
364    0.304348
365    0.304348
Name: hs_sku, dtype: float64
359   NaN
360   NaN
361   NaN
362   NaN
363   NaN
364   NaN
365   NaN
Name: nyn_sku, dtype: float64
359   NaN
360   NaN
361   NaN
362   NaN
363   NaN
364   NaN
365   NaN
Name: atm_sku, dtype: float64
359   NaN
360   NaN
361   NaN
362   NaN
363   NaN
364   NaN
365   NaN
Name: msj_sku, dtype: float64
359   NaN
360   NaN
361   NaN
362   NaN
363   NaN
364   NaN
365   NaN
Name: fh_sku, dtype: float64
366    1.001527
367    1.074809
368    1.087023
369    0.757252
370    1.111450
371    1.001527
372    0.977099
373    0.989313
Name: mzc_sku, dtype: float64
366   NaN
367   NaN
368   NaN
369   NaN
370   NaN
371   NaN
372   NaN
373   NaN
Name: yp_sku, dtype: float64
366    0.994595
367    0.972973
368    0.994595
369    1.059459
370    1.037838
371    0.994595
372    0.994595
373    0.951351
Name: hs_sku, dtype: float64
366    0.935673
367    0.842105
368    1.122807
369    1.029240
370    1.122807
371    0.982456
372    0.982456
373    0.982456
Name: nyn_sku, dtype: float64
366    0.929293
367    0.808081
368    1.171717
369    1.171717
370    1.171717
371    0.929293
372    0.888889
373    0.929293
Name: atm_sku, dtype: float64
366    4.095238
367    0.000000
368    0.000000
369    0.000000
370    0.000000
371    0.000000
372    0.000000
373    3.904762
Name: msj_sku, dtype: float64
366   NaN
367   NaN
368   NaN
369   NaN
370   NaN
371   NaN
372   NaN
373   NaN
Name: fh_sku, dtype: float64
374    0.967603
375    0.967603
376    0.984881
377    0.950324
378    0.950324
379    1.002160
380    1.071274
381    1.105832
Name: mzc_sku, dtype: float64
374    0.901961
375    1.078431
376    1.039216
377    1.039216
378    1.098039
379    0.823529
380    0.980392
381    1.039216
Name: yp_sku, dtype: float64
374    1.113752
375    1.073005
376    1.059423
377    0.882852
378    0.991511
379    0.964346
380    0.991511
381    0.923599
Name: hs_sku, dtype: float64
374    1.021277
375    0.510638
376    1.361702
377    1.021277
378    1.021277
379    1.021277
380    1.021277
381    1.021277
Name: nyn_sku, dtype: float64
374    1.030137
375    1.030137
376    0.920548
377    1.030137
378    1.008219
379    1.008219
380    1.008219
381    0.964384
Name: atm_sku, dtype: float64
374    1.221374
375    1.221374
376    1.160305
377    0.916031
378    0.977099
379    0.854962
380    0.793893
381    0.854962
Name: msj_sku, dtype: float64
374   NaN
375   NaN
376   NaN
377   NaN
378   NaN
379   NaN
380   NaN
381   NaN
Name: fh_sku, dtype: float64
382    0.509915
383    1.172805
384    0.968839
385    1.172805
386    1.223796
387    1.070822
388    0.917847
389    1.096317
390    0.866856
Name: mzc_sku, dtype: float64
382   NaN
383   NaN
384   NaN
385   NaN
386   NaN
387   NaN
388   NaN
389   NaN
390   NaN
Name: yp_sku, dtype: float64
382    1.663043
383    2.592391
384    1.271739
385    0.489130
386    0.978261
387    0.831522
388    0.195652
389    0.489130
390    0.489130
Name: hs_sku, dtype: float64
382   NaN
383   NaN
384   NaN
385   NaN
386   NaN
387   NaN
388   NaN
389   NaN
390   NaN
Name: nyn_sku, dtype: float64
382    0.0
383    0.0
384    0.0
385    0.0
386    0.0
387    4.5
388    0.0
389    0.0
390    4.5
Name: atm_sku, dtype: float64
382    0.0
383    9.0
384    0.0
385    0.0
386    0.0
387    0.0
388    0.0
389    0.0
390    0.0
Name: msj_sku, dtype: float64
382    3.0
383    0.0
384    0.0
385    0.0
386    0.0
387    1.5
388    1.5
389    1.5
390    1.5
Name: fh_sku, dtype: float64
391    0.814286
392    1.200000
393    0.914286
394    1.357143
395    1.385714
396    0.328571
Name: mzc_sku, dtype: float64
391    0.967742
392    2.129032
393    0.000000
394    0.967742
395    0.774194
396    1.161290
Name: yp_sku, dtype: float64
391    1.734940
392    1.373494
393    0.000000
394    1.373494
395    0.867470
396    0.650602
Name: hs_sku, dtype: float64
391   NaN
392   NaN
393   NaN
394   NaN
395   NaN
396   NaN
Name: nyn_sku, dtype: float64
391    0.0
392    0.0
393    0.0
394    0.0
395    0.0
396    6.0
Name: atm_sku, dtype: float64
391    0.9
392    1.2
393    0.0
394    1.3
395    1.2
396    1.4
Name: msj_sku, dtype: float64
391    1.153846
392    1.153846
393    1.846154
394    1.153846
395    0.692308
396    0.000000
Name: fh_sku, dtype: float64
397    0.705882
398    0.715170
399    1.030960
400    1.142415
401    0.863777
402    1.541796
Name: mzc_sku, dtype: float64
397    0.000000
398    2.181818
399    1.090909
400    0.000000
401    0.000000
402    2.727273
Name: yp_sku, dtype: float64
397    1.093220
398    1.067797
399    1.703390
400    0.610169
401    0.737288
402    0.788136
Name: hs_sku, dtype: float64
397   NaN
398   NaN
399   NaN
400   NaN
401   NaN
402   NaN
Name: nyn_sku, dtype: float64
397   NaN
398   NaN
399   NaN
400   NaN
401   NaN
402   NaN
Name: atm_sku, dtype: float64
397    0.0
398    3.0
399    0.0
400    0.0
401    3.0
402    0.0
Name: msj_sku, dtype: float64
397   NaN
398   NaN
399   NaN
400   NaN
401   NaN
402   NaN
Name: fh_sku, dtype: float64
403    1.008681
404    0.911458
405    0.996528
406    1.057292
407    1.008681
408    0.996528
409    1.020833
Name: mzc_sku, dtype: float64
403    0.025090
404    1.204301
405    1.229391
406    1.154122
407    1.078853
408    1.129032
409    1.179211
Name: yp_sku, dtype: float64
403    0.000000
404    1.266667
405    1.222222
406    1.177778
407    0.977778
408    1.200000
409    1.155556
Name: hs_sku, dtype: float64
403    1.070588
404    0.988235
405    1.152941
406    0.988235
407    0.823529
408    0.988235
409    0.988235
Name: nyn_sku, dtype: float64
403    0.956522
404    1.043478
405    0.913043
406    1.043478
407    1.086957
408    0.956522
409    1.000000
Name: atm_sku, dtype: float64
403    0.0
404    0.0
405    0.0
406    0.0
407    7.0
408    0.0
409    0.0
Name: msj_sku, dtype: float64
403   NaN
404   NaN
405   NaN
406   NaN
407   NaN
408   NaN
409   NaN

Name: fh_sku, dtype: float64
410    1.000000
411    0.972973
412    1.027027
Name: mzc_sku, dtype: float64
410   NaN
411   NaN
412   NaN
Name: yp_sku, dtype: float64
410   NaN
411   NaN
412   NaN
Name: hs_sku, dtype: float64
410   NaN
411   NaN
412   NaN
Name: nyn_sku, dtype: float64
410   NaN
411   NaN
412   NaN
Name: atm_sku, dtype: float64
410   NaN
411   NaN
412   NaN
Name: msj_sku, dtype: float64
410   NaN
411   NaN
412   NaN
Name: fh_sku, dtype: float64
413    1.046875
414    0.843750
415    1.187500
416    0.921875
Name: mzc_sku, dtype: float64
413   NaN
414   NaN
415   NaN
416   NaN
Name: yp_sku, dtype: float64
413    0.000000
414    0.111111
415    3.888889
416    0.000000
Name: hs_sku, dtype: float64
413   NaN
414   NaN
415   NaN
416   NaN
Name: nyn_sku, dtype: float64
413   NaN
414   NaN
415   NaN
416   NaN
Name: atm_sku, dtype: float64
413   NaN
414   NaN
415   NaN
416   NaN
Name: msj_sku, dtype: float64
413   NaN
414   NaN
415   NaN
416   NaN
Name: fh_sku, dtype: float64
417    0.051471
418    0.051471
419    1.492647
420    1.338235
421    1.389706
422    1.286765
423    1.389706
Name: mzc_sku, dtype: float64
417    0.875
418    2.625
419    0.000
420    0.000
421    0.000
422    0.000
423    3.500
Name: yp_sku, dtype: float64
417    0.000000
418    0.451613
419    0.000000
420    1.129032
421    0.225806
422    0.677419
423    4.516129
Name: hs_sku, dtype: float64
417    0.000000
418    2.333333
419    0.000000
420    0.000000
421    0.000000
422    0.000000
423    4.666667
Name: nyn_sku, dtype: float64
417    0.00
418    1.75
419    0.00
420    0.00
421    0.00
422    0.00
423    5.25
Name: atm_sku, dtype: float64
417    0.000000
418    0.538462
419    0.000000
420    0.000000
421    0.000000
422    0.000000
423    6.461538
Name: msj_sku, dtype: float64
417    2.0
418    3.0
419    0.0
420    0.0
421    0.0
422    0.0
423    2.0
Name: fh_sku, dtype: float64
424    0.12
425    1.50
426    1.38
Name: mzc_sku, dtype: float64
424    3.0
425    0.0
426    0.0
Name: yp_sku, dtype: float64
424    0.0
425    3.0
426    0.0
Name: hs_sku, dtype: float64
424   NaN
425   NaN
426   NaN
Name: nyn_sku, dtype: float64
424    3.0
425    0.0
426    0.0
Name: atm_sku, dtype: float64
424    3.0
425    0.0
426    0.0
Name: msj_sku, dtype: float64
424    3.0
425    0.0
426    0.0
Name: fh_sku, dtype: float64
427    1.085561
428    1.497326
429    0.973262
430    1.197861
431    1.085561
432    0.411765
433    0.748663
Name: mzc_sku, dtype: float64
427   NaN
428   NaN
429   NaN
430   NaN
431   NaN
432   NaN
433   NaN
Name: yp_sku, dtype: float64
427   NaN
428   NaN
429   NaN
430   NaN
431   NaN
432   NaN
433   NaN
Name: hs_sku, dtype: float64
427   NaN
428   NaN
429   NaN
430   NaN
431   NaN
432   NaN
433   NaN
Name: nyn_sku, dtype: float64
427   NaN
428   NaN
429   NaN
430   NaN
431   NaN
432   NaN
433   NaN
Name: atm_sku, dtype: float64
427   NaN
428   NaN
429   NaN
430   NaN
431   NaN
432   NaN
433   NaN
Name: msj_sku, dtype: float64
427    0.0
428    7.0
429    0.0
430    0.0
431    0.0
432    0.0
433    0.0
Name: fh_sku, dtype: float64
434    1.008130
435    1.495935
436    0.032520
437    0.878049
438    1.365854
439    1.398374
440    1.365854
441    0.455285
Name: mzc_sku, dtype: float64
434    2.72
435    0.00
436    4.64
437    0.00
438    0.00
439    0.00
440    0.00
441    0.64
Name: yp_sku, dtype: float64
434    0.00
435    0.00
436    7.04
437    0.00
438    0.00
439    0.32
440    0.00
441    0.64
Name: hs_sku, dtype: float64
434    1.523810
435    1.142857
436    0.380952
437    1.142857
438    1.142857
439    0.761905
440    1.142857
441    0.761905
Name: nyn_sku, dtype: float64
434    2.666667
435    0.000000
436    0.000000
437    0.000000
438    0.000000
439    0.000000
440    2.666667
441    2.666667
Name: atm_sku, dtype: float64
434    4.000000
435    0.000000
436    0.000000
437    0.000000
438    1.333333
439    0.000000
440    0.000000
441    2.666667
Name: msj_sku, dtype: float64
434    6.0
435    0.0
436    0.0
437    0.0
438    0.0
439    0.0
440    0.0
441    2.0
Name: fh_sku, dtype: float64
442    1.145833
443    1.041667
444    1.041667
445    1.067708
446    0.703125
Name: mzc_sku, dtype: float64
442    0.8750
443    0.8750
444    1.0625
445    1.1875
446    1.0000
Name: yp_sku, dtype: float64
442    0.0
443    0.0
444    0.0
445    0.0
446    5.0
Name: hs_sku, dtype: float64
442   NaN
443   NaN
444   NaN
445   NaN
446   NaN
Name: nyn_sku, dtype: float64
442   NaN
443   NaN
444   NaN
445   NaN
446   NaN
Name: atm_sku, dtype: float64
442   NaN
443   NaN
444   NaN
445   NaN
446   NaN
Name: msj_sku, dtype: float64
442   NaN
443   NaN
444   NaN
445   NaN
446   NaN
Name: fh_sku, dtype: float64
447    0.945565
448    0.776210
449    0.987903
450    1.058468
451    1.086694
452    1.030242
453    1.114919
Name: mzc_sku, dtype: float64
447    0.0
448    7.0
449    0.0
450    0.0
451    0.0
452    0.0
453    0.0
Name: yp_sku, dtype: float64
447    0.0
448    7.0
449    0.0
450    0.0
451    0.0
452    0.0
453    0.0
Name: hs_sku, dtype: float64
447    0.0
448    7.0
449    0.0
450    0.0
451    0.0
452    0.0
453    0.0
Name: nyn_sku, dtype: float64
447    0.411765
448    1.441176
449    0.823529
450    0.823529
451    1.029412
452    1.235294
453    1.235294
Name: atm_sku, dtype: float64
447   NaN
448   NaN
449   NaN
450   NaN
451   NaN
452   NaN
453   NaN
Name: msj_sku, dtype: float64
447    0.000000
448    0.000000
449    0.000000
450    2.333333
451    2.333333
452    0.000000
453    2.333333
Name: fh_sku, dtype: float64
454    1.052632
455    1.082707
456    0.992481
457    0.872180
Name: mzc_sku, dtype: float64
454    1.043478
455    1.321739
456    0.973913
457    0.660870
Name: yp_sku, dtype: float64
454    0.888889
455    1.206349
456    1.015873
457    0.888889
Name: hs_sku, dtype: float64
454    1.12
455    0.80
456    0.96
457    1.12
Name: nyn_sku, dtype: float64
454    1.230769
455    1.230769
456    0.923077
457    0.615385
Name: atm_sku, dtype: float64
454    0.774194
455    1.032258
456    1.290323
457    0.903226
Name: msj_sku, dtype: float64
454   NaN
455   NaN
456   NaN
457   NaN
Name: fh_sku, dtype: float64
458    0.736196
459    1.079755
460    1.055215
461    1.128834
Name: mzc_sku, dtype: float64
458   NaN
459   NaN
460   NaN
461   NaN
Name: yp_sku, dtype: float64
458   NaN
459   NaN
460   NaN
461   NaN
Name: hs_sku, dtype: float64
458   NaN
459   NaN
460   NaN
461   NaN
Name: nyn_sku, dtype: float64
458   NaN
459   NaN
460   NaN
461   NaN
Name: atm_sku, dtype: float64
458   NaN
459   NaN
460   NaN
461   NaN
Name: msj_sku, dtype: float64
458   NaN
459   NaN
460   NaN
461   NaN
Name: fh_sku, dtype: float64
462    2.090909
463    0.545455
464    0.727273
465    0.545455
466    1.090909
Name: mzc_sku, dtype: float64
462    0.0
463    0.0
464    0.0
465    0.0
466    5.0
Name: yp_sku, dtype: float64
462   NaN
463   NaN
464   NaN
465   NaN
466   NaN
Name: hs_sku, dtype: float64
462    0.0
463    5.0
464    0.0
465    0.0
466    0.0
Name: nyn_sku, dtype: float64
462   NaN
463   NaN
464   NaN
465   NaN
466   NaN
Name: atm_sku, dtype: float64
462   NaN
463   NaN
464   NaN
465   NaN
466   NaN
Name: msj_sku, dtype: float64
462   NaN
463   NaN
464   NaN
465   NaN
466   NaN
Name: fh_sku, dtype: float64
467    1.344262
468    1.081967
469    0.557377
470    0.786885
471    1.196721
472    1.032787
Name: mzc_sku, dtype: float64
467   NaN
468   NaN
469   NaN
470   NaN
471   NaN
472   NaN
Name: yp_sku, dtype: float64
467    0.0
468    0.0
469    0.0
470    6.0
471    0.0
472    0.0
Name: hs_sku, dtype: float64
467   NaN
468   NaN
469   NaN
470   NaN
471   NaN
472   NaN
Name: nyn_sku, dtype: float64
467   NaN
468   NaN
469   NaN
470   NaN
471   NaN
472   NaN
Name: atm_sku, dtype: float64
467    0.0
468    0.0
469    0.0
470    6.0
471    0.0
472    0.0
Name: msj_sku, dtype: float64
467   NaN
468   NaN
469   NaN
470   NaN
471   NaN
472   NaN
Name: fh_sku, dtype: float64
473    0.923077
474    1.076923
Name: mzc_sku, dtype: float64
473   NaN
474   NaN
Name: yp_sku, dtype: float64
473    0.666667
474    1.333333
Name: hs_sku, dtype: float64
473   NaN
474   NaN
Name: nyn_sku, dtype: float64
473   NaN
474   NaN
Name: atm_sku, dtype: float64
473   NaN
474   NaN
Name: msj_sku, dtype: float64
473   NaN
474   NaN
Name: fh_sku, dtype: float64
475    1.116201
476    1.075978
477    0.975419
478    0.854749
479    0.874860
480    1.065922
481    1.086034
482    0.935196
483    1.015642
Name: mzc_sku, dtype: float64
475    0.984
476    0.984
477    1.068
478    0.948
479    1.044
480    1.008
481    0.864
482    1.032
483    1.068
Name: yp_sku, dtype: float64
475    0.983668
476    1.051508
477    1.108040
478    0.814070
479    0.983668
480    1.051508
481    1.006281
482    0.994975
483    1.006281
Name: hs_sku, dtype: float64
475    1.157143
476    1.157143
477    1.028571
478    1.028571
479    0.514286
480    1.028571
481    1.028571
482    1.028571
483    1.028571
Name: nyn_sku, dtype: float64
475    1.000000
476    0.916667
477    1.083333
478    1.000000
479    1.166667
480    0.916667
481    0.916667
482    0.916667
483    1.083333
Name: atm_sku, dtype: float64
475    0.949451
476    0.989011
477    1.087912
478    1.028571
479    0.850549
480    1.048352
481    1.068132
482    0.949451
483    1.028571
Name: msj_sku, dtype: float64
475    0.0
476    0.0
477    0.0
478    0.0
479    0.0
480    0.0
481    0.0
482    9.0
483    0.0
Name: fh_sku, dtype: float64
484    0.952532
485    0.974684
486    1.007911
487    1.007911
488    1.007911
489    1.063291
490    0.985759
Name: mzc_sku, dtype: float64
484    1.015432
485    1.037037
486    0.972222
487    0.864198
488    1.058642
489    1.015432
490    1.037037
Name: yp_sku, dtype: float64
484    0.965517
485    1.009404
486    1.031348
487    0.965517
488    1.009404
489    1.009404
490    1.009404
Name: hs_sku, dtype: float64
484    0.954545
485    0.954545
486    0.890909
487    1.336364
488    1.018182
489    0.954545
490    0.890909
Name: nyn_sku, dtype: float64
484    1.239583
485    1.093750
486    1.020833
487    0.364583
488    1.166667
489    1.020833
490    1.093750
Name: atm_sku, dtype: float64
484    1.065217
485    0.978261
486    1.086957
487    0.934783
488    0.826087
489    1.065217
490    1.043478
Name: msj_sku, dtype: float64
484    0.0
485    0.0
486    0.0
487    7.0
488    0.0
489    0.0
490    0.0
Name: fh_sku, dtype: float64
491    1.121134
492    1.538660
493    0.873711
494    1.182990
495    1.268041
496    0.711340
497    0.788660
498    0.804124
499    0.711340
Name: mzc_sku, dtype: float64
491    0.998319
492    1.028571
493    0.998319
494    1.089076
495    1.225210
496    0.544538
497    1.043697
498    1.043697
499    1.028571
Name: yp_sku, dtype: float64
491    0.984152
492    1.069731
493    0.927100
494    1.041204
495    0.812995
496    1.026941
497    0.741680
498    1.183835
499    1.212361
Name: hs_sku, dtype: float64
491    1.304348
492    1.369565
493    1.108696
494    1.304348
495    1.369565
496    1.043478
497    0.065217
498    1.434783
499    0.000000
Name: nyn_sku, dtype: float64
491    1.061662
492    1.109920
493    1.013405
494    1.182306
495    0.699732
496    1.037534
497    1.013405
498    1.037534
499    0.844504
Name: atm_sku, dtype: float64
491    1.153361
492    0.869748
493    1.039916
494    1.115546
495    1.096639
496    1.191176
497    0.888655
498    0.794118
499    0.850840
Name: msj_sku, dtype: float64
491   NaN
492   NaN
493   NaN
494   NaN
495   NaN
496   NaN
497   NaN
498   NaN
499   NaN
Name: fh_sku, dtype: float64
500    1.034161
501    0.908385
502    1.006211
503    1.076087
504    1.090062
505    0.908385
506    0.894410
507    1.104037
508    0.978261
Name: mzc_sku, dtype: float64
500    0.843750
501    1.012500
502    0.984375
503    1.012500
504    0.759375
505    0.928125
506    1.096875
507    1.181250
508    1.181250
Name: yp_sku, dtype: float64
500    0.71875
501    0.96875
502    1.15625
503    0.84375
504    0.71875
505    1.12500
506    1.21875
507    1.21875
508    1.03125
Name: hs_sku, dtype: float64
500    0.860870
501    1.173913
502    1.017391
503    0.782609
504    0.782609
505    0.860870
506    1.252174
507    1.095652
508    1.173913
Name: nyn_sku, dtype: float64
500    0.771429
501    0.900000
502    1.157143
503    1.028571
504    1.028571
505    1.028571
506    1.028571
507    0.964286
508    1.092857
Name: atm_sku, dtype: float64
500    1.041131
501    1.203085
502    1.064267
503    0.948586
504    0.971722
505    0.670951
506    1.064267
507    0.948586
508    1.087404
Name: msj_sku, dtype: float64
500    1.061662
501    1.230563
502    0.965147
503    0.868633
504    0.941019
505    0.868633
506    1.037534
507    1.037534
508    0.989276
Name: fh_sku, dtype: float64
509    1.028571
510    1.042857
511    0.942857
512    1.157143
513    0.942857
514    0.885714
Name: mzc_sku, dtype: float64
509    1.467391
510    1.239130
511    1.336957
512    0.847826
513    0.652174
514    0.456522
Name: yp_sku, dtype: float64
509    1.327511
510    1.213974
511    1.196507
512    0.851528
513    0.877729
514    0.532751
Name: hs_sku, dtype: float64
509    1.677419
510    1.935484
511    0.580645
512    0.322581
513    0.258065
514    1.225806
Name: nyn_sku, dtype: float64
509    3.041667
510    1.583333
511    0.166667
512    0.291667
513    0.333333
514    0.583333
Name: atm_sku, dtype: float64
509    0.661597
510    0.889734
511    1.619772
512    1.551331
513    1.049430
514    0.228137
Name: msj_sku, dtype: float64
509   NaN
510   NaN
511   NaN
512   NaN
513   NaN
514   NaN
Name: fh_sku, dtype: float64
515    1.000000
516    1.166667
517    0.833333
Name: mzc_sku, dtype: float64
515   NaN
516   NaN
517   NaN
Name: yp_sku, dtype: float64
515   NaN
516   NaN
517   NaN
Name: hs_sku, dtype: float64
515    0.0
516    3.0
517    0.0
Name: nyn_sku, dtype: float64
515   NaN
516   NaN
517   NaN
Name: atm_sku, dtype: float64
515    0.75
516    1.50
517    0.75
Name: msj_sku, dtype: float64
515    0.0
516    3.0
517    0.0
Name: fh_sku, dtype: float64
518    1.265823
519    0.253165
520    1.234177
521    1.139241
522    1.107595
Name: mzc_sku, dtype: float64
518    5.0
519    0.0
520    0.0
521    0.0
522    0.0
Name: yp_sku, dtype: float64
518    3.888889
519    0.000000
520    0.000000
521    0.000000
522    1.111111
Name: hs_sku, dtype: float64
518   NaN
519   NaN
520   NaN
521   NaN
522   NaN
Name: nyn_sku, dtype: float64
518   NaN
519   NaN
520   NaN
521   NaN
522   NaN
Name: atm_sku, dtype: float64
518   NaN
519   NaN
520   NaN
521   NaN
522   NaN
Name: msj_sku, dtype: float64
518   NaN
519   NaN
520   NaN
521   NaN
522   NaN
Name: fh_sku, dtype: float64
523    0.952381
524    0.857143
525    0.761905
526    1.238095
527    1.142857
528    1.095238
529    0.952381
530    1.000000
531    1.000000
Name: mzc_sku, dtype: float64
523    1.0
524    0.0
525    0.0
526    0.0
527    0.0
528    0.0
529    0.0
530    0.0
531    8.0
Name: yp_sku, dtype: float64
523    2.314286
524    2.314286
525    0.642857
526    0.642857
527    0.128571
528    0.128571
529    0.128571
530    0.128571
531    2.571429
Name: hs_sku, dtype: float64
523    1.8
524    0.0
525    0.0
526    0.0
527    0.0
528    0.0
529    0.0
530    0.0
531    7.2
Name: nyn_sku, dtype: float64
523    1.5
524    0.0
525    0.0
526    0.0
527    0.0
528    0.0
529    0.0
530    0.0
531    7.5
Name: atm_sku, dtype: float64
523    0.0
524    0.0
525    0.0
526    1.0
527    0.0
528    0.0
529    0.0
530    0.0
531    8.0
Name: msj_sku, dtype: float64
523    1.145455
524    0.000000
525    0.000000
526    0.000000
527    0.000000
528    0.000000
529    0.000000
530    0.000000
531    7.854545
Name: fh_sku, dtype: float64
532    0.429967
533    0.456026
534    0.521173
535    0.534202
536    1.680782
537    2.058632
538    1.250814
539    1.068404
Name: mzc_sku, dtype: float64
532    0.884706
533    0.903529
534    0.903529
535    0.771765
536    1.167059
537    1.110588
538    1.129412
539    1.129412
Name: yp_sku, dtype: float64
532    1.058005
533    1.058005
534    0.909513
535    0.928074
536    1.002320
537    1.020882
538    1.020882
539    1.002320
Name: hs_sku, dtype: float64
532   NaN
533   NaN
534   NaN
535   NaN
536   NaN
537   NaN
538   NaN
539   NaN
Name: nyn_sku, dtype: float64
532    0.0
533    0.0
534    0.0
535    8.0
536    0.0
537    0.0
538    0.0
539    0.0
Name: atm_sku, dtype: float64
532    0.0
533    0.0
534    8.0
535    0.0
536    0.0
537    0.0
538    0.0
539    0.0
Name: msj_sku, dtype: float64
532    0.0
533    0.0
534    0.0
535    0.0
536    0.0
537    0.0
538    8.0
539    0.0
Name: fh_sku, dtype: float64
540    0.919067
541    1.152263
542    1.152263
543    0.548697
544    1.111111
545    0.795610
546    1.234568
547    1.069959
548    1.069959
549    0.946502
Name: mzc_sku, dtype: float64
540    0.000000
541    1.176471
542    1.176471
543    4.607843
544    1.176471
545    0.000000
546    0.490196
547    0.784314
548    0.196078
549    0.392157
Name: yp_sku, dtype: float64
540    0.934744
541    1.216931
542    1.075838
543    0.864198
544    0.952381
545    0.917108
546    1.022928
547    1.022928
548    1.058201
549    0.934744

Name: hs_sku, dtype: float64
540   NaN
541   NaN
542   NaN
543   NaN
544   NaN
545   NaN
546   NaN
547   NaN
548   NaN
549   NaN
Name: nyn_sku, dtype: float64
540     0.0
541     0.0
542     0.0
543     0.0
544    10.0
545     0.0
546     0.0
547     0.0
548     0.0
549     0.0
Name: atm_sku, dtype: float64
540    0.625000
541    0.888158
542    1.381579
543    0.000000
544    1.315789
545    1.282895
546    0.986842
547    1.250000
548    1.151316
549    1.118421
Name: msj_sku, dtype: float64
540    2.285714
541    1.238095
542    0.952381
543    0.000000
544    1.714286
545    1.428571
546    1.142857
547    0.000000
548    1.238095
549    0.000000
Name: fh_sku, dtype: float64
550    0.990964
551    0.927711
552    0.969880
553    1.033133
554    0.990964
555    1.096386
556    0.990964
Name: mzc_sku, dtype: float64
550    0.968085
551    1.241135
552    1.117021
553    0.968085
554    0.943262
555    0.769504
556    0.992908
Name: yp_sku, dtype: float64
550    1.137809
551    1.063604
552    0.939929
553    0.989399
554    0.989399
555    0.840989
556    1.038869
Name: hs_sku, dtype: float64
550   NaN
551   NaN
552   NaN
553   NaN
554   NaN
555   NaN
556   NaN
Name: nyn_sku, dtype: float64
550    0.0
551    0.0
552    0.0
553    7.0
554    0.0
555    0.0
556    0.0
Name: atm_sku, dtype: float64
550   NaN
551   NaN
552   NaN
553   NaN
554   NaN
555   NaN
556   NaN
Name: msj_sku, dtype: float64
550   NaN
551   NaN
552   NaN
553   NaN
554   NaN
555   NaN
556   NaN
Name: fh_sku, dtype: float64
557    0.979592
558    1.020408
Name: mzc_sku, dtype: float64
557   NaN
558   NaN
Name: yp_sku, dtype: float64
557    1.257143
558    0.742857
Name: hs_sku, dtype: float64
557   NaN
558   NaN
Name: nyn_sku, dtype: float64
557   NaN
558   NaN
Name: atm_sku, dtype: float64
557    0.8
558    1.2
Name: msj_sku, dtype: float64
557   NaN
558   NaN
Name: fh_sku, dtype: float64
559    1.043478
560    0.991304
561    1.147826
562    1.030435
563    1.004348
564    0.939130
565    0.873913
566    1.004348
567    0.965217
Name: mzc_sku, dtype: float64
559    1.195489
560    0.947368
561    1.172932
562    0.654135
563    0.969925
564    1.093985
565    0.981203
566    1.048872
567    0.936090
Name: yp_sku, dtype: float64
559    1.162630
560    1.173010
561    0.861592
562    0.747405
563    1.141869
564    0.923875
565    0.965398
566    0.892734
567    1.131488
Name: hs_sku, dtype: float64
559    0.000000
560    0.958580
561    1.384615
562    1.224852
563    0.585799
564    1.437870
565    1.863905
566    0.000000
567    1.544379
Name: nyn_sku, dtype: float64
559    0.000000
560    1.111969
561    1.285714
562    1.285714
563    1.077220
564    1.459459
565    1.424710
566    0.000000
567    1.355212
Name: atm_sku, dtype: float64
559    1.074074
560    0.907407
561    1.259259
562    0.629630
563    0.851852
564    1.018519
565    0.888889
566    1.407407
567    0.962963
Name: msj_sku, dtype: float64
559    0.256329
560    1.025316
561    1.139241
562    0.996835
563    1.424051
564    1.395570
565    1.082278
566    0.341772
567    1.338608
Name: fh_sku, dtype: float64
568    0.900000
569    0.933333
570    0.900000
571    1.033333
572    1.166667
573    1.000000
574    1.066667
Name: mzc_sku, dtype: float64
568    1.076923
569    1.388664
570    1.076923
571    1.133603
572    0.708502
573    0.793522
574    0.821862
Name: yp_sku, dtype: float64
568    0.973510
569    0.973510
570    1.004415
571    1.019868
572    1.097130
573    0.896247
574    1.035320
Name: hs_sku, dtype: float64
568    1.673913
569    1.217391
570    0.760870
571    0.760870
572    0.760870
573    0.913043
574    0.913043
Name: nyn_sku, dtype: float64
568    0.732558
569    0.976744
570    0.976744
571    1.058140
572    1.058140
573    1.139535
574    1.058140
Name: atm_sku, dtype: float64
568    1.001908
569    0.975191
570    1.015267
571    0.881679
572    1.095420
573    0.975191
574    1.055344
Name: msj_sku, dtype: float64
568    0.982456
569    1.166667
570    0.859649
571    0.982456
572    0.982456
573    1.228070
574    0.798246
Name: fh_sku, dtype: float64
575    0.801187
576    0.854599
577    0.783383
578    0.836795
579    1.388724
580    1.335312
Name: mzc_sku, dtype: float64
575    1.031579
576    1.010526
577    1.094737
578    0.968421
579    0.968421
580    0.926316
Name: yp_sku, dtype: float64
575    1.006270
576    0.978056
577    1.015674
578    0.968652
579    1.156740
580    0.874608
Name: hs_sku, dtype: float64
575    0.916031
576    1.007634
577    0.916031
578    0.778626
579    1.465649
580    0.916031
Name: nyn_sku, dtype: float64
575    0.993377
576    0.913907
577    0.993377
578    0.993377
579    1.112583
580    0.993377
Name: atm_sku, dtype: float64
575    0.792453
576    0.792453
577    0.943396
578    0.943396
579    1.622642
580    0.905660
Name: msj_sku, dtype: float64
575    0.955017
576    0.934256
577    1.245675
578    0.975779
579    0.934256
580    0.955017
Name: fh_sku, dtype: float64
581    1.067873
582    1.058824
583    1.076923
584    0.959276
585    0.914027
586    0.923077
Name: mzc_sku, dtype: float64
581    0.977035
582    1.340292
583    1.139875
584    0.889353
585    0.864301
586    0.789144
Name: yp_sku, dtype: float64
581    0.881306
582    1.219585
583    1.139466
584    0.943620
585    0.872404
586    0.943620
Name: hs_sku, dtype: float64
581    1.000000
582    1.058824
583    1.000000
584    0.941176
585    1.000000
586    1.000000
Name: nyn_sku, dtype: float64
581    0.464396
582    0.724458
583    0.817337
584    1.300310
585    1.281734
586    1.411765
Name: atm_sku, dtype: float64
581    1.061728
582    1.061728
583    1.086420
584    1.234568
585    0.000000
586    1.555556
Name: msj_sku, dtype: float64
581    0.0
582    0.0
583    0.0
584    0.0
585    0.0
586    6.0
Name: fh_sku, dtype: float64
587    1.056604
588    1.056604
589    1.056604
590    1.056604
591    1.056604
592    0.792453
593    0.924528
Name: mzc_sku, dtype: float64
587    0.8750
588    0.8750
589    0.8750
590    0.8750
591    1.3125
592    1.3125
593    0.8750
Name: yp_sku, dtype: float64
587    1.037037
588    1.037037
589    1.037037
590    0.777778
591    1.037037
592    1.037037
593    1.037037
Name: hs_sku, dtype: float64
587    1.037037
588    1.037037
589    1.037037
590    1.037037
591    0.777778
592    1.037037
593    1.037037
Name: nyn_sku, dtype: float64
587    1.037037
588    1.037037
589    1.037037
590    1.037037
591    0.777778
592    1.037037
593    1.037037
Name: atm_sku, dtype: float64
587    1.0
588    1.0
589    1.0
590    1.0
591    1.0
592    1.0
593    1.0
Name: msj_sku, dtype: float64
587   NaN
588   NaN
589   NaN
590   NaN
591   NaN
592   NaN
593   NaN
Name: fh_sku, dtype: float64
594    1.395349
595    1.209302
596    0.651163
597    0.744186
Name: mzc_sku, dtype: float64
594    0.235294
595    1.905882
596    0.658824
597    1.200000
Name: yp_sku, dtype: float64
594    1.110266
595    1.368821
596    0.714829
597    0.806084
Name: hs_sku, dtype: float64
594    0.909091
595    1.272727
596    0.727273
597    1.090909
Name: nyn_sku, dtype: float64
594    1.090909
595    1.333333
596    0.606061
597    0.969697
Name: atm_sku, dtype: float64
594    0.774194
595    1.096774
596    0.967742
597    1.161290
Name: msj_sku, dtype: float64
594    2.0
595    0.0
596    2.0
597    0.0
Name: fh_sku, dtype: float64
598    1.179487
599    1.230769
600    1.269231
601    0.756410
602    0.705128
603    0.833333
604    1.025641
Name: mzc_sku, dtype: float64
598    1.342926
599    1.175060
600    1.057554
601    0.805755
602    0.990408
603    0.839329
604    0.788969
Name: yp_sku, dtype: float64
598    1.303448
599    1.110345
600    0.885057
601    0.965517
602    0.933333
603    0.949425
604    0.852874
Name: hs_sku, dtype: float64
598    0.836957
599    1.065217
600    0.608696
601    0.760870
602    0.836957
603    1.445652
604    1.445652
Name: nyn_sku, dtype: float64
598    1.033333
599    0.800000
600    0.600000
601    0.733333
602    1.066667
603    1.566667
604    1.200000
Name: atm_sku, dtype: float64
598    1.447592
599    1.070822
600    0.753541
601    0.832861
602    1.110482
603    0.951841
604    0.832861
Name: msj_sku, dtype: float64
598    7.0
599    0.0
600    0.0
601    0.0
602    0.0
603    0.0
604    0.0
Name: fh_sku, dtype: float64
605    0.993311
606    1.053512
607    0.933110
608    0.963211
609    0.963211
610    0.963211
611    0.933110
612    0.963211
613    1.234114
Name: mzc_sku, dtype: float64
605    1.033784
606    1.885135
607    0.912162
608    0.608108
609    0.790541
610    0.668919
611    0.729730
612    1.885135
613    0.486486
Name: yp_sku, dtype: float64
605    1.070270
606    0.778378
607    1.094595
608    0.681081
609    1.094595
610    1.264865
611    0.729730
612    0.948649
613    1.337838
Name: hs_sku, dtype: float64
605    1.956522
606    2.347826
607    1.043478
608    1.434783
609    1.173913
610    1.043478
611    0.000000
612    0.000000
613    0.000000
Name: nyn_sku, dtype: float64
605    6.967742
606    1.451613
607    0.580645
608    0.000000
609    0.000000
610    0.000000
611    0.000000
612    0.000000
613    0.000000
Name: atm_sku, dtype: float64
605    0.922201
606    0.461101
607    0.563567
608    1.075901
609    0.870968
610    1.161290
611    1.178368
612    1.468691
613    1.297913
Name: msj_sku, dtype: float64
605    1.133858
606    0.744094
607    1.275591
608    1.062992
609    1.488189
610    1.027559
611    0.779528
612    0.814961
613    0.673228
Name: fh_sku, dtype: float64
614    0.730388
615    1.379621
616    1.144274
617    0.933273
618    1.436429
619    0.722272
620    0.965735
621    1.046889
622    0.641118
Name: mzc_sku, dtype: float64
614    0.103448
615    0.000000
616    0.000000
617    0.103448
618    0.000000
619    0.000000
620    0.000000
621    0.000000
622    8.793103
Name: yp_sku, dtype: float64
614    0.934054
615    0.972973
616    1.264865
617    1.099459
618    1.216216
619    1.031351
620    0.895135
621    1.060541
622    0.525405
Name: hs_sku, dtype: float64
614    0.0
615    0.0
616    0.0
617    0.0
618    0.0
619    0.0
620    0.0
621    0.0
622    9.0
Name: nyn_sku, dtype: float64
614    0.0
615    0.0
616    0.0
617    0.0
618    0.0
619    0.0
620    0.0
621    0.0
622    9.0
Name: atm_sku, dtype: float64
614    0.746231
615    0.746231
616    1.334171
617    1.288945
618    1.017588
619    0.949749
620    1.017588
621    1.040201
622    0.859296
Name: msj_sku, dtype: float64
614    0.000
615    0.000
616    1.980
617    2.115
618    2.160
619    1.800
620    0.000
621    0.000
622    0.945
Name: fh_sku, dtype: float64
623    1.017199
624    0.972973
625    1.002457
626    0.972973
627    1.017199
628    1.017199
Name: mzc_sku, dtype: float64
623    0.071006
624    1.739645
625    0.887574
626    0.958580
627    1.207101
628    1.136095
Name: yp_sku, dtype: float64
623    0.188811
624    1.636364
625    1.216783
626    1.069930
627    1.111888
628    0.776224
Name: hs_sku, dtype: float64
623    0.000000
624    1.180328
625    1.278689
626    1.180328
627    1.180328
628    1.180328
Name: nyn_sku, dtype: float64
623    0.000000
624    1.411765
625    1.176471
626    1.176471
627    0.941176
628    1.294118
Name: atm_sku, dtype: float64
623    0.923077
624    1.153846
625    1.015385
626    0.969231
627    0.969231
628    0.969231
Name: msj_sku, dtype: float64
623    0.0
624    0.0
625    6.0
626    0.0
627    0.0
628    0.0
Name: fh_sku, dtype: float64
629    1.348148
630    0.829630
631    1.296296
632    1.270370
633    0.440741
634    0.829630
635    0.985185
Name: mzc_sku, dtype: float64
629    0.000000
630    0.000000
631    1.278846
632    1.413462
633    1.951923
634    2.086538
635    0.269231
Name: yp_sku, dtype: float64
629    0.902287
630    0.320166
631    1.222453
632    1.309771
633    0.873181
634    1.207900
635    1.164241
Name: hs_sku, dtype: float64
629    0.000000
630    0.000000
631    0.466667
632    1.166667
633    2.566667
634    2.800000
635    0.000000
Name: nyn_sku, dtype: float64
629    0.000000
630    0.000000
631    0.819820
632    1.828829
633    1.513514
634    2.837838
635    0.000000
Name: atm_sku, dtype: float64
629    0.000000
630    0.000000
631    0.913043
632    2.282609
633    1.318841
634    2.485507
635    0.000000
Name: msj_sku, dtype: float64
629    0.565385
630    0.000000
631    1.480769
632    1.507692
633    1.184615
634    1.426923
635    0.834615
Name: fh_sku, dtype: float64
636    0.750846
637    0.750846
638    0.862458
639    1.278467
640    0.832018
641    0.821871
642    1.065389
643    1.481398
644    1.156708
Name: mzc_sku, dtype: float64
636    0.675456
637    0.584178
638    0.784990
639    0.912779
640    0.529412
641    0.565923
642    0.766734
643    1.898580
644    2.281947
Name: yp_sku, dtype: float64
636    0.697900
637    1.206785
638    0.785137
639    0.857835
640    1.148627
641    0.785137
642    1.206785
643    1.177706
644    1.134087
Name: hs_sku, dtype: float64
636    1.058824
637    1.191176
638    1.720588
639    2.911765
640    1.323529
641    0.661765
642    0.132353
643    0.000000
644    0.000000
Name: nyn_sku, dtype: float64
636    0.7
637    0.7
638    1.6
639    1.2
640    2.1
641    1.4
642    0.1
643    0.8
644    0.4
Name: atm_sku, dtype: float64
636    8.341463
637    0.000000
638    0.219512
639    0.000000
640    0.000000
641    0.000000
642    0.439024
643    0.000000
644    0.000000
Name: msj_sku, dtype: float64
636    0.0
637    0.0
638    0.0
639    0.0
640    0.0
641    0.0
642    0.0
643    9.0
644    0.0
Name: fh_sku, dtype: float64
645    1.046729
646    1.090343
647    0.894081
648    1.232087
649    0.883178
650    0.970405
651    0.883178
Name: mzc_sku, dtype: float64
645    0.925984
646    0.925984
647    0.727559
648    1.444094
649    1.036220
650    0.937008
651    1.003150
Name: yp_sku, dtype: float64
645    0.924272
646    0.924272
647    0.869903
648    0.883495
649    0.978641
650    1.196117
651    1.223301
Name: hs_sku, dtype: float64
645    1.127517
646    1.127517
647    0.892617
648    1.174497
649    0.798658
650    0.939597
651    0.939597
Name: nyn_sku, dtype: float64
645    1.105263
646    1.105263
647    0.967105
648    0.967105
649    1.059211
650    0.921053
651    0.875000
Name: atm_sku, dtype: float64
645    0.593567
646    0.839181
647    0.921053
648    0.859649
649    0.921053
650    1.432749
651    1.432749
Name: msj_sku, dtype: float64
645    0.904615
646    0.926154
647    0.947692
648    0.796923
649    0.947692
650    1.206154
651    1.270769
Name: fh_sku, dtype: float64
652    0.802292
653    0.862464
654    1.323782
655    1.123209
656    1.123209
657    0.762178
658    1.002865
Name: mzc_sku, dtype: float64
652    1.025862
653    0.784483
654    0.844828
655    0.301724
656    1.931034
657    1.508621
658    0.603448
Name: yp_sku, dtype: float64
652    0.926471
653    0.802941
654    1.111765
655    1.152941
656    0.926471
657    0.947059
658    1.132353
Name: hs_sku, dtype: float64
652    0.000000
653    0.000000
654    0.000000
655    0.000000
656    6.222222
657    0.000000
658    0.777778
Name: nyn_sku, dtype: float64
652    0.0
653    0.0
654    0.0
655    0.0
656    1.0
657    0.0
658    6.0
Name: atm_sku, dtype: float64
652    0.580311
653    0.544041
654    1.088083
655    1.051813
656    1.414508
657    1.160622
658    1.160622
Name: msj_sku, dtype: float64
652    1.0
653    0.0
654    0.0
655    0.0
656    3.5
657    0.0
658    2.5
Name: fh_sku, dtype: float64
659    0.953895
660    0.903021
661    0.953895
662    1.131955
663    1.093800
664    1.030207
665    0.953895
666    0.979332
Name: mzc_sku, dtype: float64
659   NaN
660   NaN
661   NaN
662   NaN
663   NaN
664   NaN
665   NaN
666   NaN
Name: yp_sku, dtype: float64
659    0.0
660    1.6
661    0.0
662    0.0
663    0.0
664    0.0
665    6.4
666    0.0
Name: hs_sku, dtype: float64
659   NaN
660   NaN
661   NaN
662   NaN
663   NaN
664   NaN
665   NaN
666   NaN
Name: nyn_sku, dtype: float64
659   NaN
660   NaN
661   NaN
662   NaN
663   NaN
664   NaN
665   NaN
666   NaN
Name: atm_sku, dtype: float64
659   NaN
660   NaN
661   NaN
662   NaN
663   NaN
664   NaN
665   NaN
666   NaN
Name: msj_sku, dtype: float64
659   NaN
660   NaN
661   NaN
662   NaN
663   NaN
664   NaN
665   NaN
666   NaN
Name: fh_sku, dtype: float64
667    1.070866
668    0.897638
669    1.244094
670    0.787402
Name: mzc_sku, dtype: float64
667    0.939759
668    0.915663
669    0.867470
670    1.277108
Name: yp_sku, dtype: float64
667    1.242105
668    1.073684
669    0.905263
670    0.778947
Name: hs_sku, dtype: float64
667    0.9
668    1.2
669    1.1
670    0.8
Name: nyn_sku, dtype: float64
667    1.011494
668    1.241379
669    0.827586
670    0.919540
Name: atm_sku, dtype: float64
667    1.150943
668    0.962264
669    1.037736
670    0.849057
Name: msj_sku, dtype: float64
667   NaN
668   NaN
669   NaN
670   NaN
Name: fh_sku, dtype: float64
671    0.974026
672    0.930736
673    1.038961
674    0.930736
675    0.930736
676    0.844156
677    0.887446
678    1.038961
679    1.255411
680    1.168831
Name: mzc_sku, dtype: float64
671    1.197917
672    1.145833
673    1.406250
674    1.302083
675    1.197917
676    0.000000
677    0.885417
678    1.250000
679    1.041667
680    0.572917
Name: yp_sku, dtype: float64
671    0.951189
672    0.876095
673    0.976220
674    0.963705
675    0.901126
676    0.000000
677    1.013767
678    1.614518
679    1.526909
680    1.176471
Name: hs_sku, dtype: float64
671    2.469136
672    0.000000
673    1.851852
674    1.111111
675    1.728395
676    0.000000
677    1.234568
678    0.370370
679    0.370370
680    0.864198
Name: nyn_sku, dtype: float64
671    1.621622
672    0.000000
673    1.621622
674    2.567568
675    2.027027
676    0.000000
677    1.216216
678    0.270270
679    0.270270
680    0.405405
Name: atm_sku, dtype: float64
671    0.767824
672    0.767824
673    1.151737
674    1.005484
675    1.115174
676    1.279707
677    0.968921
678    0.950640
679    0.968921
680    1.023766
Name: msj_sku, dtype: float64
671    1.497175
672    0.000000
673    0.932203
674    1.694915
675    1.581921
676    0.000000
677    0.903955
678    1.186441
679    1.101695
680    1.101695
Name: fh_sku, dtype: float64
681    1.029412
682    0.967647
683    1.029412
684    0.988235
685    0.967647
686    1.029412
687    0.988235
Name: mzc_sku, dtype: float64
681    0.000000
682    0.000000
683    1.888889
684    1.259259
685    1.296296
686    1.259259
687    1.296296
Name: yp_sku, dtype: float64
681    0.991501
682    0.991501
683    0.991501
684    1.011331
685    1.011331
686    1.031161
687    0.971671
Name: hs_sku, dtype: float64
681    0.000000
682    0.000000
683    1.458333
684    1.458333
685    1.166667
686    1.458333
687    1.458333
Name: nyn_sku, dtype: float64
681    0.000000
682    0.000000
683    1.418919
684    1.418919
685    1.324324
686    1.418919
687    1.418919
Name: atm_sku, dtype: float64
681    0.988038
682    0.988038
683    0.988038
684    0.971292
685    1.021531
686    1.038278
687    1.004785
Name: msj_sku, dtype: float64
681    0.000000
682    0.000000
683    1.370833
684    1.283333
685    1.400000
686    1.604167
687    1.341667
Name: fh_sku, dtype: float64
688    1.861199
689    0.899054
690    0.615142
691    0.678233
692    0.946372
Name: mzc_sku, dtype: float64
688    2.903226
689    2.096774
690    0.000000
691    0.000000
692    0.000000
Name: yp_sku, dtype: float64
688    0.166667
689    4.833333
690    0.000000
691    0.000000
692    0.000000
Name: hs_sku, dtype: float64
688    0.0
689    5.0
690    0.0
691    0.0
692    0.0
Name: nyn_sku, dtype: float64
688    0.0
689    5.0
690    0.0
691    0.0
692    0.0
Name: atm_sku, dtype: float64
688    0.5
689    4.5
690    0.0
691    0.0
692    0.0
Name: msj_sku, dtype: float64
688    0.0
689    2.5
690    0.0
691    0.0
692    2.5
Name: fh_sku, dtype: float64
693    0.884521
694    0.825553
695    0.972973
696    1.061425

Name: atm_sku, dtype: float64
693     0.0
694     0.0
695     0.0
696     0.0
697    12.0
698     0.0
699     0.0
700     0.0
701     0.0
702     0.0
703     0.0
704     0.0
Name: msj_sku, dtype: float64
693    0.0
694    4.0
695    0.0
696    0.0
697    0.0
698    0.0
699    0.0
700    0.0
701    0.0
702    4.0
703    0.0
704    4.0
Name: fh_sku, dtype: float64
705    0.90
706    0.98
707    1.02
708    1.18
709    0.90
710    0.96
711    1.06
Name: mzc_sku, dtype: float64
705    7.0
706    0.0
707    0.0
708    0.0
709    0.0
710    0.0
711    0.0
Name: yp_sku, dtype: float64
705   NaN
706   NaN
707   NaN
708   NaN
709   NaN
710   NaN
711   NaN
Name: hs_sku, dtype: float64
705   NaN
706   NaN
707   NaN
708   NaN
709   NaN
710   NaN
711   NaN
Name: nyn_sku, dtype: float64
705   NaN
706   NaN
707   NaN
708   NaN
709   NaN
710   NaN
711   NaN
Name: atm_sku, dtype: float64
705   NaN
706   NaN
707   NaN
708   NaN
709   NaN
710   NaN
711   NaN
Name: msj_sku, dtype: float64
705    7.0
706    0.0
707    0.0
708    0.0
709    0.0
710    0.0
711    0.0
Name: fh_sku, dtype: float64
712    1.227273
713    1.348485
714    1.151515
715    0.712121
716    0.772727
717    0.787879
Name: mzc_sku, dtype: float64
712    1.00
713    1.24
714    1.26
715    0.74
716    0.90
717    0.86
Name: yp_sku, dtype: float64
712    1.219672
713    0.924590
714    1.003279
715    1.042623
716    0.983607
717    0.826230
Name: hs_sku, dtype: float64
712    1.772727
713    1.500000
714    1.227273
715    0.136364
716    0.272727
717    1.090909
Name: nyn_sku, dtype: float64
712    0.797872
713    0.893617
714    0.989362
715    1.117021
716    0.606383
717    1.595745
Name: atm_sku, dtype: float64
712    1.160494
713    1.037037
714    1.037037
715    0.938272
716    0.938272
717    0.888889
Name: msj_sku, dtype: float64
712   NaN
713   NaN
714   NaN
715   NaN
716   NaN
717   NaN
Name: fh_sku, dtype: float64
718    0.861538
719    0.888889
720    0.970940
721    1.422222
722    0.724786
723    0.929915
724    0.847863
725    1.353846
Name: mzc_sku, dtype: float64
718    0.000000
719    0.000000
720    0.000000
721    0.000000
722    1.680672
723    1.747899
724    1.613445
725    2.957983
Name: yp_sku, dtype: float64
718    0.522523
719    0.648649
720    0.522523
721    0.468468
722    1.171171
723    1.315315
724    1.711712
725    1.639640
Name: hs_sku, dtype: float64
718    0.000000
719    0.000000
720    0.000000
721    0.000000
722    0.000000
723    2.823529
724    2.352941
725    2.823529
Name: nyn_sku, dtype: float64
718    0.000000
719    0.307692
720    0.000000
721    0.000000
722    0.000000
723    2.769231
724    2.153846
725    2.769231
Name: atm_sku, dtype: float64
718    1.065217
719    1.739130
720    0.260870
721    2.000000
722    0.826087
723    0.891304
724    0.847826
725    0.369565
Name: msj_sku, dtype: float64
718    0.000000
719    0.000000
720    0.000000
721    0.000000
722    1.087379
723    2.330097
724    3.106796
725    1.475728
Name: fh_sku, dtype: float64
726    0.731183
727    0.709677
728    1.118280
729    0.838710
730    1.290323
731    0.967742
732    1.161290
733    1.182796
Name: mzc_sku, dtype: float64
726    0.504505
727    1.225225
728    0.792793
729    1.009009
730    0.792793
731    0.720721
732    1.153153
733    1.801802
Name: yp_sku, dtype: float64
726    0.755140
727    0.740187
728    1.465421
729    0.927103
730    1.128972
731    1.099065
732    1.128972
733    0.755140
Name: hs_sku, dtype: float64
726    2.933333
727    0.000000
728    0.000000
729    1.066667
730    1.866667
731    0.533333
732    0.622222
733    0.977778
Name: nyn_sku, dtype: float64
726    0.000000
727    0.000000
728    0.000000
729    1.466667
730    0.800000
731    3.466667
732    1.733333
733    0.533333
Name: atm_sku, dtype: float64
726    0.514412
727    0.496674
728    1.348115
729    1.312639
730    1.064302
731    1.028825
732    0.780488
733    1.454545
Name: msj_sku, dtype: float64
726    0.939551
727    0.746114
728    0.013817
729    0.773748
730    0.994819
731    1.298791
732    1.685665
733    1.547496
Name: fh_sku, dtype: float64
734    1.039773
735    0.937500
736    1.022727
Name: mzc_sku, dtype: float64
734    0.6
735    1.0
736    1.4
Name: yp_sku, dtype: float64
734    0.988827
735    0.905028
736    1.106145
Name: hs_sku, dtype: float64
734    1.034483
735    1.034483
736    0.931034
Name: nyn_sku, dtype: float64
734    1.000000
735    1.111111
736    0.888889
Name: atm_sku, dtype: float64
734    1.121495
735    0.785047
736    1.093458
Name: msj_sku, dtype: float64
734    0.0
735    3.0
736    0.0
Name: fh_sku, dtype: float64
737    0.694678
738    0.627451
739    0.694678
740    0.985994
741    1.008403
742    1.232493
743    1.210084
744    1.546218
Name: mzc_sku, dtype: float64
737    0.964427
738    0.695652
739    0.743083
740    0.790514
741    0.743083
742    1.628458
743    1.233202
744    1.201581
Name: yp_sku, dtype: float64
737    0.914761
738    0.681913
739    0.848233
740    0.748441
741    0.798337
742    1.796258
743    0.698545
744    1.513514
Name: hs_sku, dtype: float64
737    0.000000
738    0.000000
739    0.000000
740    3.404255
741    0.000000
742    1.021277
743    0.000000
744    3.574468
Name: nyn_sku, dtype: float64
737    0.000000
738    0.000000
739    0.000000
740    1.052632
741    0.000000
742    2.526316
743    0.000000
744    4.421053
Name: atm_sku, dtype: float64
737    0.000000
738    0.000000
739    0.000000
740    2.238532
741    0.000000
742    2.385321
743    0.256881
744    3.119266
Name: msj_sku, dtype: float64
737    0.000000
738    0.000000
739    0.000000
740    2.333333
741    0.000000
742    3.000000
743    0.416667
744    2.250000
Name: fh_sku, dtype: float64
745    0.722222
746    0.694444
747    0.916667
748    0.861111
749    1.194444
750    1.222222
751    1.194444
752    1.111111
753    1.083333
Name: mzc_sku, dtype: float64
745    0.882353
746    0.882353
747    1.588235
748    1.235294
749    0.970588
750    0.705882
751    1.235294
752    0.705882
753    0.794118
Name: yp_sku, dtype: float64
745    1.289474
746    1.421053
747    1.657895
748    0.947368
749    0.973684
750    0.657895
751    0.842105
752    0.631579
753    0.578947
Name: hs_sku, dtype: float64
745    0.957447
746    0.765957
747    1.531915
748    1.148936
749    1.148936
750    0.957447
751    0.000000
752    0.957447
753    1.531915
Name: nyn_sku, dtype: float64
745    0.310345
746    0.310345
747    1.241379
748    0.620690
749    0.931034
750    0.310345
751    0.000000
752    2.172414
753    3.103448
Name: atm_sku, dtype: float64
745    1.434783
746    0.913043
747    1.000000
748    1.434783
749    1.217391
750    0.434783
751    0.739130
752    1.000000
753    0.826087
Name: msj_sku, dtype: float64
745    1.352941
746    1.352941
747    0.941176
748    1.176471
749    1.000000
750    0.000000
751    0.352941
752    1.411765
753    1.411765
Name: fh_sku, dtype: float64
754    1.226837
755    0.709265
756    1.015974
757    1.054313
758    1.111821
759    0.881789
Name: mzc_sku, dtype: float64
754    1.382488
755    1.327189
756    1.548387
757    0.552995
758    0.497696
759    0.691244
Name: yp_sku, dtype: float64
754    0.933014
755    0.846890
756    1.191388
757    0.990431
758    0.947368
759    1.090909
Name: hs_sku, dtype: float64
754    0.792453
755    0.000000
756    1.924528
757    0.905660
758    0.905660
759    1.471698
Name: nyn_sku, dtype: float64
754    1.348315
755    0.438202
756    1.247191
757    1.011236
758    0.977528
759    0.977528
Name: atm_sku, dtype: float64
754    0.904523
755    0.814070
756    1.296482
757    0.934673
758    1.040201
759    1.010050
Name: msj_sku, dtype: float64
754    1.359606
755    1.152709
756    1.448276
757    0.147783
758    0.857143
759    1.034483
Name: fh_sku, dtype: float64
760    0.652720
761    1.051604
762    0.779637
763    0.743375
764    0.725244
765    0.634589
766    0.725244
767    0.580195
768    1.142259
769    1.831241
770    1.323570
771    1.377964
772    1.432357
Name: mzc_sku, dtype: float64
760    1.826446
761    0.913223
762    1.181818
763    1.181818
764    1.235537
765    0.698347
766    0.966942
767    0.966942
768    0.483471
769    0.537190
770    0.483471
771    1.289256
772    1.235537
Name: yp_sku, dtype: float64
760    1.717234
761    1.033024
762    0.845201
763    1.180599
764    1.126935
765    1.019608
766    0.657379
767    0.791538
768    0.885449
769    0.684211
770    0.992776
771    1.006192
772    1.059856
Name: hs_sku, dtype: float64
760    1.471698
761    0.817610
762    2.289308
763    2.534591
764    1.471698
765    1.308176
766    1.144654
767    1.144654
768    0.000000
769    0.000000
770    0.000000
771    0.408805
772    0.408805
Name: nyn_sku, dtype: float64
760    2.384892
761    1.122302
762    1.870504
763    1.917266
764    1.917266
765    0.982014
766    1.402878
767    0.841727
768    0.000000
769    0.000000
770    0.000000
771    0.280576
772    0.280576
Name: atm_sku, dtype: float64
760    1.380531
761    1.150442
762    1.058407
763    0.989381
764    1.150442
765    1.173451
766    0.322124
767    0.874336
768    1.265487
769    0.897345
770    0.805310
771    0.966372
772    0.966372
Name: msj_sku, dtype: float64
760    1.335135
761    1.124324
762    0.000000
763    1.194595
764    0.983784
765    0.000000
766    0.772973
767    1.194595
768    0.772973
769    1.335135
770    0.702703
771    1.124324
772    2.459459
Name: fh_sku, dtype: float64
773    0.964286
774    0.952381
775    1.023810
776    1.011905
777    1.047619
Name: mzc_sku, dtype: float64
773    1.037736
774    0.990566
775    0.990566
776    0.990566
777    0.990566
Name: yp_sku, dtype: float64
773    1.025180
774    1.034173
775    0.971223
776    0.998201
777    0.971223
Name: hs_sku, dtype: float64
773    1.176471
774    1.323529
775    1.176471
776    0.588235
777    0.735294
Name: nyn_sku, dtype: float64
773    1.465517
774    1.034483
775    1.293103
776    0.517241
777    0.689655
Name: atm_sku, dtype: float64
773    1.016484
774    1.043956
775    1.016484
776    0.961538
777    0.961538
Name: msj_sku, dtype: float64
773   NaN
774   NaN
775   NaN
776   NaN
777   NaN
Name: fh_sku, dtype: float64
778    0.904255
779    0.904255
780    1.010638
781    0.851064
782    1.329787
Name: mzc_sku, dtype: float64
778    1.50
779    0.00
780    1.50
781    1.75
782    0.25
Name: yp_sku, dtype: float64
778    0.714286
779    1.428571
780    1.785714
781    0.714286
782    0.357143
Name: hs_sku, dtype: float64
778    0.000000
779    0.000000
780    0.714286
781    0.000000
782    4.285714
Name: nyn_sku, dtype: float64
778    1.250000
779    1.250000
780    1.666667
781    0.000000
782    0.833333
Name: atm_sku, dtype: float64
778    1.25
779    1.25
780    1.25
781    1.25
782    0.00
Name: msj_sku, dtype: float64
778    1.50
779    1.50
780    0.75
781    1.25
782    0.00
Name: fh_sku, dtype: float64
783    0.892857
784    1.026786
785    1.250000
786    0.178571
787    1.651786
Name: mzc_sku, dtype: float64
783   NaN
784   NaN
785   NaN
786   NaN
787   NaN
Name: yp_sku, dtype: float64
783    1.6
784    0.0
785    0.8
786    0.4
787    2.2
Name: hs_sku, dtype: float64
783    2.5
784    2.5
785    0.0
786    0.0
787    0.0
Name: nyn_sku, dtype: float64
783    0.0
784    5.0
785    0.0
786    0.0
787    0.0
Name: atm_sku, dtype: float64
783    0.277778
784    0.000000
785    1.666667
786    1.388889
787    1.666667
Name: msj_sku, dtype: float64
783   NaN
784   NaN
785   NaN
786   NaN
787   NaN
Name: fh_sku, dtype: float64
788    0.649038
789    0.692308
790    0.692308
791    0.649038
792    0.951923
793    0.692308
794    1.427885
795    1.730769
796    1.514423
Name: mzc_sku, dtype: float64
788    1.687500
789    0.715909
790    0.767045
791    0.767045
792    1.227273
793    0.767045
794    0.715909
795    1.176136
796    1.176136
Name: yp_sku, dtype: float64
788    0.820144
789    0.884892
790    1.294964
791    0.992806
792    0.561151
793    0.841727
794    0.755396
795    1.424460
796    1.424460
Name: hs_sku, dtype: float64
788    1.459459
789    2.189189
790    1.459459
791    0.729730
792    2.189189
793    0.000000
794    0.243243
795    0.486486
796    0.243243
Name: nyn_sku, dtype: float64
788    2.605263
789    2.368421
790    1.657895
791    1.421053
792    0.947368
793    0.000000
794    0.000000
795    0.000000
796    0.000000
Name: atm_sku, dtype: float64
788    1.525952
789    0.685121
790    0.996540
791    0.996540
792    1.245675
793    0.934256
794    0.903114
795    1.089965
796    0.622837
Name: msj_sku, dtype: float64
788    0.000000
789    0.000000
790    0.000000
791    0.000000
792    1.038462
793    0.692308
794    2.076923
795    3.461538
796    1.730769
Name: fh_sku, dtype: float64
797    1.219048
798    0.723810
799    1.028571
800    1.028571
Name: mzc_sku, dtype: float64
797    0.909091
798    0.848485
799    1.393939
800    0.848485
Name: yp_sku, dtype: float64
797    1.025641
798    0.957265
799    1.094017
800    0.923077
Name: hs_sku, dtype: float64
797    0.631579
798    1.052632
799    1.052632
800    1.263158
Name: nyn_sku, dtype: float64
797    0.9375
798    1.1250
799    1.0625
800    0.8750
Name: atm_sku, dtype: float64
797    0.946237
798    1.032258
799    1.118280
800    0.903226
Name: msj_sku, dtype: float64
797    0.734694
798    1.387755
799    0.979592
800    0.897959
Name: fh_sku, dtype: float64
801    1.059761
802    1.059761
803    0.920319
804    1.041169
805    1.022576
806    1.003984
807    0.892430
Name: mzc_sku, dtype: float64
801    1.193684
802    1.208421
803    0.000000
804    1.105263
805    1.223158
806    1.208421
807    1.061053
Name: yp_sku, dtype: float64
801    1.0250
802    1.0000
803    1.0000
804    0.9750
805    1.0000
806    0.9875
807    1.0125
Name: hs_sku, dtype: float64
801    1.027523
802    1.027523
803    1.027523
804    1.027523
805    0.963303
806    1.027523
807    0.899083
Name: nyn_sku, dtype: float64
801    0.858491
802    0.990566
803    1.056604
804    0.924528
805    1.056604
806    1.056604
807    1.056604
Name: atm_sku, dtype: float64
801    0.989899
802    1.159596
803    0.890909
804    1.074747
805    1.046465
806    0.919192
807    0.919192
Name: msj_sku, dtype: float64
801    3.5
802    0.0
803    0.0
804    0.0
805    3.5
806    0.0
807    0.0
Name: fh_sku, dtype: float64
808    0.595041
809    1.035813
810    0.870523
811    1.498623

Name: mzc_sku, dtype: float64
808    0.25
809    3.00
810    0.25
811    0.50
Name: yp_sku, dtype: float64
808    0.0
809    4.0
810    0.0
811    0.0
Name: hs_sku, dtype: float64
808   NaN
809   NaN
810   NaN
811   NaN
Name: nyn_sku, dtype: float64
808   NaN
809   NaN
810   NaN
811   NaN
Name: atm_sku, dtype: float64
808    0.0
809    4.0
810    0.0
811    0.0
Name: msj_sku, dtype: float64
808    0.000000
809    2.666667
810    0.000000
811    1.333333
Name: fh_sku, dtype: float64
812    1.036364
813    1.072727
814    1.018182
815    0.981818
816    0.945455
817    0.945455
Name: mzc_sku, dtype: float64
812    1.052239
813    0.828358
814    0.895522
815    1.029851
816    1.029851
817    1.164179
Name: yp_sku, dtype: float64
812    0.953846
813    1.200000
814    1.015385
815    1.138462
816    0.830769
817    0.861538
Name: hs_sku, dtype: float64
812    1.032258
813    0.967742
814    1.032258
815    1.032258
816    1.032258
817    0.903226
Name: nyn_sku, dtype: float64
812    1.012658
813    0.886076
814    1.063291
815    0.987342
816    1.037975
817    1.012658
Name: atm_sku, dtype: float64
812    1.083612
813    1.103679
814    0.882943
815    0.923077
816    1.003344
817    1.003344
Name: msj_sku, dtype: float64
812   NaN
813   NaN
814   NaN
815   NaN
816   NaN
817   NaN
Name: fh_sku, dtype: float64
818    1.317073
819    1.231707
820    1.292683
821    0.597561
822    0.560976
Name: mzc_sku, dtype: float64
818    1.633523
819    1.250000
820    1.264205
821    0.525568
822    0.326705
Name: yp_sku, dtype: float64
818    1.361257
819    1.086387
820    1.204188
821    0.759162
822    0.589005
Name: hs_sku, dtype: float64
818    0.895522
819    1.492537
820    1.268657
821    0.820896
822    0.522388
Name: nyn_sku, dtype: float64
818    2.127660
819    0.851064
820    1.170213
821    0.425532
822    0.425532
Name: atm_sku, dtype: float64
818    1.226415
819    0.867925
820    1.075472
821    0.886792
822    0.943396
Name: msj_sku, dtype: float64
818    0.0
819    0.0
820    0.0
821    0.0
822    5.0
Name: fh_sku, dtype: float64
823    0.886598
824    1.113402
Name: mzc_sku, dtype: float64
823    0.888889
824    1.111111
Name: yp_sku, dtype: float64
823    1.053571
824    0.946429
Name: hs_sku, dtype: float64
823   NaN
824   NaN
Name: nyn_sku, dtype: float64
823   NaN
824   NaN
Name: atm_sku, dtype: float64
823    0.941176
824    1.058824
Name: msj_sku, dtype: float64
823   NaN
824   NaN
Name: fh_sku, dtype: float64
825    1.0
Name: mzc_sku, dtype: float64
825   NaN
Name: yp_sku, dtype: float64
825    1.0
Name: hs_sku, dtype: float64
825   NaN
Name: nyn_sku, dtype: float64
825    1.0
Name: atm_sku, dtype: float64
825    1.0
Name: msj_sku, dtype: float64
825   NaN
Name: fh_sku, dtype: float64
826    1.395349
827    0.767442
828    0.837209
Name: mzc_sku, dtype: float64
826    1.008621
827    1.008621
828    0.982759
Name: yp_sku, dtype: float64
826    0.933673
827    1.010204
828    1.056122
Name: hs_sku, dtype: float64
826    0.807692
827    1.269231
828    0.923077
Name: nyn_sku, dtype: float64
826    1.000000
827    0.777778
828    1.222222
Name: atm_sku, dtype: float64
826    0.75
827    1.25
828    1.00
Name: msj_sku, dtype: float64
826   NaN
827   NaN
828   NaN
Name: fh_sku, dtype: float64
829    1.850318
830    1.003185
831    0.891720
832    1.092357
833    0.557325
834    0.936306
835    0.668790
Name: mzc_sku, dtype: float64
829    1.201320
830    0.762376
831    0.392739
832    0.762376
833    1.108911
834    1.432343
835    1.339934
Name: yp_sku, dtype: float64
829    1.262019
830    1.026442
831    1.144231
832    0.942308
833    0.740385
834    0.925481
835    0.959135
Name: hs_sku, dtype: float64
829    0.000000
830    1.772152
831    0.886076
832    1.329114
833    0.531646
834    1.329114
835    1.151899
Name: nyn_sku, dtype: float64
829    0.000000
830    1.533333
831    0.866667
832    1.800000
833    0.466667
834    1.200000
835    1.133333
Name: atm_sku, dtype: float64
829    0.565217
830    1.347826
831    0.282609
832    0.891304
833    1.043478
834    1.391304
835    1.478261
Name: msj_sku, dtype: float64
829    0.967480
830    1.195122
831    1.052846
832    0.711382
833    0.853659
834    1.252033
835    0.967480
Name: fh_sku, dtype: float64
836    1.287671
837    0.712329
838    0.767123
839    1.232877
Name: mzc_sku, dtype: float64
836    0.805755
837    0.805755
838    1.294964
839    1.093525
Name: yp_sku, dtype: float64
836    0.881890
837    0.818898
838    0.755906
839    1.543307
Name: hs_sku, dtype: float64
836    0.712329
837    0.547945
838    1.205479
839    1.534247
Name: nyn_sku, dtype: float64
836    0.953642
837    0.715232
838    1.245033
839    1.086093
Name: atm_sku, dtype: float64
836    1.324138
837    0.744828
838    0.800000
839    1.131034
Name: msj_sku, dtype: float64
836    1.028571
837    0.914286
838    1.302857
839    0.754286
Name: fh_sku, dtype: float64
840    1.84
841    0.96
842    0.80
843    0.80
844    0.94
845    0.90
846    0.92
847    0.84
Name: mzc_sku, dtype: float64
840    1.018568
841    1.018568
842    0.997347
843    0.827586
844    1.039788
845    1.018568
846    1.061008
847    1.018568
Name: yp_sku, dtype: float64
840    0.812834
841    1.069519
842    1.090909
843    0.994652
844    0.983957
845    1.048128
846    1.005348
847    0.994652
Name: hs_sku, dtype: float64
840    0.984615
841    1.661538
842    0.615385
843    0.615385
844    1.230769
845    1.107692
846    0.800000
847    0.984615
Name: nyn_sku, dtype: float64
840    0.964824
841    0.844221
842    1.165829
843    1.286432
844    0.804020
845    0.924623
846    1.005025
847    1.005025
Name: atm_sku, dtype: float64
840    1.012920
841    1.054264
842    0.992248
843    1.033592
844    0.971576
845    1.012920
846    0.950904
847    0.971576
Name: msj_sku, dtype: float64
840    0.0
841    0.0
842    0.0
843    0.0
844    8.0
845    0.0
846    0.0
847    0.0
Name: fh_sku, dtype: float64
848    0.829876
849    1.037344
850    0.995851
851    1.058091
852    1.078838
Name: mzc_sku, dtype: float64
848    0.901288
849    1.008584
850    1.030043
851    1.008584
852    1.051502
Name: yp_sku, dtype: float64
848    0.737410
849    0.935252
850    1.025180
851    1.241007
852    1.061151
Name: hs_sku, dtype: float64
848    0.992366
849    1.068702
850    1.068702
851    1.030534
852    0.839695
Name: nyn_sku, dtype: float64
848    0.675676
849    0.405405
850    1.351351
851    0.945946
852    1.621622
Name: atm_sku, dtype: float64
848    0.923913
849    1.141304
850    1.059783
851    1.005435
852    0.869565
Name: msj_sku, dtype: float64
848    0.0
849    0.0
850    0.0
851    0.0
852    5.0
Name: fh_sku, dtype: float64
853    0.955243
854    0.955243
855    0.966752
856    0.966752
857    0.955243
858    1.335038
859    0.955243
860    0.966752
861    0.943734
Name: mzc_sku, dtype: float64
853    1.130233
854    1.088372
855    1.018605
856    1.102326
857    1.074419
858    0.865116
859    0.906977
860    0.906977
861    0.906977
Name: yp_sku, dtype: float64
853    1.048673
854    0.955752
855    0.942478
856    1.061947
857    0.995575
858    0.982301
859    1.048673
860    1.048673
861    0.915929
Name: hs_sku, dtype: float64
853   NaN
854   NaN
855   NaN
856   NaN
857   NaN
858   NaN
859   NaN
860   NaN
861   NaN
Name: nyn_sku, dtype: float64
853    0.0
854    4.5
855    0.0
856    4.5
857    0.0
858    0.0
859    0.0
860    0.0
861    0.0
Name: atm_sku, dtype: float64
853    9.0
854    0.0
855    0.0
856    0.0
857    0.0
858    0.0
859    0.0
860    0.0
861    0.0
Name: msj_sku, dtype: float64
853    1.636364
854    0.975524
855    1.510490
856    1.195804
857    1.132867
858    0.881119
859    0.849650
860    0.818182
861    0.000000
Name: fh_sku, dtype: float64
862    1.010204
863    0.979592
864    0.969388
865    1.010204
866    1.030612
Name: mzc_sku, dtype: float64
862    0.994832
863    1.356589
864    1.007752
865    0.891473
866    0.749354
Name: yp_sku, dtype: float64
862    1.340289
863    1.396469
864    0.834671
865    0.746388
866    0.682183
Name: hs_sku, dtype: float64
862    0.888889
863    0.777778
864    1.555556
865    1.000000
866    0.777778
Name: nyn_sku, dtype: float64
862    1.228814
863    0.847458
864    0.593220
865    1.101695
866    1.228814
Name: atm_sku, dtype: float64
862    1.203931
863    1.093366
864    1.031941
865    0.884521
866    0.786241
Name: msj_sku, dtype: float64
862   NaN
863   NaN
864   NaN
865   NaN
866   NaN
Name: fh_sku, dtype: float64
867    0.935065
868    0.779221
869    1.194805
870    1.090909
Name: mzc_sku, dtype: float64
867   NaN
868   NaN
869   NaN
870   NaN
Name: yp_sku, dtype: float64
867    1.6
868    0.8
869    0.8
870    0.8
Name: hs_sku, dtype: float64
867   NaN
868   NaN
869   NaN
870   NaN
Name: nyn_sku, dtype: float64
867   NaN
868   NaN
869   NaN
870   NaN
Name: atm_sku, dtype: float64
867    1.12
868    0.96
869    0.96
870    0.96
Name: msj_sku, dtype: float64
867   NaN
868   NaN
869   NaN
870   NaN
Name: fh_sku, dtype: float64
871    1.120462
872    1.028053
873    0.820132
874    1.004950
875    1.051155
876    1.004950
877    0.970297
Name: mzc_sku, dtype: float64
871    1.147849
872    0.997312
873    0.000000
874    0.827957
875    0.922043
876    0.620968
877    2.483871
Name: yp_sku, dtype: float64
871    1.098312
872    1.320755
873    0.000000
874    1.292949
875    1.425025
876    1.181728
877    0.681231
Name: hs_sku, dtype: float64
871    2.507463
872    2.228856
873    0.000000
874    0.000000
875    0.000000
876    1.044776
877    1.218905
Name: nyn_sku, dtype: float64
871    1.411765
872    1.647059
873    0.000000
874    0.000000
875    0.019608
876    2.647059
877    1.274510
Name: atm_sku, dtype: float64
871    1.062651
872    1.096386
873    0.000000
874    1.180723
875    1.315663
876    0.944578
877    1.400000
Name: msj_sku, dtype: float64
871    1.942197
872    2.144509
873    0.000000
874    1.213873
875    1.335260
876    0.242775
877    0.121387
Name: fh_sku, dtype: float64
878    0.893557
879    1.047619
880    1.109244
881    1.016807
882    0.985994
883    1.109244
884    0.893557
885    0.831933
886    0.924370
887    0.924370
888    1.263305
Name: mzc_sku, dtype: float64
878    0.789238
879    1.331839
880    1.381166
881    0.887892
882    1.134529
883    1.035874
884    0.986547
885    0.000000
886    0.690583
887    1.282511
888    1.479821
Name: yp_sku, dtype: float64
878    1.648712
879    0.901639
880    0.850117
881    1.262295
882    0.824356
883    1.004684
884    0.927400
885    0.644028
886    0.978923
887    1.056206
888    0.901639
Name: hs_sku, dtype: float64
878    0.873016
879    0.960317
880    1.309524
881    0.436508
882    1.134921
883    1.746032
884    1.222222
885    0.174603
886    0.960317
887    0.436508
888    1.746032
Name: nyn_sku, dtype: float64
878    0.768817
879    1.182796
880    0.473118
881    0.768817
882    0.768817
883    0.473118
884    0.946237
885    0.768817
886    1.951613
887    1.064516
888    1.833333
Name: atm_sku, dtype: float64
878    0.976834
879    0.976834
880    0.934363
881    1.231660
882    0.722008
883    1.019305
884    0.849421
885    1.061776
886    1.019305
887    0.891892
888    1.316602
Name: msj_sku, dtype: float64
878    0.949239
879    0.837563
880    1.507614
881    0.000000
882    1.228426
883    1.619289
884    0.837563
885    1.005076
886    0.781726
887    1.172589
888    1.060914
Name: fh_sku, dtype: float64
889    1.316
890    1.008
891    0.924
892    0.840
893    0.924
894    0.980
895    1.008
Name: mzc_sku, dtype: float64
889    1.040541
890    0.827703
891    1.087838
892    0.993243
893    1.087838
894    1.111486
895    0.851351
Name: yp_sku, dtype: float64
889    1.177658
890    1.083445
891    1.139973
892    0.998654
893    0.791386
894    0.810229
895    0.998654
Name: hs_sku, dtype: float64
889   NaN
890   NaN
891   NaN
892   NaN
893   NaN
894   NaN
895   NaN
Name: nyn_sku, dtype: float64
889    0.0
890    0.0
891    0.0
892    0.0
893    0.0
894    7.0
895    0.0
Name: atm_sku, dtype: float64
889   NaN
890   NaN
891   NaN
892   NaN
893   NaN
894   NaN
895   NaN
Name: msj_sku, dtype: float64
889   NaN
890   NaN
891   NaN
892   NaN
893   NaN
894   NaN
895   NaN
Name: fh_sku, dtype: float64
896    1.042945
897    0.981595
898    1.027607
899    0.981595
900    0.966258
Name: mzc_sku, dtype: float64
896    1.022727
897    0.890152
898    1.060606
899    1.174242
900    0.852273
Name: yp_sku, dtype: float64
896    1.052632
897    0.977444
898    0.864662
899    0.977444
900    1.127820
Name: hs_sku, dtype: float64
896    1.022727
897    1.022727
898    1.022727
899    0.909091
900    1.022727
Name: nyn_sku, dtype: float64
896    1.162791
897    0.755814
898    1.104651
899    0.988372
900    0.988372
Name: atm_sku, dtype: float64
896   NaN
897   NaN
898   NaN
899   NaN
900   NaN
Name: msj_sku, dtype: float64
896    0.0
897    5.0
898    0.0
899    0.0
900    0.0
Name: fh_sku, dtype: float64
901    1.401274
902    0.063694
903    1.512739
904    1.401274
905    0.621019
Name: mzc_sku, dtype: float64
901    0.966851
902    0.276243
903    1.270718
904    1.104972
905    1.381215
Name: yp_sku, dtype: float64
901    0.597826
902    0.978261
903    0.797101
904    0.887681
905    1.739130
Name: hs_sku, dtype: float64
901    0.000000
902    2.692308
903    0.192308
904    0.256410
905    1.858974
Name: nyn_sku, dtype: float64
901    0.070423
902    1.830986
903    0.563380
904    0.563380
905    1.971831
Name: atm_sku, dtype: float64
901    1.475410
902    0.081967
903    1.639344
904    0.942623
905    0.860656
Name: msj_sku, dtype: float64
901   NaN
902   NaN
903   NaN
904   NaN
905   NaN
Name: fh_sku, dtype: float64
906    1.003861
907    1.003861
908    1.120978
909    1.020592
910    1.070785
911    0.970399
912    0.936937
913    0.886744
914    1.438867
915    0.769627
916    0.886744
917    0.936937
918    0.953668
Name: mzc_sku, dtype: float64
906   NaN
907   NaN
908   NaN
909   NaN
910   NaN
911   NaN
912   NaN
913   NaN
914   NaN
915   NaN
916   NaN
917   NaN
918   NaN
Name: yp_sku, dtype: float64
906    0.000000
907    0.000000
908    4.333333
909    0.000000
910    0.000000
911    8.666667
912    0.000000
913    0.000000
914    0.000000
915    0.000000
916    0.000000
917    0.000000
918    0.000000
Name: hs_sku, dtype: float64
906     0.000000
907     0.000000
908     0.866667
909     0.000000
910     0.000000
911     0.000000
912     0.000000
913     0.000000
914    12.133333
915     0.000000
916     0.000000
917     0.000000
918     0.000000
Name: nyn_sku, dtype: float64
906     0.0
907     0.0
908     1.3
909     0.0
910     0.0
911     0.0
912     0.0
913     0.0
914    11.7
915     0.0
916     0.0
917     0.0
918     0.0
Name: atm_sku, dtype: float64
906     0.0
907     0.0
908    13.0
909     0.0
910     0.0
911     0.0
912     0.0
913     0.0
914     0.0
915     0.0
916     0.0
917     0.0
918     0.0
Name: msj_sku, dtype: float64
906   NaN
907   NaN
908   NaN
909   NaN
910   NaN
911   NaN
912   NaN
913   NaN
914   NaN
915   NaN
916   NaN
917   NaN
918   NaN
Name: fh_sku, dtype: float64
919    1.246819
920    0.610687
921    0.877863
922    1.170483
923    1.094148
Name: mzc_sku, dtype: float64
919    1.030928
920    0.322165
921    1.172680
922    1.301546
923    1.172680
Name: yp_sku, dtype: float64
919    1.245353
920    0.390335
921    0.985130
922    1.133829
923    1.245353
Name: hs_sku, dtype: float64
919    1.285714
920    0.000000
921    1.071429
922    1.571429
923    1.071429
Name: nyn_sku, dtype: float64
919    0.971223
920    0.000000
921    1.402878
922    1.258993
923    1.366906
Name: atm_sku, dtype: float64
919    0.951220
920    0.780488
921    0.902439
922    1.073171
923    1.292683
Name: msj_sku, dtype: float64
919   NaN
920   NaN
921   NaN
922   NaN
923   NaN
Name: fh_sku, dtype: float64
924    0.454545
925    1.545455
Name: mzc_sku, dtype: float64
924    0.0
925    2.0
Name: yp_sku, dtype: float64
924    0.0
925    2.0
Name: hs_sku, dtype: float64
924   NaN
925   NaN
Name: nyn_sku, dtype: float64
924   NaN
925   NaN
Name: atm_sku, dtype: float64
924   NaN
925   NaN
Name: msj_sku, dtype: float64
924   NaN
925   NaN
Name: fh_sku, dtype: float64
926    0.608696
927    1.391304
Name: mzc_sku, dtype: float64
926    0.25
927    1.75
Name: yp_sku, dtype: float64
926    2.0
927    0.0
Name: hs_sku, dtype: float64
926   NaN
927   NaN
Name: nyn_sku, dtype: float64
926   NaN
927   NaN
Name: atm_sku, dtype: float64
926    0.0
927    2.0
Name: msj_sku, dtype: float64
926   NaN
927   NaN
Name: fh_sku, dtype: float64
928    1.0
929    1.0
Name: mzc_sku, dtype: float64
928    1.0
929    1.0
Name: yp_sku, dtype: float64
928    1.142857
929    0.857143
Name: hs_sku, dtype: float64
928    1.0
929    1.0
Name: nyn_sku, dtype: float64
928    1.0
929    1.0
Name: atm_sku, dtype: float64
928    1.0
929    1.0
Name: msj_sku, dtype: float64
928   NaN
929   NaN
Name: fh_sku, dtype: float64

930    1.090909
931    1.090909
932    0.969697
933    0.969697
934    0.969697
935    0.969697
936    0.969697
937    0.969697
Name: mzc_sku, dtype: float64
930    1.0
931    1.0
932    1.0
933    1.0
934    1.0
935    1.0
936    1.0
937    1.0
Name: yp_sku, dtype: float64
930   NaN
931   NaN
932   NaN
933   NaN
934   NaN
935   NaN
936   NaN
937   NaN
Name: hs_sku, dtype: float64
930    1.0
931    1.0
932    1.0
933    1.0
934    1.0
935    1.0
936    1.0
937    1.0
Name: nyn_sku, dtype: float64
930    0.780488
931    0.780488
932    0.780488
933    1.170732
934    1.170732
935    0.975610
936    1.170732
937    1.170732
Name: atm_sku, dtype: float64
930    1.217391
931    1.217391
932    1.217391
933    0.869565
934    0.869565
935    0.869565
936    0.869565
937    0.869565
Name: msj_sku, dtype: float64
930   NaN
931   NaN
932   NaN
933   NaN
934   NaN
935   NaN
936   NaN
937   NaN
Name: fh_sku, dtype: float64
938    1.058824
939    0.941176
Name: mzc_sku, dtype: float64
938    0.545455
939    1.454545
Name: yp_sku, dtype: float64
938    0.666667
939    1.333333
Name: hs_sku, dtype: float64
938   NaN
939   NaN
Name: nyn_sku, dtype: float64
938   NaN
939   NaN
Name: atm_sku, dtype: float64
938    0.857143
939    1.142857
Name: msj_sku, dtype: float64
938   NaN
939   NaN
Name: fh_sku, dtype: float64
940    0.965517
941    1.086207
942    0.965517
943    1.086207
944    0.965517
945    0.965517
946    0.965517
Name: mzc_sku, dtype: float64
940    0.965517
941    1.206897
942    0.965517
943    0.965517
944    0.965517
945    0.965517
946    0.965517
Name: yp_sku, dtype: float64
940    1.0
941    1.5
942    1.0
943    0.5
944    1.0
945    1.0
946    1.0
Name: hs_sku, dtype: float64
940    0.965517
941    0.965517
942    0.965517
943    1.206897
944    0.965517
945    0.965517
946    0.965517
Name: nyn_sku, dtype: float64
940    1.0
941    1.0
942    1.0
943    1.0
944    1.0
945    1.0
946    1.0
Name: atm_sku, dtype: float64
940    0.942308
941    1.346154
942    0.942308
943    0.942308
944    0.942308
945    0.942308
946    0.942308
Name: msj_sku, dtype: float64
940   NaN
941   NaN
942   NaN
943   NaN
944   NaN
945   NaN
946   NaN
Name: fh_sku, dtype: float64
947    0.859259
948    1.118519
949    1.029630
950    0.985185
951    0.948148
952    1.022222
953    1.037037
Name: mzc_sku, dtype: float64
947    0.964072
948    1.089820
949    0.880240
950    0.964072
951    1.089820
952    1.005988
953    1.005988
Name: yp_sku, dtype: float64
947    1.129032
948    1.149560
949    1.087977
950    0.903226
951    1.067449
952    0.636364
953    1.026393
Name: hs_sku, dtype: float64
947   NaN
948   NaN
949   NaN
950   NaN
951   NaN
952   NaN
953   NaN
Name: nyn_sku, dtype: float64
947   NaN
948   NaN
949   NaN
950   NaN
951   NaN
952   NaN
953   NaN
Name: atm_sku, dtype: float64
947   NaN
948   NaN
949   NaN
950   NaN
951   NaN
952   NaN
953   NaN
Name: msj_sku, dtype: float64
947   NaN
948   NaN
949   NaN
950   NaN
951   NaN
952   NaN
953   NaN
Name: fh_sku, dtype: float64
954    0.937198
955    0.956522
956    0.937198
957    1.024155
958    0.995169
959    1.072464
960    1.053140
961    1.062802
962    0.985507
963    0.975845
Name: mzc_sku, dtype: float64
954    1.048137
955    1.063665
956    1.001553
957    1.009317
958    1.009317
959    0.947205
960    1.009317
961    1.055901
962    0.923913
963    0.931677
Name: yp_sku, dtype: float64
954    1.140279
955    1.074651
956    1.099262
957    1.058244
958    1.017227
959    0.976210
960    0.926989
961    0.910582
962    0.926989
963    0.869565
Name: hs_sku, dtype: float64
954    1.114983
955    1.080139
956    1.149826
957    0.975610
958    1.149826
959    0.278746
960    0.801394
961    0.801394
962    1.358885
963    1.289199
Name: nyn_sku, dtype: float64
954    1.018349
955    1.027523
956    1.027523
957    1.018349
958    1.027523
959    0.990826
960    1.110092
961    1.082569
962    0.889908
963    0.807339
Name: atm_sku, dtype: float64
954    0.987461
955    1.018809
956    1.057994
957    1.034483
958    1.065831
959    1.034483
960    0.956113
961    1.010972
962    0.940439
963    0.893417
Name: msj_sku, dtype: float64
954   NaN
955   NaN
956   NaN
957   NaN
958   NaN
959   NaN
960   NaN
961   NaN
962   NaN
963   NaN
Name: fh_sku, dtype: float64
964    1.123471
965    1.067853
966    1.090100
967    1.034483
968    0.378198
969    1.034483
970    1.023359
971    1.156841
972    1.134594
973    0.956618
Name: mzc_sku, dtype: float64
964    5.797872
965    0.000000
966    0.000000
967    4.042553
968    0.159574
969    0.000000
970    0.000000
971    0.000000
972    0.000000
973    0.000000
Name: yp_sku, dtype: float64
964    4.551282
965    0.000000
966    0.000000
967    5.384615
968    0.064103
969    0.000000
970    0.000000
971    0.000000
972    0.000000
973    0.000000
Name: hs_sku, dtype: float64
964    4.473684
965    0.000000
966    0.000000
967    5.263158
968    0.263158
969    0.000000
970    0.000000
971    0.000000
972    0.000000
973    0.000000
Name: nyn_sku, dtype: float64
964    5.208333
965    0.000000
966    0.000000
967    4.583333
968    0.208333
969    0.000000
970    0.000000
971    0.000000
972    0.000000
973    0.000000
Name: atm_sku, dtype: float64
964    1.218391
965    1.126437
966    1.126437
967    1.195402
968    0.045977
969    1.103448
970    0.988506
971    1.011494
972    1.149425
973    1.034483
Name: msj_sku, dtype: float64
964     0.0
965     0.0
966     0.0
967     0.0
968    10.0
969     0.0
970     0.0
971     0.0
972     0.0
973     0.0
Name: fh_sku, dtype: float64
974    1.642458
975    1.798883
976    0.821229
977    0.782123
978    0.586592
979    0.508380
980    0.860335
Name: mzc_sku, dtype: float64
974    2.843750
975    3.354167
976    0.072917
977    0.145833
978    0.291667
979    0.145833
980    0.145833
Name: yp_sku, dtype: float64
974    3.167883
975    3.423358
976    0.000000
977    0.255474
978    0.051095
979    0.051095
980    0.051095
Name: hs_sku, dtype: float64
974    1.140741
975    1.555556
976    0.829630
977    0.933333
978    0.829630
979    1.037037
980    0.674074
Name: nyn_sku, dtype: float64
974    0.563218
975    0.925287
976    0.965517
977    1.448276
978    1.086207
979    1.126437
980    0.885057
Name: atm_sku, dtype: float64
974    3.224719
975    3.303371
976    0.078652
977    0.157303
978    0.078652
979    0.078652
980    0.078652
Name: msj_sku, dtype: float64
974    3.698113
975    3.301887
976    0.000000
977    0.000000
978    0.000000
979    0.000000
980    0.000000
Name: fh_sku, dtype: float64
981    1.084507
982    0.985915
983    0.920188
984    0.953052
985    1.018779
986    1.018779
987    1.018779
Name: mzc_sku, dtype: float64
981    0.875
982    0.875
983    0.980
984    1.050
985    1.085
986    1.085
987    1.050
Name: yp_sku, dtype: float64
981    0.947368
982    0.868421
983    0.921053
984    1.078947
985    1.052632
986    1.078947
987    1.052632
Name: hs_sku, dtype: float64
981    1.0
982    1.0
983    1.0
984    1.0
985    1.0
986    1.0
987    1.0
Name: nyn_sku, dtype: float64
981    0.720588
982    1.029412
983    1.029412
984    1.029412
985    1.029412
986    1.080882
987    1.080882
Name: atm_sku, dtype: float64
981    1.038710
982    1.083871
983    1.038710
984    0.903226
985    0.993548
986    0.993548
987    0.948387
Name: msj_sku, dtype: float64
981   NaN
982   NaN
983   NaN
984   NaN
985   NaN
986   NaN
987   NaN
Name: fh_sku, dtype: float64
988    1.102564
989    0.948718
990    1.051282
991    0.897436
Name: mzc_sku, dtype: float64
988   NaN
989   NaN
990   NaN
991   NaN
Name: yp_sku, dtype: float64
988    2.0
989    0.0
990    2.0
991    0.0
Name: hs_sku, dtype: float64
988   NaN
989   NaN
990   NaN
991   NaN
Name: nyn_sku, dtype: float64
988   NaN
989   NaN
990   NaN
991   NaN
Name: atm_sku, dtype: float64
988   NaN
989   NaN
990   NaN
991   NaN
Name: msj_sku, dtype: float64
988   NaN
989   NaN
990   NaN
991   NaN
Name: fh_sku, dtype: float64
992    1.000
993    1.000
994    1.250
995    1.000
996    0.875
997    0.875
998    1.000
999    1.000
Name: mzc_sku, dtype: float64
992    1.0
993    1.0
994    1.0
995    1.0
996    1.0
997    1.0
998    1.0
999    1.0
Name: yp_sku, dtype: float64
992    1.185185
993    0.888889
994    0.888889
995    1.185185
996    0.888889
997    1.185185
998    1.185185
999    0.592593
Name: hs_sku, dtype: float64
992    0.969697
993    0.969697
994    1.212121
995    0.969697
996    0.969697
997    0.969697
998    0.969697
999    0.969697
Name: nyn_sku, dtype: float64
992    0.969697
993    1.212121
994    0.969697
995    0.969697
996    0.969697
997    0.969697
998    0.969697
999    0.969697
Name: atm_sku, dtype: float64
992    1.191489
993    1.191489
994    0.851064
995    0.851064
996    1.191489
997    0.851064
998    1.021277
999    0.851064
Name: msj_sku, dtype: float64
992   NaN
993   NaN
994   NaN
995   NaN
996   NaN
997   NaN
998   NaN
999   NaN
Name: fh_sku, dtype: float64
1000    1.121212
1001    1.151515
1002    0.666667
1003    1.060606
Name: mzc_sku, dtype: float64
1000    0.0
1001    0.0
1002    0.0
1003    4.0
Name: yp_sku, dtype: float64
1000    0.682927
1001    1.073171
1002    1.560976
1003    0.682927
Name: hs_sku, dtype: float64
1000   NaN
1001   NaN
1002   NaN
1003   NaN
Name: nyn_sku, dtype: float64
1000   NaN
1001   NaN
1002   NaN
1003   NaN
Name: atm_sku, dtype: float64
1000    0.0
1001    0.0
1002    0.0
1003    4.0
Name: msj_sku, dtype: float64
1000    0.0
1001    0.0
1002    0.0
1003    4.0
Name: fh_sku, dtype: float64
1004    0.873563
1005    0.724138
1006    1.229885
1007    1.068966
1008    1.126437
1009    0.977011
Name: mzc_sku, dtype: float64
1004    1.019305
1005    0.764479
1006    1.111969
1007    1.158301
1008    0.880309
1009    1.065637
Name: yp_sku, dtype: float64
1004    1.038869
1005    1.038869
1006    0.932862
1007    1.102473
1008    0.932862
1009    0.954064
Name: hs_sku, dtype: float64
1004    1.217391
1005    1.304348
1006    1.391304
1007    0.869565
1008    1.217391
1009    0.000000
Name: nyn_sku, dtype: float64
1004    1.066667
1005    1.200000
1006    1.200000
1007    2.000000
1008    0.533333
1009    0.000000
Name: atm_sku, dtype: float64
1004    0.865116
1005    0.865116
1006    1.060465
1007    0.948837
1008    1.200000
1009    1.060465
Name: msj_sku, dtype: float64
1004   NaN
1005   NaN
1006   NaN
1007   NaN
1008   NaN
1009   NaN
Name: fh_sku, dtype: float64
1010    1.0
Name: mzc_sku, dtype: float64
1010    1.0
Name: yp_sku, dtype: float64
1010    1.0
Name: hs_sku, dtype: float64
1010    1.0
Name: nyn_sku, dtype: float64
1010    1.0
Name: atm_sku, dtype: float64
1010    1.0
Name: msj_sku, dtype: float64
1010    1.0
Name: fh_sku, dtype: float64
1011    1.0
Name: mzc_sku, dtype: float64
1011    1.0
Name: yp_sku, dtype: float64
1011    1.0
Name: hs_sku, dtype: float64
1011    1.0
Name: nyn_sku, dtype: float64
1011    1.0
Name: atm_sku, dtype: float64
1011    1.0
Name: msj_sku, dtype: float64
1011   NaN
Name: fh_sku, dtype: float64
1012    1.247379
1013    1.289308
1014    1.320755
1015    0.953878
1016    0.974843
1017    0.870021
1018    0.817610
1019    0.828092
1020    0.901468
1021    0.796646
Name: mzc_sku, dtype: float64
1012    3.728814
1013    2.570621
1014    3.672316
1015    0.000000
1016    0.000000
1017    0.000000
1018    0.028249
1019    0.000000
1020    0.000000
1021    0.000000
Name: yp_sku, dtype: float64
1012    1.011364
1013    1.147727
1014    1.056818
1015    0.681818
1016    1.068182
1017    0.977273
1018    1.034091
1019    1.011364
1020    1.102273
1021    0.909091
Name: hs_sku, dtype: float64
1012   NaN
1013   NaN
1014   NaN
1015   NaN
1016   NaN
1017   NaN
1018   NaN
1019   NaN
1020   NaN
1021   NaN
Name: nyn_sku, dtype: float64
1012     0.0
1013     0.0
1014    10.0
1015     0.0
1016     0.0
1017     0.0
1018     0.0
1019     0.0
1020     0.0
1021     0.0
Name: atm_sku, dtype: float64
1012    5.0
1013    5.0
1014    0.0
1015    0.0
1016    0.0
1017    0.0
1018    0.0
1019    0.0
1020    0.0
1021    0.0
Name: msj_sku, dtype: float64
1012    0.0
1013    5.0
1014    0.0
1015    0.0
1016    0.0
1017    0.0
1018    0.0
1019    5.0
1020    0.0
1021    0.0
Name: fh_sku, dtype: float64
1022    1.279736
1023    0.878855
1024    0.647577
1025    0.585903
1026    1.110132
1027    0.770925
1028    1.726872
Name: mzc_sku, dtype: float64
1022    2.535433
1023    0.220472
1024    0.661417
1025    0.275591
1026    1.157480
1027    0.110236
1028    2.039370
Name: yp_sku, dtype: float64
1022    1.126437
1023    0.885057
1024    0.777778
1025    0.750958
1026    1.153257
1027    1.045977
1028    1.260536
Name: hs_sku, dtype: float64
1022    2.676471
1023    0.000000
1024    0.411765
1025    0.000000
1026    3.088235
1027    0.000000
1028    0.823529
Name: nyn_sku, dtype: float64
1022    2.7
1023    0.0
1024    0.4
1025    0.0
1026    3.2
1027    0.0
1028    0.7
Name: atm_sku, dtype: float64
1022    2.461538
1023    0.076923
1024    0.692308
1025    0.307692
1026    1.846154
1027    0.000000
1028    1.615385
Name: msj_sku, dtype: float64
1022    0.0
1023    0.0
1024    0.0
1025    0.0
1026    7.0
1027    0.0
1028    0.0
Name: fh_sku, dtype: float64
1029    0.980861
1030    0.861244
1031    0.956938
1032    1.028708
1033    1.172249
Name: mzc_sku, dtype: float64
1029    0.913978
1030    0.994624
1031    0.940860
1032    1.075269
1033    1.075269
Name: yp_sku, dtype: float64
1029    1.063830
1030    1.010638
1031    0.904255
1032    1.063830
1033    0.957447
Name: hs_sku, dtype: float64
1029   NaN
1030   NaN
1031   NaN
1032   NaN
1033   NaN
Name: nyn_sku, dtype: float64
1029   NaN
1030   NaN
1031   NaN
1032   NaN
1033   NaN
Name: atm_sku, dtype: float64
1029   NaN
1030   NaN
1031   NaN
1032   NaN
1033   NaN
Name: msj_sku, dtype: float64
1029   NaN
1030   NaN
1031   NaN
1032   NaN
1033   NaN
Name: fh_sku, dtype: float64
1034    2.492308
1035    0.553846
1036    0.830769
1037    1.038462
1038    1.038462
1039    0.969231
1040    0.069231
1041    1.038462
1042    0.969231
Name: mzc_sku, dtype: float64
1034    1.928571
1035    1.928571
1036    1.285714
1037    0.642857
1038    0.642857
1039    0.642857
1040    0.642857
1041    0.642857
1042    0.642857
Name: yp_sku, dtype: float64
1034    1.08
1035    1.08
1036    1.08
1037    1.08
1038    1.08
1039    1.08
1040    0.36
1041    1.08
1042    1.08
Name: hs_sku, dtype: float64
1034    1.058824
1035    1.058824
1036    1.058824
1037    1.058824
1038    0.794118
1039    1.058824
1040    1.058824
1041    0.794118
1042    1.058824
Name: nyn_sku, dtype: float64
1034    1.022727
1035    0.818182
1036    1.022727
1037    1.022727
1038    1.022727
1039    1.022727
1040    1.022727
1041    1.022727
1042    1.022727
Name: atm_sku, dtype: float64
1034    4.064516
1035    0.870968
1036    1.016129
1037    0.435484
1038    0.580645
1039    0.580645
1040    0.435484
1041    0.580645
1042    0.435484
Name: msj_sku, dtype: float64
1034   NaN
1035   NaN
1036   NaN
1037   NaN
1038   NaN
1039   NaN
1040   NaN
1041   NaN
1042   NaN
Name: fh_sku, dtype: float64
1043    1.200730
1044    0.715328
1045    1.251825
1046    1.098540
1047    1.405109
1048    1.200730
1049    0.127737
Name: mzc_sku, dtype: float64
1043    0.0
1044    0.0
1045    0.0
1046    7.0
1047    0.0
1048    0.0
1049    0.0
Name: yp_sku, dtype: float64
1043    2.264706
1044    0.205882
1045    4.323529
1046    0.205882
1047    0.000000
1048    0.000000
1049    0.000000
Name: hs_sku, dtype: float64
1043    0.0
1044    1.0
1045    0.0
1046    6.0
1047    0.0
1048    0.0
1049    0.0
Name: nyn_sku, dtype: float64
1043    0.0
1044    0.0
1045    0.0
1046    7.0
1047    0.0
1048    0.0
1049    0.0
Name: atm_sku, dtype: float64
1043    0.304348
1044    0.000000
1045    0.000000
1046    3.347826
1047    0.000000
1048    3.347826
1049    0.000000
Name: msj_sku, dtype: float64
1043    0.0
1044    7.0
1045    0.0
1046    0.0
1047    0.0
1048    0.0
1049    0.0
Name: fh_sku, dtype: float64
1050    0.997738
1051    1.045249
1052    1.029412
1053    0.950226
1054    1.061086
1055    0.902715
1056    1.013575
Name: mzc_sku, dtype: float64
1050    0.0
1051    0.0
1052    0.0
1053    0.0
1054    7.0
1055    0.0
1056    0.0
Name: yp_sku, dtype: float64
1050    1.172093
1051    1.188372
1052    1.025581
1053    0.927907
1054    1.009302
1055    0.846512
1056    0.830233
Name: hs_sku, dtype: float64
1050   NaN
1051   NaN
1052   NaN
1053   NaN
1054   NaN
1055   NaN
1056   NaN
Name: nyn_sku, dtype: float64
1050   NaN
1051   NaN
1052   NaN
1053   NaN
1054   NaN
1055   NaN
1056   NaN
Name: atm_sku, dtype: float64
1050    7.0
1051    0.0
1052    0.0
1053    0.0
1054    0.0
1055    0.0
1056    0.0
Name: msj_sku, dtype: float64
1050    0.0
1051    0.0
1052    0.0
1053    0.0
1054    0.0
1055    0.0
1056    7.0
Name: fh_sku, dtype: float64
1057    1.096386
1058    0.975904
1059    1.096386
1060    1.156627
1061    1.156627
1062    0.686747
1063    0.831325
Name: mzc_sku, dtype: float64
1057    1.314554
1058    0.805164
1059    1.100939
1060    1.133803
1061    1.347418
1062    1.068075
1063    0.230047
Name: yp_sku, dtype: float64
1057    1.282869
1058    0.780876
1059    1.157371
1060    1.031873
1061    1.143426
1062    0.697211
1063    0.906375
Name: hs_sku, dtype: float64
1057    1.798165
1058    1.990826
1059    0.513761
1060    0.449541
1061    1.990826
1062    0.000000
1063    0.256881
Name: nyn_sku, dtype: float64
1057    0.978495
1058    0.250896
1059    1.003584
1060    1.028674
1061    0.953405
1062    1.430108
1063    1.354839
Name: atm_sku, dtype: float64
1057    0.330909
1058    0.687273
1059    1.272727
1060    1.400000
1061    1.272727
1062    1.272727
1063    0.763636
Name: msj_sku, dtype: float64
1057    4.666667
1058    0.000000
1059    0.000000
1060    2.333333
1061    0.000000
1062    0.000000
1063    0.000000

Name: fh_sku, dtype: float64
1064    1.315068
1065    1.135741
1066    0.567870
1067    0.577833
1068    1.036115
1069    0.966376
1070    1.165629
1071    1.235367
Name: mzc_sku, dtype: float64
1064    8.0
1065    0.0
1066    0.0
1067    0.0
1068    0.0
1069    0.0
1070    0.0
1071    0.0
Name: yp_sku, dtype: float64
1064    0.090177
1065    0.000000
1066    1.198068
1067    2.009662
1068    1.133655
1069    1.301127
1070    1.133655
1071    1.133655
Name: hs_sku, dtype: float64
1064    1.090909
1065    0.909091
1066    1.272727
1067    1.090909
1068    1.636364
1069    1.272727
1070    0.000000
1071    0.727273
Name: nyn_sku, dtype: float64
1064    0.939597
1065    1.181208
1066    0.966443
1067    0.993289
1068    1.100671
1069    1.288591
1070    0.000000
1071    1.530201
Name: atm_sku, dtype: float64
1064    1.157025
1065    1.553719
1066    0.099174
1067    0.000000
1068    1.388430
1069    1.223140
1070    1.322314
1071    1.256198
Name: msj_sku, dtype: float64
1064    8.0
1065    0.0
1066    0.0
1067    0.0
1068    0.0
1069    0.0
1070    0.0
1071    0.0
Name: fh_sku, dtype: float64
1072    0.307692
1073    0.846154
1074    1.846154
Name: mzc_sku, dtype: float64
1072    0.000000
1073    0.666667
1074    2.333333
Name: yp_sku, dtype: float64
1072    0.0
1073    0.0
1074    3.0
Name: hs_sku, dtype: float64
1072    0.0
1073    0.0
1074    3.0
Name: nyn_sku, dtype: float64
1072    0.0
1073    0.0
1074    3.0
Name: atm_sku, dtype: float64
1072    0.0
1073    3.0
1074    0.0
Name: msj_sku, dtype: float64
1072    0.0
1073    0.0
1074    3.0
Name: fh_sku, dtype: float64
1075    0.939024
1076    0.939024
1077    1.006098
1078    1.039634
1079    1.039634
1080    0.905488
1081    0.972561
1082    0.972561
1083    1.039634
1084    1.073171
1085    1.073171
Name: mzc_sku, dtype: float64
1075     0.0
1076     0.0
1077     0.0
1078    11.0
1079     0.0
1080     0.0
1081     0.0
1082     0.0
1083     0.0
1084     0.0
1085     0.0
Name: yp_sku, dtype: float64
1075     0.0
1076    11.0
1077     0.0
1078     0.0
1079     0.0
1080     0.0
1081     0.0
1082     0.0
1083     0.0
1084     0.0
1085     0.0
Name: hs_sku, dtype: float64
1075    0.578947
1076    1.447368
1077    0.868421
1078    1.447368
1079    2.894737
1080    2.605263
1081    0.289474
1082    0.289474
1083    0.289474
1084    0.289474
1085    0.000000
Name: nyn_sku, dtype: float64
1075    4.888889
1076    2.444444
1077    3.666667
1078    0.000000
1079    0.000000
1080    0.000000
1081    0.000000
1082    0.000000
1083    0.000000
1084    0.000000
1085    0.000000
Name: atm_sku, dtype: float64
1075    0.655629
1076    0.546358
1077    1.347682
1078    1.639073
1079    1.347682
1080    0.655629
1081    0.801325
1082    1.238411
1083    0.764901
1084    0.983444
1085    1.019868
Name: msj_sku, dtype: float64
1075    0.636194
1076    0.554104
1077    0.861940
1078    1.149254
1079    1.190299
1080    0.800373
1081    0.677239
1082    1.272388
1083    1.436567
1084    1.477612
1085    0.944030
Name: fh_sku, dtype: float64
1086    1.026634
1087    0.561743
1088    0.794189
1089    1.142857
1090    0.697337
1091    0.736077
1092    1.336562
1093    1.704600
Name: mzc_sku, dtype: float64
1086    0.605042
1087    0.739496
1088    0.873950
1089    0.773109
1090    1.042017
1091    1.277311
1092    1.142857
1093    1.546218
Name: yp_sku, dtype: float64
1086    1.350844
1087    0.930582
1088    1.606004
1089    1.200750
1090    0.795497
1091    0.750469
1092    0.630394
1093    0.735460
Name: hs_sku, dtype: float64
1086    1.25
1087    1.50
1088    3.00
1089    1.75
1090    0.50
1091    0.00
1092    0.00
1093    0.00
Name: nyn_sku, dtype: float64
1086    4.571429
1087    3.428571
1088    0.000000
1089    0.000000
1090    0.000000
1091    0.000000
1092    0.000000
1093    0.000000
Name: atm_sku, dtype: float64
1086    2.366197
1087    3.267606
1088    0.000000
1089    0.000000
1090    0.000000
1091    0.000000
1092    1.352113
1093    1.014085
Name: msj_sku, dtype: float64
1086    0.964981
1087    0.591440
1088    0.933852
1089    0.840467
1090    1.276265
1091    1.214008
1092    1.058366
1093    1.120623
Name: fh_sku, dtype: float64
1094    0.709677
1095    0.903226
1096    1.354839
1097    1.032258
Name: mzc_sku, dtype: float64
1094    1.118280
1095    1.333333
1096    0.860215
1097    0.688172
Name: yp_sku, dtype: float64
1094    0.314607
1095    1.797753
1096    0.988764
1097    0.898876
Name: hs_sku, dtype: float64
1094    0.705882
1095    0.862745
1096    1.176471
1097    1.254902
Name: nyn_sku, dtype: float64
1094    1.188119
1095    0.990099
1096    0.950495
1097    0.871287
Name: atm_sku, dtype: float64
1094    1.288136
1095    1.084746
1096    1.288136
1097    0.338983
Name: msj_sku, dtype: float64
1094    1.878261
1095    0.521739
1096    0.591304
1097    1.008696
Name: fh_sku, dtype: float64
1098    1.283019
1099    0.905660
1100    1.433962
1101    0.905660
1102    0.905660
1103    0.905660
1104    0.830189
1105    0.830189
Name: mzc_sku, dtype: float64
1098    0.000000
1099    1.056604
1100    1.358491
1101    1.207547
1102    0.905660
1103    1.056604
1104    1.207547
1105    1.207547
Name: yp_sku, dtype: float64
1098    1.237113
1099    1.278351
1100    1.319588
1101    0.824742
1102    1.030928
1103    0.948454
1104    0.618557
1105    0.742268
Name: hs_sku, dtype: float64
1098    0.888889
1099    0.888889
1100    0.296296
1101    1.333333
1102    1.333333
1103    1.481481
1104    0.888889
1105    0.888889
Name: nyn_sku, dtype: float64
1098    1.007407
1099    0.888889
1100    0.888889
1101    0.829630
1102    1.125926
1103    0.888889
1104    1.244444
1105    1.125926
Name: atm_sku, dtype: float64
1098    1.168539
1099    1.078652
1100    1.078652
1101    0.808989
1102    0.988764
1103    0.898876
1104    0.988764
1105    0.988764
Name: msj_sku, dtype: float64
1098    1.263158
1099    3.368421
1100    3.368421
1101    0.000000
1102    0.000000
1103    0.000000
1104    0.000000
1105    0.000000
Name: fh_sku, dtype: float64
1106    1.057143
1107    1.171429
1108    0.942857
1109    1.000000
1110    0.828571
Name: mzc_sku, dtype: float64
1106    2.460317
1107    0.873016
1108    0.634921
1109    0.714286
1110    0.317460
Name: yp_sku, dtype: float64
1106    1.45
1107    1.10
1108    0.95
1109    1.00
1110    0.50
Name: hs_sku, dtype: float64
1106    1.568627
1107    0.718954
1108    0.816993
1109    1.045752
1110    0.849673
Name: nyn_sku, dtype: float64
1106    1.722689
1107    0.630252
1108    0.882353
1109    0.924370
1110    0.840336
Name: atm_sku, dtype: float64
1106    0.618557
1107    1.649485
1108    1.082474
1109    0.927835
1110    0.721649
Name: msj_sku, dtype: float64
1106    0.084746
1107    0.508475
1108    0.000000
1109    2.203390
1110    2.203390
Name: fh_sku, dtype: float64
1111    0.988235
1112    1.005882
1113    0.988235
1114    1.023529
1115    1.023529
1116    0.970588
Name: mzc_sku, dtype: float64
1111    1.037736
1112    1.132075
1113    1.113208
1114    0.905660
1115    0.905660
1116    0.905660
Name: yp_sku, dtype: float64
1111    0.969231
1112    1.084615
1113    1.061538
1114    1.038462
1115    0.923077
1116    0.923077
Name: hs_sku, dtype: float64
1111    1.071429
1112    0.857143
1113    1.071429
1114    0.857143
1115    1.071429
1116    1.071429
Name: nyn_sku, dtype: float64
1111    0.814286
1112    0.942857
1113    1.071429
1114    1.028571
1115    1.071429
1116    1.071429
Name: atm_sku, dtype: float64
1111   NaN
1112   NaN
1113   NaN
1114   NaN
1115   NaN
1116   NaN
Name: msj_sku, dtype: float64
1111    0.0
1112    6.0
1113    0.0
1114    0.0
1115    0.0
1116    0.0
Name: fh_sku, dtype: float64
1117    1.0
Name: mzc_sku, dtype: float64
1117    1.0
Name: yp_sku, dtype: float64
1117    1.0
Name: hs_sku, dtype: float64
1117    1.0
Name: nyn_sku, dtype: float64
1117    1.0
Name: atm_sku, dtype: float64
1117    1.0
Name: msj_sku, dtype: float64
1117   NaN
Name: fh_sku, dtype: float64
1118    1.000000
1119    1.037037
1120    0.944444
1121    1.018519
Name: mzc_sku, dtype: float64
1118    0.823529
1119    0.764706
1120    0.647059
1121    1.764706
Name: yp_sku, dtype: float64
1118    0.968944
1119    1.080745
1120    0.906832
1121    1.043478
Name: hs_sku, dtype: float64
1118    1.018182
1119    1.745455
1120    0.218182
1121    1.018182
Name: nyn_sku, dtype: float64
1118    1.152542
1119    1.016949
1120    0.745763
1121    1.084746
Name: atm_sku, dtype: float64
1118    1.166667
1119    0.952381
1120    0.785714
1121    1.095238
Name: msj_sku, dtype: float64
1118    0.612613
1119    0.648649
1120    1.441441
1121    1.297297
Name: fh_sku, dtype: float64
1122    1.012658
1123    0.987342
Name: mzc_sku, dtype: float64
1122   NaN
1123   NaN
Name: yp_sku, dtype: float64
1122   NaN
1123   NaN
Name: hs_sku, dtype: float64
1122   NaN
1123   NaN
Name: nyn_sku, dtype: float64
1122   NaN
1123   NaN
Name: atm_sku, dtype: float64
1122   NaN
1123   NaN
Name: msj_sku, dtype: float64
1122   NaN
1123   NaN
Name: fh_sku, dtype: float64
1124    0.876440
1125    1.027225
1126    0.980105
1127    1.027225
1128    1.046073
1129    1.017801
1130    0.998953
1131    1.046073
1132    0.980105
Name: mzc_sku, dtype: float64
1124   NaN
1125   NaN
1126   NaN
1127   NaN
1128   NaN
1129   NaN
1130   NaN
1131   NaN
1132   NaN
Name: yp_sku, dtype: float64
1124    0.0
1125    0.0
1126    0.0
1127    0.0
1128    0.0
1129    0.0
1130    9.0
1131    0.0
1132    0.0
Name: hs_sku, dtype: float64
1124   NaN
1125   NaN
1126   NaN
1127   NaN
1128   NaN
1129   NaN
1130   NaN
1131   NaN
1132   NaN
Name: nyn_sku, dtype: float64
1124   NaN
1125   NaN
1126   NaN
1127   NaN
1128   NaN
1129   NaN
1130   NaN
1131   NaN
1132   NaN
Name: atm_sku, dtype: float64
1124    1.011236
1125    0.950562
1126    0.900000
1127    1.092135
1128    0.930337
1129    0.950562
1130    1.071910
1131    1.122472
1132    0.970787
Name: msj_sku, dtype: float64
1124   NaN
1125   NaN
1126   NaN
1127   NaN
1128   NaN
1129   NaN
1130   NaN
1131   NaN
1132   NaN
Name: fh_sku, dtype: float64
1133    0.671533
1134    1.284672
1135    0.496350
1136    1.547445
Name: mzc_sku, dtype: float64
1133    1.688889
1134    0.755556
1135    0.711111
1136    0.844444
Name: yp_sku, dtype: float64
1133    0.624204
1134    1.732484
1135    0.789809
1136    0.853503
Name: hs_sku, dtype: float64
1133    0.888889
1134    1.444444
1135    0.666667
1136    1.000000
Name: nyn_sku, dtype: float64
1133    0.574257
1134    1.564356
1135    0.891089
1136    0.970297
Name: atm_sku, dtype: float64
1133    1.045752
1134    0.993464
1135    0.862745
1136    1.098039
Name: msj_sku, dtype: float64
1133    0.834043
1134    1.395745
1135    0.902128
1136    0.868085
Name: fh_sku, dtype: float64
1137    0.857143
1138    1.142857
Name: mzc_sku, dtype: float64
1137    1.352941
1138    0.647059
Name: yp_sku, dtype: float64
1137    1.22973
1138    0.77027
Name: hs_sku, dtype: float64
1137   NaN
1138   NaN
Name: nyn_sku, dtype: float64
1137   NaN
1138   NaN
Name: atm_sku, dtype: float64
1137    1.5
1138    0.5
Name: msj_sku, dtype: float64
1137    1.375
1138    0.625
Name: fh_sku, dtype: float64
1139    0.785414
1140    0.605891
1141    1.447405
1142    0.964937
1143    0.605891
1144    1.043478
1145    1.469846
1146    1.077139
Name: mzc_sku, dtype: float64
1139    0.0
1140    0.0
1141    0.0
1142    0.0
1143    8.0
1144    0.0
1145    0.0
1146    0.0
Name: yp_sku, dtype: float64
1139    0.921875
1140    0.906250
1141    1.343750
1142    1.093750
1143    0.968750
1144    1.609375
1145    0.312500
1146    0.843750
Name: hs_sku, dtype: float64
1139    0.689655
1140    0.206897
1141    0.965517
1142    1.034483
1143    0.965517
1144    2.068966
1145    1.034483
1146    1.034483
Name: nyn_sku, dtype: float64
1139    0.000000
1140    0.000000
1141    1.034700
1142    1.236593
1143    1.337539
1144    2.195584
1145    1.009464
1146    1.186120
Name: atm_sku, dtype: float64
1139    1.397380
1140    0.000000
1141    1.467249
1142    1.082969
1143    1.397380
1144    0.000000
1145    1.152838
1146    1.502183
Name: msj_sku, dtype: float64
1139   NaN
1140   NaN
1141   NaN
1142   NaN
1143   NaN
1144   NaN
1145   NaN
1146   NaN
Name: fh_sku, dtype: float64
1147    0.952381
1148    0.888889
1149    1.206349
1150    0.952381
Name: mzc_sku, dtype: float64
1147    0.896
1148    0.800
1149    1.344
1150    0.960
Name: yp_sku, dtype: float64
1147    1.200000
1148    1.576471
1149    0.658824
1150    0.564706
Name: hs_sku, dtype: float64
1147    0.800000
1148    1.866667
1149    1.333333
1150    0.000000
Name: nyn_sku, dtype: float64
1147    1.571429
1148    1.428571
1149    1.000000
1150    0.000000
Name: atm_sku, dtype: float64
1147    1.076923
1148    1.153846
1149    1.461538
1150    0.307692
Name: msj_sku, dtype: float64
1147    0.971963
1148    1.158879
1149    1.121495
1150    0.747664
Name: fh_sku, dtype: float64
1151    0.785714
1152    1.142857
1153    1.071429
1154    1.000000
Name: mzc_sku, dtype: float64
1151    1.149425
1152    1.103448
1153    1.379310
1154    0.367816
Name: yp_sku, dtype: float64
1151    1.009009
1152    1.765766
1153    0.504505
1154    0.720721
Name: hs_sku, dtype: float64
1151    1.253731
1152    1.552239
1153    0.417910
1154    0.776119
Name: nyn_sku, dtype: float64
1151    0.901961
1152    1.333333
1153    0.784314
1154    0.980392
Name: atm_sku, dtype: float64
1151    0.552846
1152    1.170732
1153    0.845528
1154    1.430894
Name: msj_sku, dtype: float64
1151    1.424242
1152    1.090909
1153    0.727273
1154    0.757576
Name: fh_sku, dtype: float64
1155    0.911765
1156    0.970588
1157    1.117647
Name: mzc_sku, dtype: float64
1155   NaN
1156   NaN
1157   NaN
Name: yp_sku, dtype: float64
1155    1.052632
1156    1.000000
1157    0.947368
Name: hs_sku, dtype: float64
1155   NaN
1156   NaN
1157   NaN
Name: nyn_sku, dtype: float64
1155   NaN
1156   NaN
1157   NaN
Name: atm_sku, dtype: float64
1155    3.0
1156    0.0
1157    0.0
Name: msj_sku, dtype: float64
1155    3.0
1156    0.0
1157    0.0
Name: fh_sku, dtype: float64
1158    1.212121
1159    0.878788
1160    0.909091
1161    1.030303
1162    1.090909
1163    0.969697
1164    0.909091
Name: mzc_sku, dtype: float64
1158    1.16
1159    1.16
1160    0.92
1161    1.00
1162    0.88
1163    1.08
1164    0.80
Name: yp_sku, dtype: float64
1158    1.25
1159    1.15
1160    0.90
1161    1.00
1162    0.65
1163    1.00
1164    1.05
Name: hs_sku, dtype: float64
1158    1.3125
1159    1.8750
1160    0.8750
1161    0.9375
1162    0.7500
1163    1.1250
1164    0.1250
Name: nyn_sku, dtype: float64
1158    1.000000
1159    1.142857
1160    0.904762
1161    1.047619
1162    1.142857
1163    1.190476
1164    0.571429
Name: atm_sku, dtype: float64
1158    0.929461
1159    1.336100
1160    0.784232
1161    0.842324
1162    1.307054
1163    1.016598
1164    0.784232
Name: msj_sku, dtype: float64
1158    1.147541
1159    1.032787
1160    1.032787
1161    1.032787
1162    0.879781
1163    0.956284
1164    0.918033
Name: fh_sku, dtype: float64
1165    1.208955
1166    1.074627
1167    1.074627
1168    0.402985
1169    1.074627
1170    1.074627
1171    1.074627
1172    0.940299
1173    1.074627
Name: mzc_sku, dtype: float64
1165    1.184211
1166    0.947368
1167    0.947368
1168    0.947368
1169    0.947368
1170    1.184211
1171    0.947368
1172    0.947368
1173    0.947368
Name: yp_sku, dtype: float64
1165    1.5
1166    1.0
1167    1.0
1168    0.5
1169    1.0
1170    1.0
1171    1.0
1172    1.0
1173    1.0
Name: hs_sku, dtype: float64
1165    1.028571
1166    1.028571
1167    1.028571
1168    1.028571
1169    1.028571
1170    0.771429
1171    1.028571
1172    1.028571
1173    1.028571
Name: nyn_sku, dtype: float64
1165    1.028571
1166    1.028571
1167    1.028571
1168    0.771429
1169    1.028571
1170    1.028571
1171    1.028571
1172    1.028571
1173    1.028571
Name: atm_sku, dtype: float64
1165    0.947368
1166    1.105263
1167    0.947368
1168    0.789474
1169    0.947368
1170    1.105263
1171    0.947368
1172    1.105263
1173    1.105263
Name: msj_sku, dtype: float64
1165   NaN
1166   NaN
1167   NaN
1168   NaN
1169   NaN
1170   NaN
1171   NaN
1172   NaN
1173   NaN
Name: fh_sku, dtype: float64
1174    1.247312
1175    0.903226
1176    0.860215
1177    0.989247
Name: mzc_sku, dtype: float64
1174    1.028571
1175    0.914286
1176    1.074286
1177    0.982857
Name: yp_sku, dtype: float64
1174    0.873563
1175    0.919540
1176    1.333333
1177    0.873563
Name: hs_sku, dtype: float64
1174    1.153846
1175    0.846154
1176    0.846154
1177    1.153846
Name: nyn_sku, dtype: float64
1174    1.090909
1175    0.818182
1176    1.000000
1177    1.090909
Name: atm_sku, dtype: float64
1174    1.000000
1175    0.888889
1176    1.074074
1177    1.037037
Name: msj_sku, dtype: float64
1174    1.125
1175    1.050
1176    1.050
1177    0.775
Name: fh_sku, dtype: float64
1178    1.0
Name: mzc_sku, dtype: float64
1178    1.0
Name: yp_sku, dtype: float64
1178    1.0
Name: hs_sku, dtype: float64
1178   NaN
Name: nyn_sku, dtype: float64
1178   NaN
Name: atm_sku, dtype: float64
1178    1.0
Name: msj_sku, dtype: float64
1178    1.0
Name: fh_sku, dtype: float64
1179    0.835894
1180    0.528580
1181    0.964966
1182    0.995698
1183    1.327597
1184    0.854333
1185    0.964966
1186    0.651506
1187    1.204671
1188    1.671789
Name: mzc_sku, dtype: float64
1179    1.067961
1180    0.000000
1181    2.135922
1182    1.165049
1183    0.000000
1184    5.533981
1185    0.097087
1186    0.000000
1187    0.000000
1188    0.000000
Name: yp_sku, dtype: float64
1179    1.278351
1180    1.237113
1181    1.278351
1182    1.278351
1183    1.319588
1184    1.278351
1185    0.041237
1186    1.113402
1187    1.154639
1188    0.020619
Name: hs_sku, dtype: float64
1179    0.000000
1180    0.000000
1181    0.000000
1182    0.689655
1183    1.310345
1184    1.655172
1185    1.586207
1186    1.448276
1187    1.655172
1188    1.655172
Name: nyn_sku, dtype: float64
1179    0.000000
1180    0.094787
1181    0.023697
1182    0.971564
1183    1.563981
1184    1.421801
1185    1.445498
1186    1.540284
1187    1.516588
1188    1.421801
Name: atm_sku, dtype: float64
1179    1.833333
1180    1.611111
1181    1.694444
1182    0.000000
1183    1.722222
1184    1.444444
1185    1.666667
1186    0.000000
1187    0.027778
1188    0.000000
Name: msj_sku, dtype: float64
1179    0.073529
1180    0.000000
1181    0.000000
1182    0.000000
1183    2.573529
1184    0.808824
1185    2.352941
1186    0.294118
1187    0.441176
1188    3.455882
Name: fh_sku, dtype: float64
1189    0.678571
1190    1.428571
1191    0.892857
Name: mzc_sku, dtype: float64
1189    0.00
1190    1.35
1191    1.65
Name: yp_sku, dtype: float64
1189    0.000
1190    1.725
1191    1.275
Name: hs_sku, dtype: float64
1189    0.666667
1190    1.333333
1191    1.000000
Name: nyn_sku, dtype: float64
1189    0.461538
1190    1.500000
1191    1.038462
Name: atm_sku, dtype: float64
1189    0.46875
1190    1.12500
1191    1.40625
Name: msj_sku, dtype: float64
1189    0.083799
1190    1.357542
1191    1.558659
Name: fh_sku, dtype: float64
1192    1.063830
1193    0.510638
1194    1.106383
1195    1.021277
1196    1.234043
1197    1.063830
Name: mzc_sku, dtype: float64
1192    0.0
1193    0.0
1194    0.0
1195    3.0
1196    3.0
1197    0.0
Name: yp_sku, dtype: float64
1192    1.0
1193    1.0
1194    1.5
1195    1.0
1196    1.0
1197    0.5
Name: hs_sku, dtype: float64
1192   NaN
1193   NaN
1194   NaN
1195   NaN
1196   NaN
1197   NaN
Name: nyn_sku, dtype: float64
1192    0.0
1193    6.0
1194    0.0
1195    0.0
1196    0.0
1197    0.0
Name: atm_sku, dtype: float64
1192   NaN
1193   NaN
1194   NaN
1195   NaN
1196   NaN
1197   NaN
Name: msj_sku, dtype: float64
1192    0.857143
1193    5.142857
1194    0.000000
1195    0.000000
1196    0.000000
1197    0.000000
Name: fh_sku, dtype: float64
1198    1.443038
1199    0.911392
1200    0.797468
1201    0.848101

Name: mzc_sku, dtype: float64
1198    3.428571
1199    0.190476
1200    0.190476
1201    0.190476
Name: yp_sku, dtype: float64
1198    1.379061
1199    0.924188
1200    0.859206
1201    0.837545
Name: hs_sku, dtype: float64
1198    4.0
1199    0.0
1200    0.0
1201    0.0
Name: nyn_sku, dtype: float64
1198    4.0
1199    0.0
1200    0.0
1201    0.0
Name: atm_sku, dtype: float64
1198    1.174825
1199    0.979021
1200    0.965035
1201    0.881119
Name: msj_sku, dtype: float64
1198    4.0
1199    0.0
1200    0.0
1201    0.0
Name: fh_sku, dtype: float64
1202    1.087420
1203    0.959488
1204    0.916844
1205    0.970149
1206    1.066098
Name: mzc_sku, dtype: float64
1202    1.25
1203    1.05
1204    1.10
1205    0.95
1206    0.65
Name: yp_sku, dtype: float64
1202    1.048544
1203    0.990291
1204    1.009709
1205    1.038835
1206    0.912621
Name: hs_sku, dtype: float64
1202    1.40625
1203    1.87500
1204    0.93750
1205    0.31250
1206    0.46875
Name: nyn_sku, dtype: float64
1202    1.833333
1203    2.166667
1204    0.833333
1205    0.166667
1206    0.000000
Name: atm_sku, dtype: float64
1202    0.913462
1203    0.961538
1204    0.889423
1205    1.033654
1206    1.201923
Name: msj_sku, dtype: float64
1202    5.0
1203    0.0
1204    0.0
1205    0.0
1206    0.0
Name: fh_sku, dtype: float64
1207    1.290323
1208    1.225806
1209    0.483871
Name: mzc_sku, dtype: float64
1207    1.03125
1208    1.18125
1209    0.78750
Name: yp_sku, dtype: float64
1207    0.000000
1208    1.636364
1209    1.363636
Name: hs_sku, dtype: float64
1207    0.631579
1208    1.500000
1209    0.868421
Name: nyn_sku, dtype: float64
1207    1.153846
1208    1.076923
1209    0.769231
Name: atm_sku, dtype: float64
1207    1.0
1208    1.6
1209    0.4
Name: msj_sku, dtype: float64
1207    0.851852
1208    1.333333
1209    0.814815
Name: fh_sku, dtype: float64
1210    1.043478
1211    1.043478
1212    0.913043
1213    0.956522
1214    0.956522
1215    0.956522
1216    1.000000
1217    1.130435
Name: mzc_sku, dtype: float64
1210   NaN
1211   NaN
1212   NaN
1213   NaN
1214   NaN
1215   NaN
1216   NaN
1217   NaN
Name: yp_sku, dtype: float64
1210    1.297297
1211    1.297297
1212    1.513514
1213    1.513514
1214    0.000000
1215    1.513514
1216    0.000000
1217    0.864865
Name: hs_sku, dtype: float64
1210   NaN
1211   NaN
1212   NaN
1213   NaN
1214   NaN
1215   NaN
1216   NaN
1217   NaN
Name: nyn_sku, dtype: float64
1210   NaN
1211   NaN
1212   NaN
1213   NaN
1214   NaN
1215   NaN
1216   NaN
1217   NaN
Name: atm_sku, dtype: float64
1210    0.000000
1211    1.379310
1212    1.931034
1213    0.000000
1214    0.000000
1215    1.931034
1216    1.379310
1217    1.379310
Name: msj_sku, dtype: float64
1210   NaN
1211   NaN
1212   NaN
1213   NaN
1214   NaN
1215   NaN
1216   NaN
1217   NaN
Name: fh_sku, dtype: float64
1218    1.012048
1219    1.060241
1220    1.060241
1221    0.867470
Name: mzc_sku, dtype: float64
1218    0.000000
1219    1.454545
1220    0.545455
1221    2.000000
Name: yp_sku, dtype: float64
1218    1.192982
1219    1.122807
1220    0.421053
1221    1.263158
Name: hs_sku, dtype: float64
1218    0.000000
1219    1.555556
1220    0.888889
1221    1.555556
Name: nyn_sku, dtype: float64
1218    0.000000
1219    1.538462
1220    1.153846
1221    1.307692
Name: atm_sku, dtype: float64
1218    1.185185
1219    1.148148
1220    0.888889
1221    0.777778
Name: msj_sku, dtype: float64
1218   NaN
1219   NaN
1220   NaN
1221   NaN
Name: fh_sku, dtype: float64
1222    1.72973
1223    0.27027
Name: mzc_sku, dtype: float64
1222    0.833333
1223    1.166667
Name: yp_sku, dtype: float64
1222    0.0
1223    2.0
Name: hs_sku, dtype: float64
1222   NaN
1223   NaN
Name: nyn_sku, dtype: float64
1222   NaN
1223   NaN
Name: atm_sku, dtype: float64
1222    0.0
1223    2.0
Name: msj_sku, dtype: float64
1222   NaN
1223   NaN
Name: fh_sku, dtype: float64
1224    1.142857
1225    1.028571
1226    1.142857
1227    1.142857
1228    0.914286
1229    0.800000
1230    0.914286
1231    0.914286
Name: mzc_sku, dtype: float64
1224    1.454545
1225    1.212121
1226    0.969697
1227    0.969697
1228    0.727273
1229    0.969697
1230    0.727273
1231    0.969697
Name: yp_sku, dtype: float64
1224    1.655172
1225    1.655172
1226    0.551724
1227    0.275862
1228    0.827586
1229    0.827586
1230    1.103448
1231    1.103448
Name: hs_sku, dtype: float64
1224    1.0
1225    1.0
1226    1.0
1227    1.0
1228    1.0
1229    1.0
1230    1.0
1231    1.0
Name: nyn_sku, dtype: float64
1224    1.00
1225    1.00
1226    0.75
1227    1.25
1228    1.00
1229    1.00
1230    1.00
1231    1.00
Name: atm_sku, dtype: float64
1224    1.309091
1225    1.163636
1226    0.872727
1227    0.872727
1228    0.872727
1229    0.872727
1230    1.018182
1231    1.018182
Name: msj_sku, dtype: float64
1224   NaN
1225   NaN
1226   NaN
1227   NaN
1228   NaN
1229   NaN
1230   NaN
1231   NaN
Name: fh_sku, dtype: float64
1232    1.005076
1233    1.116751
1234    1.025381
1235    0.852792
Name: mzc_sku, dtype: float64
1232    1.022026
1233    0.546256
1234    1.409692
1235    1.022026
Name: yp_sku, dtype: float64
1232    1.025126
1233    1.165829
1234    0.964824
1235    0.844221
Name: hs_sku, dtype: float64
1232    2.666667
1233    0.296296
1234    0.740741
1235    0.296296
Name: nyn_sku, dtype: float64
1232    1.443299
1233    0.618557
1234    1.092784
1235    0.845361
Name: atm_sku, dtype: float64
1232    1.174603
1233    0.253968
1234    1.333333
1235    1.238095
Name: msj_sku, dtype: float64
1232   NaN
1233   NaN
1234   NaN
1235   NaN
Name: fh_sku, dtype: float64
1236    1.237288
1237    0.881356
1238    0.898305
1239    0.983051
Name: mzc_sku, dtype: float64
1236    1.387755
1237    0.816327
1238    1.102041
1239    0.693878
Name: yp_sku, dtype: float64
1236    1.340909
1237    1.045455
1238    0.636364
1239    0.977273
Name: hs_sku, dtype: float64
1236    0.949153
1237    1.084746
1238    1.084746
1239    0.881356
Name: nyn_sku, dtype: float64
1236    1.026549
1237    0.955752
1238    1.026549
1239    0.991150
Name: atm_sku, dtype: float64
1236    0.913580
1237    1.012346
1238    1.111111
1239    0.962963
Name: msj_sku, dtype: float64
1236    1.224490
1237    0.979592
1238    0.870748
1239    0.925170
Name: fh_sku, dtype: float64
1240    1.025641
1241    0.974359
Name: mzc_sku, dtype: float64
1240    1.0
1241    1.0
Name: yp_sku, dtype: float64
1240   NaN
1241   NaN
Name: hs_sku, dtype: float64
1240    1.0
1241    1.0
Name: nyn_sku, dtype: float64
1240    2.0
1241    0.0
Name: atm_sku, dtype: float64
1240   NaN
1241   NaN
Name: msj_sku, dtype: float64
1240   NaN
1241   NaN
Name: fh_sku, dtype: float64
1242    1.074485
1243    1.045959
1244    0.903328
1245    0.998415
1246    0.969889
1247    1.007924
Name: mzc_sku, dtype: float64
1242    1.230469
1243    1.195312
1244    1.289062
1245    0.843750
1246    0.796875
1247    0.644531
Name: yp_sku, dtype: float64
1242    0.894977
1243    0.840183
1244    1.232877
1245    1.187215
1246    0.913242
1247    0.931507
Name: hs_sku, dtype: float64
1242    0.915254
1243    0.661017
1244    0.864407
1245    0.915254
1246    1.372881
1247    1.271186
Name: nyn_sku, dtype: float64
1242    0.680412
1243    0.742268
1244    0.659794
1245    1.298969
1246    1.340206
1247    1.278351
Name: atm_sku, dtype: float64
1242    0.564460
1243    0.940767
1244    0.878049
1245    1.191638
1246    1.212544
1247    1.212544
Name: msj_sku, dtype: float64
1242    0.000000
1243    0.000000
1244    0.061856
1245    1.731959
1246    1.917526
1247    2.288660
Name: fh_sku, dtype: float64
1248    1.0
Name: mzc_sku, dtype: float64
1248    1.0
Name: yp_sku, dtype: float64
1248    1.0
Name: hs_sku, dtype: float64
1248    1.0
Name: nyn_sku, dtype: float64
1248    1.0
Name: atm_sku, dtype: float64
1248    1.0
Name: msj_sku, dtype: float64
1248    1.0
Name: fh_sku, dtype: float64
1249    0.947368
1250    1.052632
Name: mzc_sku, dtype: float64
1249    0.5
1250    1.5
Name: yp_sku, dtype: float64
1249    1.188406
1250    0.811594
Name: hs_sku, dtype: float64
1249    1.5
1250    0.5
Name: nyn_sku, dtype: float64
1249    0.935484
1250    1.064516
Name: atm_sku, dtype: float64
1249    0.727273
1250    1.272727
Name: msj_sku, dtype: float64
1249    0.676056
1250    1.323944
Name: fh_sku, dtype: float64
1251    0.759494
1252    1.107595
1253    1.297468
1254    1.139241
1255    0.696203
Name: mzc_sku, dtype: float64
1251    0.000000
1252    0.731707
1253    1.219512
1254    1.707317
1255    1.341463
Name: yp_sku, dtype: float64
1251    0.0
1252    2.5
1253    0.0
1254    0.0
1255    2.5
Name: hs_sku, dtype: float64
1251   NaN
1252   NaN
1253   NaN
1254   NaN
1255   NaN
Name: nyn_sku, dtype: float64
1251    0.0
1252    0.0
1253    0.0
1254    0.0
1255    5.0
Name: atm_sku, dtype: float64
1251    0.0
1252    0.0
1253    0.0
1254    0.0
1255    5.0
Name: msj_sku, dtype: float64
1251    0.0
1252    2.5
1253    2.5
1254    0.0
1255    0.0
Name: fh_sku, dtype: float64
1256    1.071429
1257    0.928571
Name: mzc_sku, dtype: float64
1256    0.0
1257    2.0
Name: yp_sku, dtype: float64
1256    1.027027
1257    0.972973
Name: hs_sku, dtype: float64
1256   NaN
1257   NaN
Name: nyn_sku, dtype: float64
1256    1.333333
1257    0.666667
Name: atm_sku, dtype: float64
1256    0.444444
1257    1.555556
Name: msj_sku, dtype: float64
1256   NaN
1257   NaN
Name: fh_sku, dtype: float64
1258    0.656805
1259    1.260355
1260    1.242604
1261    1.295858
1262    0.816568
1263    0.727811
Name: mzc_sku, dtype: float64
1258    0.000000
1259    1.756098
1260    1.219512
1261    1.658537
1262    0.585366
1263    0.780488
Name: yp_sku, dtype: float64
1258    0.038961
1259    1.324675
1260    1.207792
1261    0.974026
1262    1.285714
1263    1.168831
Name: hs_sku, dtype: float64
1258    0.000000
1259    1.728814
1260    1.728814
1261    1.322034
1262    0.711864
1263    0.508475
Name: nyn_sku, dtype: float64
1258    0.000000
1259    1.469388
1260    1.183673
1261    0.938776
1262    1.265306
1263    1.142857
Name: atm_sku, dtype: float64
1258    0.000000
1259    0.829493
1260    1.354839
1261    1.741935
1262    0.967742
1263    1.105991
Name: msj_sku, dtype: float64
1258    0.638298
1259    1.340426
1260    1.059574
1261    1.123404
1262    1.059574
1263    0.778723
Name: fh_sku, dtype: float64
1264    0.974265
1265    0.992647
1266    0.974265
1267    0.974265
1268    1.084559
Name: mzc_sku, dtype: float64
1264    0.822785
1265    0.917722
1266    1.075949
1267    1.139241
1268    1.044304
Name: yp_sku, dtype: float64
1264    1.063830
1265    1.046099
1266    0.975177
1267    0.939716
1268    0.975177
Name: hs_sku, dtype: float64
1264    1.136364
1265    1.136364
1266    0.909091
1267    0.909091
1268    0.909091
Name: nyn_sku, dtype: float64
1264    1.136364
1265    1.136364
1266    0.909091
1267    0.909091
1268    0.909091
Name: atm_sku, dtype: float64
1264    1.046099
1265    1.046099
1266    1.028369
1267    0.851064
1268    1.028369
Name: msj_sku, dtype: float64
1264   NaN
1265   NaN
1266   NaN
1267   NaN
1268   NaN
Name: fh_sku, dtype: float64
1269    1.0
1270    1.0
Name: mzc_sku, dtype: float64
1269   NaN
1270   NaN
Name: yp_sku, dtype: float64
1269   NaN
1270   NaN
Name: hs_sku, dtype: float64
1269   NaN
1270   NaN
Name: nyn_sku, dtype: float64
1269   NaN
1270   NaN
Name: atm_sku, dtype: float64
1269   NaN
1270   NaN
Name: msj_sku, dtype: float64
1269   NaN
1270   NaN
Name: fh_sku, dtype: float64
1271    1.0
Name: mzc_sku, dtype: float64
1271   NaN
Name: yp_sku, dtype: float64
1271   NaN
Name: hs_sku, dtype: float64
1271   NaN
Name: nyn_sku, dtype: float64
1271   NaN
Name: atm_sku, dtype: float64
1271   NaN
Name: msj_sku, dtype: float64
1271    1.0
Name: fh_sku, dtype: float64
1272    0.785714
1273    0.928571
1274    1.071429
1275    1.214286
Name: mzc_sku, dtype: float64
1272    1.106383
1273    1.106383
1274    0.936170
1275    0.851064
Name: yp_sku, dtype: float64
1272    1.050847
1273    0.983051
1274    0.949153
1275    1.016949
Name: hs_sku, dtype: float64
1272    1.0
1273    1.0
1274    1.0
1275    1.0
Name: nyn_sku, dtype: float64
1272    1.1
1273    0.9
1274    0.9
1275    1.1
Name: atm_sku, dtype: float64
1272    0.923077
1273    1.000000
1274    1.000000
1275    1.076923
Name: msj_sku, dtype: float64
1272   NaN
1273   NaN
1274   NaN
1275   NaN
Name: fh_sku, dtype: float64
1276    0.832117
1277    1.160584
1278    1.007299
Name: mzc_sku, dtype: float64
1276    0.230769
1277    2.076923
1278    0.692308
Name: yp_sku, dtype: float64
1276    0.764706
1277    1.382353
1278    0.852941
Name: hs_sku, dtype: float64
1276    1.363636
1277    1.022727
1278    0.613636
Name: nyn_sku, dtype: float64
1276    1.052632
1277    1.210526
1278    0.736842
Name: atm_sku, dtype: float64
1276    1.235294
1277    1.176471
1278    0.588235
Name: msj_sku, dtype: float64
1276    0.592105
1277    1.184211
1278    1.223684
Name: fh_sku, dtype: float64
1279    1.358491
1280    0.641509
Name: mzc_sku, dtype: float64
1279    0.909091
1280    1.090909
Name: yp_sku, dtype: float64
1279    1.861111
1280    0.138889
Name: hs_sku, dtype: float64
1279    0.0
1280    2.0
Name: nyn_sku, dtype: float64
1279    0.0
1280    2.0
Name: atm_sku, dtype: float64
1279    0.0
1280    2.0
Name: msj_sku, dtype: float64
1279   NaN
1280   NaN
Name: fh_sku, dtype: float64
1281    1.194805
1282    0.805195
Name: mzc_sku, dtype: float64
1281    1.692308
1282    0.307692
Name: yp_sku, dtype: float64
1281    0.986486
1282    1.013514
Name: hs_sku, dtype: float64
1281    1.181818
1282    0.818182
Name: nyn_sku, dtype: float64
1281    1.434783
1282    0.565217
Name: atm_sku, dtype: float64
1281    0.9
1282    1.1
Name: msj_sku, dtype: float64
1281    1.061224
1282    0.938776
Name: fh_sku, dtype: float64
1283    1.236181
1284    0.733668
1285    1.427136
1286    0.723618
1287    0.904523
1288    0.974874
Name: mzc_sku, dtype: float64
1283    0.000000
1284    0.739726
1285    3.369863
1286    0.082192
1287    1.808219
1288    0.000000
Name: yp_sku, dtype: float64
1283    1.004237
1284    0.978814
1285    1.067797
1286    0.991525
1287    1.029661
1288    0.927966
Name: hs_sku, dtype: float64
1283    2.000000
1284    2.210526
1285    0.000000
1286    0.631579
1287    0.736842
1288    0.421053
Name: nyn_sku, dtype: float64
1283    1.526786
1284    1.366071
1285    0.053571
1286    1.098214
1287    0.937500
1288    1.017857
Name: atm_sku, dtype: float64
1283    0.0000
1284    0.0750
1285    0.0375
1286    2.5125
1287    1.7250
1288    1.6500
Name: msj_sku, dtype: float64
1283    0.00
1284    0.00
1285    0.00
1286    0.00
1287    5.76
1288    0.24
Name: fh_sku, dtype: float64
1289    0.802817
1290    1.647887
1291    0.549296
Name: mzc_sku, dtype: float64
1289    0.0
1290    3.0
1291    0.0
Name: yp_sku, dtype: float64
1289    1.736842
1290    1.263158
1291    0.000000
Name: hs_sku, dtype: float64
1289    3.0
1290    0.0
1291    0.0
Name: nyn_sku, dtype: float64
1289    3.0
1290    0.0
1291    0.0

Name: atm_sku, dtype: float64
1289    0.0
1290    3.0
1291    0.0
Name: msj_sku, dtype: float64
1289   NaN
1290   NaN
1291   NaN
Name: fh_sku, dtype: float64
1292    1.040248
1293    0.986068
1294    0.921053
1295    1.018576
1296    1.040248
1297    0.975232
1298    1.018576
Name: mzc_sku, dtype: float64
1292   NaN
1293   NaN
1294   NaN
1295   NaN
1296   NaN
1297   NaN
1298   NaN
Name: yp_sku, dtype: float64
1292    7.0
1293    0.0
1294    0.0
1295    0.0
1296    0.0
1297    0.0
1298    0.0
Name: hs_sku, dtype: float64
1292   NaN
1293   NaN
1294   NaN
1295   NaN
1296   NaN
1297   NaN
1298   NaN
Name: nyn_sku, dtype: float64
1292   NaN
1293   NaN
1294   NaN
1295   NaN
1296   NaN
1297   NaN
1298   NaN
Name: atm_sku, dtype: float64
1292    1.02
1293    1.08
1294    1.04
1295    0.98
1296    1.09
1297    0.81
1298    0.98
Name: msj_sku, dtype: float64
1292   NaN
1293   NaN
1294   NaN
1295   NaN
1296   NaN
1297   NaN
1298   NaN
Name: fh_sku, dtype: float64
1299    0.636364
1300    0.775841
1301    1.063512
1302    1.168120
1303    0.636364
1304    0.993773
1305    1.726027
Name: mzc_sku, dtype: float64
1299    0.0
1300    0.0
1301    7.0
1302    0.0
1303    0.0
1304    0.0
1305    0.0
Name: yp_sku, dtype: float64
1299    1.014679
1300    1.104587
1301    1.284404
1302    0.899083
1303    0.976147
1304    0.757798
1305    0.963303
Name: hs_sku, dtype: float64
1299    0.000000
1300    0.958333
1301    2.000000
1302    1.083333
1303    0.958333
1304    1.041667
1305    0.958333
Name: nyn_sku, dtype: float64
1299    0.000000
1300    0.794433
1301    1.663812
1302    1.229122
1303    1.109208
1304    1.259101
1305    0.944325
Name: atm_sku, dtype: float64
1299    1.394928
1300    0.760870
1301    1.242754
1302    1.090580
1303    1.394928
1304    0.000000
1305    1.115942
Name: msj_sku, dtype: float64
1299    0.000000
1300    4.666667
1301    0.000000
1302    0.000000
1303    0.000000
1304    2.333333
1305    0.000000
Name: fh_sku, dtype: float64
1306    0.90411
1307    1.09589
Name: mzc_sku, dtype: float64
1306    1.176471
1307    0.823529
Name: yp_sku, dtype: float64
1306    0.840909
1307    1.159091
Name: hs_sku, dtype: float64
1306    0.0
1307    2.0
Name: nyn_sku, dtype: float64
1306    0.628571
1307    1.371429
Name: atm_sku, dtype: float64
1306    0.0
1307    2.0
Name: msj_sku, dtype: float64
1306    1.265306
1307    0.734694
Name: fh_sku, dtype: float64
1308    0.8
1309    1.2
Name: mzc_sku, dtype: float64
1308    1.376147
1309    0.623853
Name: yp_sku, dtype: float64
1308    0.857143
1309    1.142857
Name: hs_sku, dtype: float64
1308    1.4
1309    0.6
Name: nyn_sku, dtype: float64
1308    2.0
1309    0.0
Name: atm_sku, dtype: float64
1308    0.777778
1309    1.222222
Name: msj_sku, dtype: float64
1308    0.916364
1309    1.083636
Name: fh_sku, dtype: float64
1310    0.586957
1311    1.391304
1312    1.456522
1313    0.565217
Name: mzc_sku, dtype: float64
1310    0.000000
1311    1.786408
1312    0.854369
1313    1.359223
Name: yp_sku, dtype: float64
1310    1.011236
1311    1.056180
1312    0.898876
1313    1.033708
Name: hs_sku, dtype: float64
1310    0.000000
1311    1.438202
1312    0.988764
1313    1.573034
Name: nyn_sku, dtype: float64
1310    0.000000
1311    1.857820
1312    1.232227
1313    0.909953
Name: atm_sku, dtype: float64
1310    0.549020
1311    1.281046
1312    1.725490
1313    0.444444
Name: msj_sku, dtype: float64
1310    0.412371
1311    1.340206
1312    1.340206
1313    0.907216
Name: fh_sku, dtype: float64
1314    1.0
Name: mzc_sku, dtype: float64
1314    1.0
Name: yp_sku, dtype: float64
1314    1.0
Name: hs_sku, dtype: float64
1314    1.0
Name: nyn_sku, dtype: float64
1314    1.0
Name: atm_sku, dtype: float64
1314    1.0
Name: msj_sku, dtype: float64
1314    1.0
Name: fh_sku, dtype: float64
1315    1.285714
1316    0.714286
Name: mzc_sku, dtype: float64
1315    1.2
1316    0.8
Name: yp_sku, dtype: float64
1315    1.25
1316    0.75
Name: hs_sku, dtype: float64
1315    2.0
1316    0.0
Name: nyn_sku, dtype: float64
1315    2.0
1316    0.0
Name: atm_sku, dtype: float64
1315    1.787234
1316    0.212766
Name: msj_sku, dtype: float64
1315    1.232143
1316    0.767857
Name: fh_sku, dtype: float64
1317    0.956522
1318    1.043478
Name: mzc_sku, dtype: float64
1317    0.923077
1318    1.076923
Name: yp_sku, dtype: float64
1317    0.947368
1318    1.052632
Name: hs_sku, dtype: float64
1317    1.0
1318    1.0
Name: nyn_sku, dtype: float64
1317    0.846154
1318    1.153846
Name: atm_sku, dtype: float64
1317    0.857143
1318    1.142857
Name: msj_sku, dtype: float64
1317    0.0
1318    2.0
Name: fh_sku, dtype: float64
1319    0.685714
1320    1.314286
Name: mzc_sku, dtype: float64
1319    0.909091
1320    1.090909
Name: yp_sku, dtype: float64
1319    0.903226
1320    1.096774
Name: hs_sku, dtype: float64
1319    1.333333
1320    0.666667
Name: nyn_sku, dtype: float64
1319    1.272727
1320    0.727273
Name: atm_sku, dtype: float64
1319    1.090909
1320    0.909091
Name: msj_sku, dtype: float64
1319    0.425532
1320    1.574468
Name: fh_sku, dtype: float64
1321    0.869565
1322    1.130435
Name: mzc_sku, dtype: float64
1321    0.5
1322    1.5
Name: yp_sku, dtype: float64
1321    0.133333
1322    1.866667
Name: hs_sku, dtype: float64
1321   NaN
1322   NaN
Name: nyn_sku, dtype: float64
1321   NaN
1322   NaN
Name: atm_sku, dtype: float64
1321   NaN
1322   NaN
Name: msj_sku, dtype: float64
1321    0.648649
1322    1.351351
Name: fh_sku, dtype: float64
1323    0.935897
1324    1.397436
1325    1.038462
1326    0.846154
1327    0.858974
1328    0.923077
Name: mzc_sku, dtype: float64
1323    1.324675
1324    1.558442
1325    1.376623
1326    0.753247
1327    0.883117
1328    0.103896
Name: yp_sku, dtype: float64
1323    0.808824
1324    1.441176
1325    0.955882
1326    0.882353
1327    0.955882
1328    0.955882
Name: hs_sku, dtype: float64
1323    1.200000
1324    1.129412
1325    1.058824
1326    1.058824
1327    1.411765
1328    0.141176
Name: nyn_sku, dtype: float64
1323    1.500000
1324    1.285714
1325    1.205357
1326    0.508929
1327    1.366071
1328    0.133929
Name: atm_sku, dtype: float64
1323    0.689189
1324    1.155405
1325    1.418919
1326    0.912162
1327    0.851351
1328    0.972973
Name: msj_sku, dtype: float64
1323    0.0
1324    0.0
1325    0.0
1326    3.0
1327    3.0
1328    0.0
Name: fh_sku, dtype: float64
1329    1.265823
1330    1.139241
1331    0.632911
1332    1.202532
1333    0.759494
Name: mzc_sku, dtype: float64
1329    0.0
1330    0.0
1331    5.0
1332    0.0
1333    0.0
Name: yp_sku, dtype: float64
1329   NaN
1330   NaN
1331   NaN
1332   NaN
1333   NaN
Name: hs_sku, dtype: float64
1329   NaN
1330   NaN
1331   NaN
1332   NaN
1333   NaN
Name: nyn_sku, dtype: float64
1329   NaN
1330   NaN
1331   NaN
1332   NaN
1333   NaN
Name: atm_sku, dtype: float64
1329   NaN
1330   NaN
1331   NaN
1332   NaN
1333   NaN
Name: msj_sku, dtype: float64
1329    1.190476
1330    1.095238
1331    0.761905
1332    1.000000
1333    0.952381
Name: fh_sku, dtype: float64
1334    1.025641
1335    0.897436
1336    0.833333
1337    0.833333
1338    1.410256
Name: mzc_sku, dtype: float64
1334    1.304348
1335    1.159420
1336    0.797101
1337    0.579710
1338    1.159420
Name: yp_sku, dtype: float64
1334    1.317829
1335    0.000000
1336    1.201550
1337    1.182171
1338    1.298450
Name: hs_sku, dtype: float64
1334   NaN
1335   NaN
1336   NaN
1337   NaN
1338   NaN
Name: nyn_sku, dtype: float64
1334   NaN
1335   NaN
1336   NaN
1337   NaN
1338   NaN
Name: atm_sku, dtype: float64
1334   NaN
1335   NaN
1336   NaN
1337   NaN
1338   NaN
Name: msj_sku, dtype: float64
1334   NaN
1335   NaN
1336   NaN
1337   NaN
1338   NaN
Name: fh_sku, dtype: float64
1339    1.026316
1340    1.105263
1341    0.868421
Name: mzc_sku, dtype: float64
1339    0.835821
1340    1.089552
1341    1.074627
Name: yp_sku, dtype: float64
1339    0.797468
1340    1.215190
1341    0.987342
Name: hs_sku, dtype: float64
1339    0.9375
1340    0.9750
1341    1.0875
Name: nyn_sku, dtype: float64
1339    0.954545
1340    1.136364
1341    0.909091
Name: atm_sku, dtype: float64
1339    1.358491
1340    0.962264
1341    0.679245
Name: msj_sku, dtype: float64
1339    0.477273
1340    1.363636
1341    1.159091
Name: fh_sku, dtype: float64
1342    0.882353
1343    1.274510
1344    0.490196
1345    1.078431
1346    1.274510
Name: mzc_sku, dtype: float64
1342    1.4
1343    1.2
1344    0.8
1345    1.0
1346    0.6
Name: yp_sku, dtype: float64
1342    1.190476
1343    1.071429
1344    0.476190
1345    1.190476
1346    1.071429
Name: hs_sku, dtype: float64
1342    1.071429
1343    1.071429
1344    0.357143
1345    1.071429
1346    1.428571
Name: nyn_sku, dtype: float64
1342    1.103896
1343    0.909091
1344    0.974026
1345    1.038961
1346    0.974026
Name: atm_sku, dtype: float64
1342    0.869565
1343    0.869565
1344    1.195652
1345    0.978261
1346    1.086957
Name: msj_sku, dtype: float64
1342    0.92
1343    1.16
1344    1.12
1345    0.80
1346    1.00
Name: fh_sku, dtype: float64
1347    0.647059
1348    1.352941
Name: mzc_sku, dtype: float64
1347    0.545455
1348    1.454545
Name: yp_sku, dtype: float64
1347    1.010989
1348    0.989011
Name: hs_sku, dtype: float64
1347    0.4
1348    1.6
Name: nyn_sku, dtype: float64
1347    0.542373
1348    1.457627
Name: atm_sku, dtype: float64
1347    0.9375
1348    1.0625
Name: msj_sku, dtype: float64
1347    1.166667
1348    0.833333
Name: fh_sku, dtype: float64
1349    1.0
Name: mzc_sku, dtype: float64
1349    1.0
Name: yp_sku, dtype: float64
1349    1.0
Name: hs_sku, dtype: float64
1349    1.0
Name: nyn_sku, dtype: float64
1349    1.0
Name: atm_sku, dtype: float64
1349    1.0
Name: msj_sku, dtype: float64
1349    1.0
Name: fh_sku, dtype: float64
1350    1.0
Name: mzc_sku, dtype: float64
1350    1.0
Name: yp_sku, dtype: float64
1350    1.0
Name: hs_sku, dtype: float64
1350    1.0
Name: nyn_sku, dtype: float64
1350    1.0
Name: atm_sku, dtype: float64
1350    1.0
Name: msj_sku, dtype: float64
1350    1.0
Name: fh_sku, dtype: float64
1351    1.053571
1352    0.946429
Name: mzc_sku, dtype: float64
1351    1.272727
1352    0.727273
Name: yp_sku, dtype: float64
1351    1.454545
1352    0.545455
Name: hs_sku, dtype: float64
1351    1.265306
1352    0.734694
Name: nyn_sku, dtype: float64
1351    1.228916
1352    0.771084
Name: atm_sku, dtype: float64
1351    1.21519
1352    0.78481
Name: msj_sku, dtype: float64
1351    1.0
1352    1.0
Name: fh_sku, dtype: float64
1353    0.955752
1354    1.044248
Name: mzc_sku, dtype: float64
1353    0.77193
1354    1.22807
Name: yp_sku, dtype: float64
1353    1.02
1354    0.98
Name: hs_sku, dtype: float64
1353    0.823529
1354    1.176471
Name: nyn_sku, dtype: float64
1353    1.268293
1354    0.731707
Name: atm_sku, dtype: float64
1353    0.8
1354    1.2
Name: msj_sku, dtype: float64
1353    0.754098
1354    1.245902
Name: fh_sku, dtype: float64
1355    0.943590
1356    0.984615
1357    0.902564
1358    1.169231

Name: mzc_sku, dtype: float64
1355    1.238710
1356    1.109677
1357    0.851613
1358    0.800000
Name: yp_sku, dtype: float64
1355    0.8
1356    0.0
1357    0.0
1358    3.2
Name: hs_sku, dtype: float64
1355    0.727273
1356    0.969697
1357    1.151515
1358    1.151515
Name: nyn_sku, dtype: float64
1355    1.042017
1356    1.142857
1357    0.873950
1358    0.941176
Name: atm_sku, dtype: float64
1355    1.24
1356    1.28
1357    0.52
1358    0.96
Name: msj_sku, dtype: float64
1355    0.930818
1356    1.157233
1357    0.880503
1358    1.031447
Name: fh_sku, dtype: float64
1359    0.900
1360    0.950
1361    0.925
1362    1.025
1363    1.075
1364    1.075
1365    1.000
1366    1.050
Name: mzc_sku, dtype: float64
1359    1.084746
1360    1.046005
1361    1.026634
1362    1.007264
1363    0.832930
1364    1.007264
1365    1.026634
1366    0.968523
Name: yp_sku, dtype: float64
1359    1.038391
1360    0.936015
1361    0.965265
1362    0.979890
1363    1.126143
1364    0.994516
1365    1.053016
1366    0.906764
Name: hs_sku, dtype: float64
1359   NaN
1360   NaN
1361   NaN
1362   NaN
1363   NaN
1364   NaN
1365   NaN
1366   NaN
Name: nyn_sku, dtype: float64
1359   NaN
1360   NaN
1361   NaN
1362   NaN
1363   NaN
1364   NaN
1365   NaN
1366   NaN
Name: atm_sku, dtype: float64
1359   NaN
1360   NaN
1361   NaN
1362   NaN
1363   NaN
1364   NaN
1365   NaN
1366   NaN
Name: msj_sku, dtype: float64
1359    0.0
1360    0.0
1361    8.0
1362    0.0
1363    0.0
1364    0.0
1365    0.0
1366    0.0
Name: fh_sku, dtype: float64
1367    0.740741
1368    1.185185
1369    1.185185
1370    0.888889
Name: mzc_sku, dtype: float64
1367    0.758621
1368    0.896552
1369    1.241379
1370    1.103448
Name: yp_sku, dtype: float64
1367    1.078652
1368    0.876404
1369    0.966292
1370    1.078652
Name: hs_sku, dtype: float64
1367    1.600000
1368    1.066667
1369    1.066667
1370    0.266667
Name: nyn_sku, dtype: float64
1367    1.333333
1368    1.333333
1369    0.820513
1370    0.512821
Name: atm_sku, dtype: float64
1367    1.021277
1368    0.936170
1369    1.021277
1370    1.021277
Name: msj_sku, dtype: float64
1367    0.933333
1368    0.800000
1369    1.066667
1370    1.200000
Name: fh_sku, dtype: float64
1371    0.843450
1372    0.728435
1373    1.150160
1374    1.130990
1375    1.073482
1376    1.073482
Name: mzc_sku, dtype: float64
1371    1.20
1372    0.24
1373    1.44
1374    1.20
1375    1.44
1376    0.48
Name: yp_sku, dtype: float64
1371    1.011834
1372    0.958580
1373    0.940828
1374    0.958580
1375    1.153846
1376    0.976331
Name: hs_sku, dtype: float64
1371   NaN
1372   NaN
1373   NaN
1374   NaN
1375   NaN
1376   NaN
Name: nyn_sku, dtype: float64
1371   NaN
1372   NaN
1373   NaN
1374   NaN
1375   NaN
1376   NaN
Name: atm_sku, dtype: float64
1371   NaN
1372   NaN
1373   NaN
1374   NaN
1375   NaN
1376   NaN
Name: msj_sku, dtype: float64
1371   NaN
1372   NaN
1373   NaN
1374   NaN
1375   NaN
1376   NaN
Name: fh_sku, dtype: float64
1377    0.909091
1378    1.090909
Name: mzc_sku, dtype: float64
1377   NaN
1378   NaN
Name: yp_sku, dtype: float64
1377    0.0
1378    2.0
Name: hs_sku, dtype: float64
1377   NaN
1378   NaN
Name: nyn_sku, dtype: float64
1377   NaN
1378   NaN
Name: atm_sku, dtype: float64
1377    0.0
1378    2.0
Name: msj_sku, dtype: float64
1377    0.985507
1378    1.014493
Name: fh_sku, dtype: float64
1379    1.141217
1380    1.044776
1381    1.269805
1382    1.318025
1383    1.237658
1384    1.318025
1385    0.819747
1386    0.739380
1387    0.819747
1388    0.723307
1389    0.739380
1390    0.932262
1391    1.060850
1392    0.835821
Name: mzc_sku, dtype: float64
1379    7.940299
1380    5.641791
1381    0.417910
1382    0.000000
1383    0.000000
1384    0.000000
1385    0.000000
1386    0.000000
1387    0.000000
1388    0.000000
1389    0.000000
1390    0.000000
1391    0.000000
1392    0.000000
Name: yp_sku, dtype: float64
1379    1.310909
1380    0.763636
1381    1.005455
1382    1.158182
1383    0.903636
1384    0.890909
1385    0.980000
1386    0.890909
1387    1.069091
1388    1.056364
1389    0.801818
1390    1.043636
1391    1.043636
1392    1.081818
Name: hs_sku, dtype: float64
1379   NaN
1380   NaN
1381   NaN
1382   NaN
1383   NaN
1384   NaN
1385   NaN
1386   NaN
1387   NaN
1388   NaN
1389   NaN
1390   NaN
1391   NaN
1392   NaN
Name: nyn_sku, dtype: float64
1379     0.0
1380     0.0
1381     0.0
1382     0.0
1383    14.0
1384     0.0
1385     0.0
1386     0.0
1387     0.0
1388     0.0
1389     0.0
1390     0.0
1391     0.0
1392     0.0
Name: atm_sku, dtype: float64
1379    0.944282
1380    1.129032
1381    1.252199
1382    0.513196
1383    1.313783
1384    1.354839
1385    0.903226
1386    0.923754
1387    1.067449
1388    0.985337
1389    1.026393
1390    0.903226
1391    0.903226
1392    0.780059
Name: msj_sku, dtype: float64
1379    1.160862
1380    0.928690
1381    1.114428
1382    1.044776
1383    0.928690
1384    0.998342
1385    1.021559
1386    0.998342
1387    1.044776
1388    0.928690
1389    0.975124
1390    0.975124
1391    0.951907
1392    0.928690
Name: fh_sku, dtype: float64
1393    1.135135
1394    0.932432
1395    0.648649
1396    0.932432
1397    1.094595
1398    1.256757
Name: mzc_sku, dtype: float64
1393    1.465116
1394    1.255814
1395    0.558140
1396    1.325581
1397    0.906977
1398    0.488372
Name: yp_sku, dtype: float64
1393    1.340426
1394    0.765957
1395    0.574468
1396    0.829787
1397    1.148936
1398    1.340426
Name: hs_sku, dtype: float64
1393    0.642857
1394    1.392857
1395    0.535714
1396    1.392857
1397    0.857143
1398    1.178571
Name: nyn_sku, dtype: float64
1393    1.384615
1394    0.923077
1395    0.230769
1396    1.153846
1397    1.153846
1398    1.153846
Name: atm_sku, dtype: float64
1393    1.565217
1394    0.521739
1395    0.521739
1396    1.565217
1397    0.521739
1398    1.304348
Name: msj_sku, dtype: float64
1393    0.000000
1394    0.000000
1395    0.000000
1396    1.363636
1397    2.454545
1398    2.181818
Name: fh_sku, dtype: float64
1399    0.594406
1400    0.979021
1401    0.944056
1402    1.223776
1403    1.048951
1404    1.048951
1405    1.083916
1406    1.118881
1407    0.979021
1408    0.979021
Name: mzc_sku, dtype: float64
1399    0.000000
1400    1.111111
1401    1.481481
1402    1.111111
1403    1.481481
1404    1.481481
1405    1.111111
1406    0.740741
1407    0.740741
1408    0.740741
Name: yp_sku, dtype: float64
1399    0.000000
1400    0.000000
1401    1.538462
1402    0.769231
1403    1.538462
1404    1.538462
1405    1.538462
1406    1.538462
1407    0.769231
1408    0.769231
Name: hs_sku, dtype: float64
1399    0.000000
1400    0.000000
1401    1.666667
1402    1.666667
1403    1.666667
1404    0.000000
1405    1.666667
1406    1.666667
1407    1.666667
1408    0.000000
Name: nyn_sku, dtype: float64
1399    0.000000
1400    0.000000
1401    0.769231
1402    1.538462
1403    1.538462
1404    1.538462
1405    1.538462
1406    0.769231
1407    1.538462
1408    0.769231
Name: atm_sku, dtype: float64
1399    0.000000
1400    0.000000
1401    0.769231
1402    1.538462
1403    1.538462
1404    1.538462
1405    2.307692
1406    0.769231
1407    0.769231
1408    0.769231
Name: msj_sku, dtype: float64
1399    3.146067
1400    1.685393
1401    0.337079
1402    0.674157
1403    0.337079
1404    1.460674
1405    0.449438
1406    0.786517
1407    0.561798
1408    0.561798
Name: fh_sku, dtype: float64
1409    0.357616
1410    0.357616
1411    1.668874
1412    1.112583
1413    1.231788
1414    1.271523
Name: mzc_sku, dtype: float64
1409    2.444444
1410    0.555556
1411    1.814815
1412    0.333333
1413    0.703704
1414    0.148148
Name: yp_sku, dtype: float64
1409    0.621762
1410    0.186528
1411    0.435233
1412    1.616580
1413    1.772021
1414    1.367876
Name: hs_sku, dtype: float64
1409    0.000000
1410    0.000000
1411    3.692308
1412    2.307692
1413    0.000000
1414    0.000000
Name: nyn_sku, dtype: float64
1409    0.000000
1410    0.000000
1411    3.245902
1412    2.655738
1413    0.000000
1414    0.098361
Name: atm_sku, dtype: float64
1409    3.719457
1410    1.411765
1411    0.000000
1412    0.868778
1413    0.000000
1414    0.000000
Name: msj_sku, dtype: float64
1409    0.0
1410    0.0
1411    6.0
1412    0.0
1413    0.0
1414    0.0
Name: fh_sku, dtype: float64
1415    0.478261
1416    0.782609
1417    1.043478
1418    1.043478
1419    1.391304
1420    1.260870
Name: mzc_sku, dtype: float64
1415    1.034483
1416    1.034483
1417    1.034483
1418    1.034483
1419    0.931034
1420    0.931034
Name: yp_sku, dtype: float64
1415    0.956522
1416    1.217391
1417    0.782609
1418    0.956522
1419    1.043478
1420    1.043478
Name: hs_sku, dtype: float64
1415    0.954545
1416    0.886364
1417    1.090909
1418    1.022727
1419    1.022727
1420    1.022727
Name: nyn_sku, dtype: float64
1415    0.965217
1416    0.991304
1417    0.886957
1418    1.304348
1419    0.913043
1420    0.939130
Name: atm_sku, dtype: float64
1415    1.40625
1416    0.84375
1417    0.93750
1418    0.93750
1419    0.93750
1420    0.93750
Name: msj_sku, dtype: float64
1415    0.0
1416    3.0
1417    0.0
1418    0.0
1419    3.0
1420    0.0
Name: fh_sku, dtype: float64
1421    1.002101
1422    0.737395
1423    0.813025
1424    1.134454
1425    1.134454
1426    1.210084
1427    1.077731
1428    0.926471
1429    0.964286
Name: mzc_sku, dtype: float64
1421    0.022785
1422    1.253165
1423    0.865823
1424    2.141772
1425    0.729114
1426    1.025316
1427    1.070886
1428    0.843038
1429    1.048101
Name: yp_sku, dtype: float64
1421    0.000000
1422    2.302326
1423    2.033223
1424    0.239203
1425    0.598007
1426    0.747508
1427    1.345515
1428    1.524917
1429    0.209302
Name: hs_sku, dtype: float64
1421    1.125
1422    3.150
1423    1.575
1424    1.575
1425    0.450
1426    1.125
1427    0.000
1428    0.000
1429    0.000
Name: nyn_sku, dtype: float64
1421    4.846154
1422    1.384615
1423    0.692308
1424    0.692308
1425    0.692308
1426    0.692308
1427    0.000000
1428    0.000000
1429    0.000000
Name: atm_sku, dtype: float64
1421    0.840659
1422    0.989011
1423    1.335165
1424    1.236264
1425    1.582418
1426    0.593407
1427    0.741758
1428    0.791209
1429    0.890110
Name: msj_sku, dtype: float64
1421    1.042105
1422    1.705263
1423    0.947368
1424    0.852632
1425    0.947368
1426    1.042105
1427    1.136842
1428    0.947368
1429    0.378947
Name: fh_sku, dtype: float64
1430    1.0
1431    1.0
Name: mzc_sku, dtype: float64
1430   NaN
1431   NaN
Name: yp_sku, dtype: float64
1430    0.0
1431    2.0
Name: hs_sku, dtype: float64
1430   NaN
1431   NaN
Name: nyn_sku, dtype: float64
1430    2.0
1431    0.0
Name: atm_sku, dtype: float64
1430   NaN
1431   NaN
Name: msj_sku, dtype: float64
1430    1.302326
1431    0.697674
Name: fh_sku, dtype: float64
1432    1.0
Name: mzc_sku, dtype: float64
1432   NaN
Name: yp_sku, dtype: float64
1432    1.0
Name: hs_sku, dtype: float64
1432   NaN
Name: nyn_sku, dtype: float64
1432   NaN
Name: atm_sku, dtype: float64
1432    1.0
Name: msj_sku, dtype: float64
1432    1.0
Name: fh_sku, dtype: float64
1433    1.0
Name: mzc_sku, dtype: float64
1433    1.0
Name: yp_sku, dtype: float64
1433    1.0
Name: hs_sku, dtype: float64
1433   NaN
Name: nyn_sku, dtype: float64
1433    1.0
Name: atm_sku, dtype: float64
1433    1.0
Name: msj_sku, dtype: float64
1433   NaN
Name: fh_sku, dtype: float64
1434    1.0
Name: mzc_sku, dtype: float64
1434    1.0
Name: yp_sku, dtype: float64
1434    1.0
Name: hs_sku, dtype: float64
1434   NaN
Name: nyn_sku, dtype: float64
1434    1.0
Name: atm_sku, dtype: float64
1434    1.0
Name: msj_sku, dtype: float64
1434   NaN
Name: fh_sku, dtype: float64
1435    1.054830
1436    1.013055
1437    1.033943
1438    0.898172
Name: mzc_sku, dtype: float64
1435   NaN
1436   NaN
1437   NaN
1438   NaN
Name: yp_sku, dtype: float64
1435   NaN
1436   NaN
1437   NaN
1438   NaN
Name: hs_sku, dtype: float64
1435   NaN
1436   NaN
1437   NaN
1438   NaN
Name: nyn_sku, dtype: float64
1435   NaN
1436   NaN
1437   NaN
1438   NaN
Name: atm_sku, dtype: float64
1435    1.167959
1436    1.012920
1437    0.992248
1438    0.826873
Name: msj_sku, dtype: float64
1435   NaN
1436   NaN
1437   NaN
1438   NaN
Name: fh_sku, dtype: float64
1439    0.473846
1440    0.323077
1441    0.366154
1442    0.990769
1443    1.550769
1444    1.507692
1445    1.787692
Name: mzc_sku, dtype: float64
1439    0.0
1440    0.0
1441    0.0
1442    0.0
1443    0.0
1444    7.0
1445    0.0
Name: yp_sku, dtype: float64
1439    0.0
1440    0.0
1441    0.0
1442    0.0
1443    7.0
1444    0.0
1445    0.0
Name: hs_sku, dtype: float64
1439   NaN
1440   NaN
1441   NaN
1442   NaN
1443   NaN
1444   NaN
1445   NaN
Name: nyn_sku, dtype: float64
1439   NaN
1440   NaN
1441   NaN
1442   NaN
1443   NaN
1444   NaN
1445   NaN
Name: atm_sku, dtype: float64
1439   NaN
1440   NaN
1441   NaN
1442   NaN
1443   NaN
1444   NaN
1445   NaN
Name: msj_sku, dtype: float64
1439   NaN
1440   NaN
1441   NaN
1442   NaN
1443   NaN
1444   NaN
1445   NaN
Name: fh_sku, dtype: float64
1446    0.960
1447    1.008
1448    1.032
Name: mzc_sku, dtype: float64
1446    1.333333
1447    1.111111
1448    0.555556
Name: yp_sku, dtype: float64
1446   NaN
1447   NaN
1448   NaN
Name: hs_sku, dtype: float64
1446   NaN
1447   NaN
1448   NaN
Name: nyn_sku, dtype: float64
1446   NaN
1447   NaN
1448   NaN
Name: atm_sku, dtype: float64
1446    1.045455
1447    1.136364
1448    0.818182
Name: msj_sku, dtype: float64
1446   NaN
1447   NaN
1448   NaN
Name: fh_sku, dtype: float64
1449    0.949640
1450    0.949640
1451    0.863309
1452    1.237410
Name: mzc_sku, dtype: float64
1449    1.52
1450    1.44
1451    0.00
1452    1.04
Name: yp_sku, dtype: float64
1449   NaN
1450   NaN
1451   NaN
1452   NaN
Name: hs_sku, dtype: float64
1449   NaN
1450   NaN
1451   NaN
1452   NaN
Name: nyn_sku, dtype: float64
1449   NaN
1450   NaN
1451   NaN
1452   NaN
Name: atm_sku, dtype: float64
1449    0.561404
1450    0.701754
1451    2.245614
1452    0.491228
Name: msj_sku, dtype: float64
1449   NaN
1450   NaN
1451   NaN
1452   NaN
Name: fh_sku, dtype: float64
1453    1.120690
1454    0.793103
1455    1.086207
Name: mzc_sku, dtype: float64
1453    0.937500
1454    0.914062
1455    1.148438
Name: yp_sku, dtype: float64
1453    0.923077
1454    1.552448
1455    0.524476
Name: hs_sku, dtype: float64
1453    1.16
1454    1.16
1455    0.68
Name: nyn_sku, dtype: float64
1453    0.358974
1454    1.564103
1455    1.076923
Name: atm_sku, dtype: float64
1453    0.966102
1454    0.830508
1455    1.203390
Name: msj_sku, dtype: float64
1453    0.00000
1454    1.76087
1455    1.23913
Name: fh_sku, dtype: float64
1456    1.733333
1457    0.266667
Name: mzc_sku, dtype: float64
1456    1.555556
1457    0.444444
Name: yp_sku, dtype: float64
1456    1.72
1457    0.28
Name: hs_sku, dtype: float64
1456    2.0
1457    0.0
Name: nyn_sku, dtype: float64
1456    1.5
1457    0.5
Name: atm_sku, dtype: float64
1456    1.555556
1457    0.444444
Name: msj_sku, dtype: float64
1456   NaN
1457   NaN
Name: fh_sku, dtype: float64
1458    1.060976
1459    0.768293
1460    1.170732
Name: mzc_sku, dtype: float64
1458   NaN
1459   NaN
1460   NaN
Name: yp_sku, dtype: float64
1458    1.098214
1459    0.803571
1460    1.098214
Name: hs_sku, dtype: float64
1458   NaN
1459   NaN
1460   NaN
Name: nyn_sku, dtype: float64
1458   NaN
1459   NaN
1460   NaN
Name: atm_sku, dtype: float64
1458   NaN
1459   NaN
1460   NaN
Name: msj_sku, dtype: float64
1458    1.153846
1459    1.015385
1460    0.830769
Name: fh_sku, dtype: float64
1461    0.727273
1462    1.272727
Name: mzc_sku, dtype: float64
1461    0.0
1462    2.0
Name: yp_sku, dtype: float64
1461    1.0
1462    1.0
Name: hs_sku, dtype: float64
1461    2.0
1462    0.0
Name: nyn_sku, dtype: float64
1461    2.0
1462    0.0
Name: atm_sku, dtype: float64
1461    1.0
1462    1.0
Name: msj_sku, dtype: float64
1461   NaN
1462   NaN
Name: fh_sku, dtype: float64
1463    1.023256
1464    0.976744
Name: mzc_sku, dtype: float64
1463    0.819672
1464    1.180328
Name: yp_sku, dtype: float64
1463    1.230769
1464    0.769231
Name: hs_sku, dtype: float64
1463    0.916667
1464    1.083333
Name: nyn_sku, dtype: float64
1463    0.711111
1464    1.288889
Name: atm_sku, dtype: float64
1463    0.592593
1464    1.407407
Name: msj_sku, dtype: float64
1463    1.052632
1464    0.947368
Name: fh_sku, dtype: float64
1465    0.8125
1466    1.1875
Name: mzc_sku, dtype: float64
1465    0.935065
1466    1.064935
Name: yp_sku, dtype: float64
1465    0.666667
1466    1.333333
Name: hs_sku, dtype: float64
1465    1.294118
1466    0.705882
Name: nyn_sku, dtype: float64
1465    1.2
1466    0.8
Name: atm_sku, dtype: float64
1465    2.0
1466    0.0
Name: msj_sku, dtype: float64
1465    2.0
1466    0.0
Name: fh_sku, dtype: float64
1467    1.0
Name: mzc_sku, dtype: float64
1467   NaN
Name: yp_sku, dtype: float64
1467   NaN
Name: hs_sku, dtype: float64
1467   NaN
Name: nyn_sku, dtype: float64
1467   NaN
Name: atm_sku, dtype: float64
1467   NaN
Name: msj_sku, dtype: float64
1467    1.0
Name: fh_sku, dtype: float64
1468    1.0
Name: mzc_sku, dtype: float64
1468   NaN
Name: yp_sku, dtype: float64
1468   NaN

Name: hs_sku, dtype: float64
1468   NaN
Name: nyn_sku, dtype: float64
1468   NaN
Name: atm_sku, dtype: float64
1468   NaN
Name: msj_sku, dtype: float64
1468   NaN
Name: fh_sku, dtype: float64
1469    1.026846
1470    0.973154
Name: mzc_sku, dtype: float64
1469   NaN
1470   NaN
Name: yp_sku, dtype: float64
1469    1.134328
1470    0.865672
Name: hs_sku, dtype: float64
1469    1.0
1470    1.0
Name: nyn_sku, dtype: float64
1469    1.131313
1470    0.868687
Name: atm_sku, dtype: float64
1469    0.991304
1470    1.008696
Name: msj_sku, dtype: float64
1469    1.0
1470    1.0
Name: fh_sku, dtype: float64
1471    1.0
Name: mzc_sku, dtype: float64
1471   NaN
Name: yp_sku, dtype: float64
1471   NaN
Name: hs_sku, dtype: float64
1471   NaN
Name: nyn_sku, dtype: float64
1471   NaN
Name: atm_sku, dtype: float64
1471   NaN
Name: msj_sku, dtype: float64
1471   NaN
Name: fh_sku, dtype: float64
1472    1.0
Name: mzc_sku, dtype: float64
1472    1.0
Name: yp_sku, dtype: float64
1472    1.0
Name: hs_sku, dtype: float64
1472   NaN
Name: nyn_sku, dtype: float64
1472   NaN
Name: atm_sku, dtype: float64
1472    1.0
Name: msj_sku, dtype: float64
1472    1.0
Name: fh_sku, dtype: float64

In [54]:
out_data.to_csv('C:/Users/Trine/Desktop/my_data/1.csv')

# 计算重复率

In [3]:
duplicate = pd.read_excel('C:/Users/Trine/Desktop/my_data/重复_抽样.xlsx')

In [4]:
duplicate.head()

,store_id,create_time,sku总数,美赞臣sku数,美赞臣标注,雅培sku数,雅培标注,惠氏sku数,惠氏标注,诺优能sku数,诺优能标注,爱他美sku数,爱他美标注,美素佳儿sku数,美素佳儿标注,飞鹤sku数,飞鹤标注
0,50295,2019-07-01 12:05:00,109,35,没有去重,17,NaN,17,NaN,4,正常,4,正常,31,没有去重,1,误判
1,50295,2019-08-05 14:37:00,77,31,没有去重,9,NaN,18,正常,3,NaN,4,NaN,12,NaN,0,正常
2,50295,2019-09-03 14:27:00,79,35,没有去重,12,NaN,16,NaN,4,没有去重,4,没有去重,8,NaN,0,NaN
3,50295,2019-10-18 15:02:00,100,24,没有去重,19,正常,16,NaN,0,NaN,4,NaN,37,正常,0,NaN
4,50295,2019-11-08 16:07:00,67,27,没有去重,7,NaN,5,NaN,4,NaN,5,正常,19,NaN,0,NaN
5,51455,2019-07-16 10:30:00,478,99,NaN,77,正常,167,没有去重,8,正常,29,正常,98,没有去重,0,NaN
6,51455,2019-08-27 09:57:00,491,96,NaN,105,没有去重,174,没有去重,7,正常,20,NaN,89,没有去重,0,NaN
7,51455,2019-09-10 09:58:00,389,95,正常,78,正常,104,正常,14,正常,14,正常,84,正常,0,正常
8,51455,2019-10-16 10:19:00,368,99,NaN,69,NaN,93,NaN,9,NaN,26,NaN,72,NaN,0,NaN
9,51455,2019-11-26 10:31:00,344,101,正常,58,正常,85,正常,7,正常,29,正常,64,正常,0,正常
10,53868,2019-06-10 15:24:00,379,118,没有去重,71,NaN,92,没有去重,15,NaN,49,NaN,34,NaN,0,NaN
11,53868,2019-07-01 14:54:00,402,136,没有去重,65,NaN,96,NaN,15,NaN,38,NaN,52,NaN,0,NaN
12,53868,2019-07-31 15:14:00,389,113,没有去重,89,没有去重,70,NaN,17,NaN,54,没有去重,46,NaN,0,NaN
13,53868,2019-08-12 19:00:00,444,139,没有去重,81,没有去重,108,没有去重,8,NaN,60,没有去重,48,正常,0,NaN
14,53868,2019-09-02 15:21:00,436,137,没有去重,91,没有去重,73,正常,19,NaN,60,没有去重,56,没有去重,0,NaN
15,53868,2019-10-12 16:25:00,448,135,没有去重,83,没有去重,98,没有去重,19,NaN,47,正常,66,没有去重,0,NaN
16,53868,2019-11-04 17:13:00,346,107,没有去重,46,正常,92,正常,18,正常,56,正常,27,NaN,0,NaN
17,53868,2019-11-18 15:40:00,284,87,没有去重,11,NaN,85,NaN,18,NaN,40,NaN,43,NaN,0,NaN
18,72065,2019-06-20 16:57:00,272,34,正常,7,正常,101,正常,33,没有去重,0,NaN,29,正常,68,没有去重
19,72065,2019-07-03 18:48:00,231,33,正常,17,正常,99,正常,0,正常,0,正常,28,正常,54,正常
20,72065,2019-08-08 15:52:00,336,52,没有去重,11,NaN,196,没有去重,0,NaN,0,NaN,76,没有去重,1,误判
21,72065,2019-09-05 18:17:00,330,39,NaN,14,NaN,124,没有去重,12,正常,11,没有去重,74,没有去重,56,没有去重
22,72065,2019-10-15 19:17:00,381,60,正常,11,NaN,151,没有去重,21,没有去重,6,NaN,60,没有去重,72,没有去重
23,72065,2019-10-29 16:54:00,386,45,NaN,10,NaN,147,没有去重,6,正常,26,正常,58,没有去重,94,没有去重
24,72065,2019-11-06 16:58:00,407,54,正常,16,没有去重,151,没有去重,7,正常,13,正常,44,没有去重,122,没有去重
25,72065,2019-11-21 14:51:00,390,55,没有去重,25,没有去重,101,没有去重,11,正常,4,正常,82,没有去重,112,没有去重
26,72664,2019-06-19 12:57:00,549,72,NaN,45,没有去重,304,没有去重,26,没有去重,73,没有去重,29,NaN,0,NaN
27,72664,2019-07-24 11:16:00,496,73,NaN,38,NaN,278,没有去重,30,没有去重,38,正常,39,NaN,0,NaN
28,72664,2019-08-28 17:37:00,465,66,NaN,41,NaN,274,没有去重,9,NaN,4,NaN,71,没有去重,0,NaN
29,72664,2019-09-16 12:44:00,382,81,正常,26,正常,195,NaN,5,NaN,7,NaN,68,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,142650,2019-08-19 15:41:00,332,64,没有去重,50,正常,65,正常,7,正常,40,正常,60,正常,46,没有去重
33,142650,2019-09-05 19:45:00,250,37,NaN,48,NaN,59,NaN,0,NaN,13,NaN,54,NaN,39,没有去重
34,142650,2019-10-08 16:12:00,381,53,正常,56,没有去重,83,正常,17,正常,37,正常,86,没有去重,49,没有去重
35,142650,2019-10-24 11:51:00,249,55,正常,20,正常,69,正常,8,正常,30,正常,62,没有去重,5,正常
36,142650,2019-10-30 11:55:00,277,58,没有去重,18,正常,66,正常,8,正常,29,正常,69,没有去重,29,正常
37,142650,2019-11-04 16:24:00,291,46,NaN,25,NaN,76,没有去重,13,正常,29,NaN,67,没有去重,35,没有去重
38,150244,2019-07-03 13:09:00,135,52,漏拍,0,NaN,62,正常,0,NaN,0,NaN,0,NaN,21,NaN
39,150244,2019-08-01 12:46:00,54,32,NaN,0,NaN,22,NaN,0,NaN,0,NaN,0,NaN,0,NaN
40,150244,2019-08-19 17:21:00,241,50,NaN,19,NaN,84,没有去重,2,NaN,13,NaN,18,NaN,55,NaN
41,150244,2019-09-02 09:24:00,295,49,NaN,21,NaN,90,没有去重,5,NaN,29,没有去重,45,没有去重,56,NaN
42,150244,2019-10-14 14:58:00,211,17,NaN,29,NaN,60,漏拍,11,NaN,24,正常,26,正常,44,正常
43,150244,2019-11-04 14:12:00,305,32,NaN,31,正常,83,没有去重,12,正常,45,没有去重,49,没有去重,53,NaN
44,150244,2019-11-11 11:49:00,153,38,NaN,4,NaN,80,没有去重,0,NaN,0,NaN,0,NaN,31,NaN
45,158650,2019-10-15 13:11:00,153,55,NaN,4,NaN,62,NaN,0,NaN,0,NaN,31,正常,1,正常
46,158650,2019-11-07 14:09:00,253,46,NaN,38,正常,69,正常,4,NaN,5,NaN,90,没有去重,1,NaN
47,187084,2019-08-24 19:42:00,333,99,没有去重,58,没有去重,51,正常,18,正常,70,没有去重,37,正常,0,正常
48,187084,2019-09-06 10:48:00,239,110,没有去重,31,正常,58,正常,2,正常,30,正常,8,正常,0,正常
49,187084,2019-10-11 12:12:00,329,101,没有去重,80,没有去重,48,正常,5,正常,53,正常,42,正常,0,正常
50,187084,2019-11-26 11:35:00,266,84,没有去重,58,NaN,42,NaN,2,NaN,41,NaN,39,没有去重,0,NaN
51,240863,2019-07-12 16:11:00,207,73,NaN,0,NaN,79,NaN,0,NaN,0,NaN,55,NaN,0,NaN
52,240863,2019-08-08 15:08:00,283,89,正常,0,NaN,86,正常,23,NaN,53,NaN,30,NaN,2,误判
53,240863,2019-09-19 13:58:00,431,122,没有去重,1,误判,100,没有去重,48,没有去重,111,没有去重,49,正常,0,正常
54,240863,2019-10-17 14:13:00,355,134,没有去重,0,NaN,70,没有去重,26,没有去重,82,没有去重,43,NaN,0,NaN
55,240863,2019-10-29 14:13:00,301,73,NaN,0,NaN,76,没有去重,23,没有去重,74,没有去重,55,NaN,0,NaN
56,240863,2019-11-11 13:57:00,283,114,没有去重,0,NaN,59,没有去重,25,没有去重,84,没有去重,0,NaN,1,误判
57,240863,2019-11-20 12:08:00,403,198,没有去重,0,正常,75,没有去重,23,没有去重,63,没有去重,44,正常,0,正常
58,242359,2019-10-11 10:17:00,260,100,没有去重,36,没有去重,8,没有去重,18,没有去重,25,没有去重,17,没有去重,56,没有去重
59,242358,2019-10-15 17:09:00,278,27,没有去重,39,没有去重,65,没有去重,11,没有去重,25,没有去重,42,没有去重,69,没有去重
60,242562,2019-10-11 13:44:00,292,59,正常,14,误判,64,没有去重,31,没有去重,51,没有去重,48,没有去重,25,没有去重
61,242562,2019-11-07 17:09:00,191,53,正常,8,没有去重,24,没有去重,18,没有去重,32,没有去重,31,没有去重,25,没有去重

In [34]:
from collections import Counter
for i in range(len(duplicate)):
    a = Counter(duplicate.iloc[i,:] == '没有去重')
    duplicate_proportion = a[1]/7
    duplicate.loc[i,'duplicate'] = duplicate_proportion

In [37]:
duplicate.to_excel('C:/Users/Trine/Desktop/my_data/重复_抽样2.xlsx')